/*
	SIC LABORATORY,	LG ELECTRONICS INC., SEOUL, KOREA
	Copyright(c) 2013 by LG	Electronics Inc.

	This program is	free software; you can redistribute it and/or
	modify it under	the terms of the GNU General Public License
	version	2 as published by the Free Software Foundation.

	This program is	distributed in the hope	that it	will be	useful,
	but WITHOUT ANY	WARRANTY; without even the implied warranty of
	MERCHANTABILITY	or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.
*/

/*****************************************************************************
**
**	Name:DBB_DEMOD_L1_Commands.h
**
**	Description:
**
**	Functions
**	Implemented:
**
**	References:
**
**	Exports:
**
**	Dependencies:
**
**
**	Revision History:
**
**	Date			Author				Description
**	-------------------------------------------------------------------------
**	20-01-2016		Jeongpil Yun		Initial draft.
**
*****************************************************************************/

#ifndef	_DBB_DEMOD_L1_COMMANDS_H_
#define	_DBB_DEMOD_L1_COMMANDS_H_

/*-------------------------------------------------------------------------*/
/* common definition */
typedef enum {
	DEMOD_LOCK_LOCKED						= 0x01,
	DEMOD_LOCK_UNLOCKED						= 0x00,
} DEMOD_LOCK;

typedef enum {
	DEMOD_MODULATION_DEFAULT				= 0x20,
	DEMOD_MODULATION_VSB					= 0x08,
	DEMOD_MODULATION_QAM					= 0x48,
	DEMOD_MODULATION_ATSC3					= 0x09,
	DEMOD_MODULATION_ISDBT					= 0x10,
	DEMOD_MODULATION_ISDBC					= 0x11,
	DEMOD_MODULATION_DVBT					= 0x20,
	DEMOD_MODULATION_DVBT2					= 0x21,
	DEMOD_MODULATION_DVBC					= 0x40,
	DEMOD_MODULATION_DVBC2					= 0x41,
	DEMOD_MODULATION_DVBS					= 0x60,
	DEMOD_MODULATION_DVBS2					= 0x61,
	DEMOD_MODULATION_DVBS2X					= 0x62,
	DEMOD_MODULATION_DTMB					= 0x18,
	DEMOD_MODULATION_AUTO_DETECT			= 0x0F,			//15
	DEMOD_MODULATION_ANALOG					= 0x64,			//100
	DEMOD_MODULATION_SLEEP					= 0xC8,			//200, lgit
	DEMOD_MODULATION_UNKNOWN				= 0xFA,			//250, lgit
} DEMOD_MODULATION;

typedef enum {
	DEMOD_CONSTELLATION_QPSK				= 0x00,
	DEMOD_CONSTELLATION_DQPSK				= 0x01,
	DEMOD_CONSTELLATION_QAM16				= 0x02,
	DEMOD_CONSTELLATION_QAM32				= 0x03,
	DEMOD_CONSTELLATION_QAM64				= 0x04,
	DEMOD_CONSTELLATION_QAM128				= 0x05,
	DEMOD_CONSTELLATION_QAM256				= 0x06,
	DEMOD_CONSTELLATION_QAM1024				= 0x07,
	DEMOD_CONSTELLATION_QAM4096				= 0x08,
	DEMOD_CONSTELLATION_PSK8				= 0x09,
	DEMOD_CONSTELLATION_VSB8				= 0x0A,
	DEMOD_CONSTELLATION_QAM4				= 0x0B,
	DEMOD_CONSTELLATION_APSK16				= 0x0C,
	DEMOD_CONSTELLATION_APSK32				= 0x0D,
	DEMOD_CONSTELLATION_QAM4NR				= 0x0E,
	DEMOD_CONSTELLATION_UNKNOWN				= 0x0F,
} DEMOD_CONSTELLATION;

typedef enum {
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_1_2		= 0x00,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_1_3		= 0x01,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_2_3		= 0x02,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_1_4		= 0x03,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_3_4		= 0x04,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_2_5		= 0x05,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_3_5		= 0x06,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_4_5		= 0x07,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_5_6		= 0x08,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_7_8		= 0x09,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_8_9		= 0x0a,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_9_10		= 0x0b,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_13_45	= 0x0c,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_9_20		= 0x0d,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_90_180	= 0x0e,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_96_180	= 0x0f,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_11_20	= 0x10,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_100_180	= 0x11,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_104_180	= 0x12,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_18_30	= 0x13,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_28_45	= 0x14,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_23_36	= 0x15,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_20_30	= 0x16,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_25_36	= 0x17,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_128_180	= 0x18,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_13_18	= 0x19,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_132_180	= 0x1a,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_140_180	= 0x1b,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_154_180	= 0x1c,
	DEMOD_CODERATE_DVBS_DVBS2_DTMB_UNKNOWN	= 0x1f,
} DEMOD_CODERATE_DVBS_DVBS2_DTMB;

typedef enum {
	DEMOD_CODERATE_ATSC3_2_15				= 0x00,
	DEMOD_CODERATE_ATSC3_3_15				= 0x01,
	DEMOD_CODERATE_ATSC3_4_15				= 0x02,
	DEMOD_CODERATE_ATSC3_5_15				= 0x03,
	DEMOD_CODERATE_ATSC3_6_15				= 0x04,
	DEMOD_CODERATE_ATSC3_7_15				= 0x05,
	DEMOD_CODERATE_ATSC3_8_15				= 0x06,
	DEMOD_CODERATE_ATSC3_9_15				= 0x07,
	DEMOD_CODERATE_ATSC3_10_15				= 0x08,
	DEMOD_CODERATE_ATSC3_11_15				= 0x09,
	DEMOD_CODERATE_ATSC3_12_15				= 0x0A,
	DEMOD_CODERATE_ATSC3_13_15				= 0x0B,
} DEMOD_CODERATE_ATSC3;

typedef enum {
	DEMOD_CODERATE_DVBT_ISDBT_1_2			= 0x00,
	DEMOD_CODERATE_DVBT_ISDBT_2_3			= 0x01,
	DEMOD_CODERATE_DVBT_ISDBT_3_4			= 0x02,
	DEMOD_CODERATE_DVBT_ISDBT_5_6			= 0x03,
	DEMOD_CODERATE_DVBT_ISDBT_7_8			= 0x04,
} DEMOD_CODERATE_DVBT_ISDBT;

typedef enum {
	DEMOD_CODERATE_DVBT2_1_2				= 0x00,
	DEMOD_CODERATE_DVBT2_3_5				= 0x01,
	DEMOD_CODERATE_DVBT2_2_3				= 0x02,
	DEMOD_CODERATE_DVBT2_3_4				= 0x03,
	DEMOD_CODERATE_DVBT2_4_5				= 0x04,
	DEMOD_CODERATE_DVBT2_5_6				= 0x05,
} DEMOD_CODERATE_DVBT2;

typedef enum {
	DEMOD_FFT_MODE_2K						= 0x00,
	DEMOD_FFT_MODE_8K						= 0x01,
	DEMOD_FFT_MODE_4K						= 0x02,
	DEMOD_FFT_MODE_1K						= 0x03,
	DEMOD_FFT_MODE_16K						= 0x04,
	DEMOD_FFT_MODE_32K						= 0x05,
	DEMOD_FFT_MODE_512K						= 0x06,
	DEMOD_FFT_MODE_256K						= 0x07,
} DEMOD_FFT_MODE;

/*-------------------------------------------------------------------------*/
/* configs for supported commands */
/* system */
#define	DEMOD_CMD_GET_REG
#define	DEMOD_CMD_SET_REG
#define	DEMOD_CMD_GET_PROP
#define	DEMOD_CMD_SET_PROP
#define	DEMOD_CMD_POWER_SAVE
#define	DEMOD_CMD_RESTART
#define	DEMOD_CMD_SET_REPEAT
#define	DEMOD_CMD_GET_PART_INFO
/* common */
#define	DEMOD_CMD_SET_TUNE
#define	DEMOD_CMD_STATUS
#define	DEMOD_CMD_TSCLK_STATUS
#define	DEMOD_CMD_SOFT_RESET
#define	DEMOD_CMD_SET_SELF_RESET_PARAM
#define	DEMOD_CMD_LOCKTIME
/* standard status */
#define	DEMOD_CMD_VSB_STATUS
#define	DEMOD_CMD_QAM_STATUS
#define	DEMOD_CMD_ATSC3_STATUS
#define	DEMOD_CMD_DVBS_STATUS
#define	DEMOD_CMD_DVBS2_STATUS
#define	DEMOD_CMD_DVBT_STATUS
#define	DEMOD_CMD_DVBT2_STATUS
#define	DEMOD_CMD_DVBC_STATUS
#define	DEMOD_CMD_DVBC2_STATUS
#define	DEMOD_CMD_ISDBT_STATUS
#define	DEMOD_CMD_DTMB_STATUS
/* feature control & status - ATSC */
#define	DEMOD_CMD_ATSC3_PLP_ID
#define	DEMOD_CMD_ATSC3_PLP_SELECT
#define	DEMOD_CMD_ATSC3_PLP_COMMON
#define	DEMOD_CMD_ATSC3_PLP_INFO
#define	DEMOD_CMD_ATSC3_SET_BASEADDR_AXI
/* feature control & status - DVB */
#define	DEMOD_CMD_SET_DVB_BASEADDR_AXI
#define	DEMOD_CMD_DVBS_SYM_RATE
#define	DEMOD_CMD_DVBS_OPERATING_MODE
#define	DEMOD_CMD_GET_SIGSRCH_NUM
#define	DEMOD_CMD_GET_SIGSRCH_INFO
#define	DEMOD_CMD_BLIND_STATUS
#define	DEMOD_CMD_BLIND_INIT
#define	DEMOD_CMD_BLIND_FOUNDINFO
#define	DEMOD_CMD_BLIND_END
#define	DEMOD_CMD_DVBT2_PLP_SELECT
#define	DEMOD_CMD_GET_DVBT2_PLP_ID
#define	DEMOD_CMD_SET_DVBT2_BASEADDR_AXI
#define	DEMOD_CMD_DVBC_SRD
#define	DEMOD_CMD_DVBC2_STARTFREQUENCY
#define	DEMOD_CMD_DVBC2_PLP_SELECT
#define	DEMOD_CMD_SET_ISDBT_BASEADDR_AXI
#define	DEMOD_CMD_ISDBT_TMCC_INFO
#define	DEMOD_CMD_SET_DTMB_BASEADDR_AXI
/* special control & status */
#define	DEMOD_CMD_DISEQC_SEND
#define	DEMOD_CMD_DISEQC_STATUS

/* DEMOD command code */
typedef enum {
	DEMOD_CMD_GET_REG_CODE					= 0x03,
	DEMOD_CMD_SET_REG_CODE					= 0x04,
	DEMOD_CMD_GET_PROP_CODE					= 0x28,
	DEMOD_CMD_SET_PROP_CODE					= 0x29,
	DEMOD_CMD_POWER_SAVE_CODE				= 0x39,
	DEMOD_CMD_RESTART_CODE					= 0x3A,
	DEMOD_CMD_SET_REPEAT_CODE				= 0x93,
	DEMOD_CMD_GET_PART_INFO_CODE			= 0x32,
	DEMOD_CMD_SET_TUNE_CODE					= 0x3D,
	DEMOD_CMD_STATUS_CODE					= 0x2A,
	DEMOD_CMD_TSCLK_STATUS_CODE				= 0x53,
	DEMOD_CMD_SOFT_RESET_CODE				= 0x11,
	DEMOD_CMD_SET_SELF_RESET_PARAM_CODE		= 0x2B,
	DEMOD_CMD_LOCKTIME_CODE					= 0x3E,
	DEMOD_CMD_VSB_STATUS_CODE				= 0x1A,
	DEMOD_CMD_QAM_STATUS_CODE				= 0x33,
	DEMOD_CMD_ATSC3_STATUS_CODE				= 0x36,
	DEMOD_CMD_DVBS_STATUS_CODE				= 0x15,
	DEMOD_CMD_DVBS2_STATUS_CODE				= 0x16,
	DEMOD_CMD_DVBT_STATUS_CODE				= 0x17,
	DEMOD_CMD_DVBT2_STATUS_CODE				= 0x18,
	DEMOD_CMD_DVBC_STATUS_CODE				= 0x1C,
	DEMOD_CMD_DVBC2_STATUS_CODE				= 0x1D,
	DEMOD_CMD_ISDBT_STATUS_CODE				= 0x1B,
	DEMOD_CMD_DTMB_STATUS_CODE				= 0x43,
	DEMOD_CMD_ATSC3_PLP_ID_CODE				= 0x61,
	DEMOD_CMD_ATSC3_PLP_SELECT_CODE			= 0x62,
	DEMOD_CMD_ATSC3_PLP_COMMON_CODE			= 0x63,
	DEMOD_CMD_ATSC3_PLP_INFO_CODE			= 0x64,
	DEMOD_CMD_ATSC3_SET_BASEADDR_AXI_CODE	= 0x65,
	DEMOD_CMD_SET_DVB_BASEADDR_AXI_CODE		= 0x52,
	DEMOD_CMD_DVBS_SYM_RATE_CODE			= 0x31,
	DEMOD_CMD_DVBS_OPERATING_MODE_CODE		= 0x14,
	DEMOD_CMD_GET_SIGSRCH_NUM_CODE			= 0x45,
	DEMOD_CMD_GET_SIGSRCH_INFO_CODE			= 0x42,
	DEMOD_CMD_BLIND_STATUS_CODE				= 0x46,
	DEMOD_CMD_BLIND_INIT_CODE				= 0x47,
	DEMOD_CMD_BLIND_FOUNDINFO_CODE			= 0x48,
	DEMOD_CMD_BLIND_END_CODE				= 0x49,
	DEMOD_CMD_DVBT2_PLP_SELECT_CODE			= 0x1F,
	DEMOD_CMD_GET_DVBT2_PLP_ID_CODE			= 0x44,
	DEMOD_CMD_SET_DVBT2_BASEADDR_AXI_CODE	= 0x50,
	DEMOD_CMD_DVBC_SRD_CODE					= 0x23,
	DEMOD_CMD_DVBC2_STARTFREQUENCY_CODE		= 0x1E,
	DEMOD_CMD_DVBC2_PLP_SELECT_CODE			= 0x20,
	DEMOD_CMD_SET_ISDBT_BASEADDR_AXI_CODE	= 0x40,
	DEMOD_CMD_ISDBT_TMCC_INFO_CODE			= 0x41,
	DEMOD_CMD_SET_DTMB_BASEADDR_AXI_CODE	= 0x51,
	DEMOD_CMD_DISEQC_SEND_CODE				= 0x13,
	DEMOD_CMD_DISEQC_STATUS_CODE			= 0x35
} DEMOD_CMD_CODE;

#ifdef	DEMOD_CMD_GET_REG
typedef struct
{ /* LX_DEMOD_CMD_GET_REG_struct */
	UINT8	addressMsb;
	UINT8	addressLsb;
	UINT8	length;
} LX_DEMOD_CMD_GET_REG_struct;

typedef struct
{ /* LX_DEMOD_CMD_GET_REG_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT32	data;
	UINT8	mData[64];
} LX_DEMOD_CMD_GET_REG_REPLY_struct;

#define	DEMOD_CMD_GET_REG_CHIP_ID_LSB									0
#define	DEMOD_CMD_GET_REG_CHIP_ID_MASK									0xff

#define	DEMOD_CMD_GET_REG_ADDRMSB_LSB									0
#define	DEMOD_CMD_GET_REG_ADDRMSB_MASK									0xff

#define	DEMOD_CMD_GET_REG_ADDRLSB_LSB									0
#define	DEMOD_CMD_GET_REG_ADDRLSB_MASK									0xff

#define	DEMOD_CMD_GET_REG_LENGTH_LSB									0
#define	DEMOD_CMD_GET_REG_LENGTH_MASK									0xff

#endif /* DEMOD_CMD_GET_REG */

#ifdef	DEMOD_CMD_SET_REG
typedef	struct
{ /* LX_DEMOD_CMD_SET_REG_struct */
	UINT8	addressMsb;
	UINT8	addressLsb;
	UINT8	length;
	UINT32	data;

} LX_DEMOD_CMD_SET_REG_struct;

typedef	struct
{ /* LX_DEMOD_CMD_SET_REG_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
} LX_DEMOD_CMD_SET_REG_REPLY_struct;

#define	DEMOD_CMD_SET_REG_CHIP_ID_LSB									0
#define	DEMOD_CMD_SET_REG_CHIP_ID_MASK									0xff

#define	DEMOD_CMD_SET_REG_ADDRMSB_LSB									0
#define	DEMOD_CMD_SET_REG_ADDRMSB_MASK									0xff

#define	DEMOD_CMD_SET_REG_ADDRLSB_LSB									0
#define	DEMOD_CMD_SET_REG_ADDRLSB_MASK									0xff

#define	DEMOD_CMD_SET_REG_LENGTH_LSB									0
#define	DEMOD_CMD_SET_REG_LENGTH_MASK									0xff

#endif /* DEMOD_CMD_SET_REG */


#ifdef	DEMOD_CMD_SET_REPEAT
typedef struct
{ /* LX_DEMOD_CMD_SET_REPEAT_struct	*/
	UINT8	repeatEn;
} LX_DEMOD_CMD_SET_REPEAT_struct;

typedef struct
{ /* LX_DEMOD_CMD_SET_REPEAT_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
} LX_DEMOD_CMD_SET_REPEAT_REPLY_struct;

#define	DEMOD_CMD_SET_REPEAT_LSB										0
#define	DEMOD_DD_GET_REPEAT_CMD_MASK									0x01
#define	DEMOD_DD_GET_REPEAT_CMD_ENABLE									0x01
#define	DEMOD_DD_GET_REPEAT_CMD_DISABLE									0x00

#endif /* DEMOD_CMD_SET_REPEAT */

#ifdef	DEMOD_CMD_POWER_SAVE
typedef	struct
{ /* LX_DEMOD_CMD_POWER_SAVE_struct */
	UINT8	power_save;
} LX_DEMOD_CMD_POWER_SAVE_struct;

typedef struct
{ /* LX_DEMOD_CMD_POWER_SAVE_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
} LX_DEMOD_CMD_POWER_SAVE_REPLY_struct;

#define	DEMOD_CMD_POWER_SAVE_LSB										0
#define	DEMOD_CMD_POWER_SAVE_MASK										0x1
#define	DEMOD_DD_POWER_SAVE_DISABLE										0
#define	DEMOD_DD_POWER_SAVE_ENABLE										1

#endif /* DEMOD_CMD_POWER_SAVE */


#ifdef	DEMOD_CMD_RESTART
typedef struct
{ /* LX_DEMOD_CMD_RESTART_struct */
	UINT8	nothing;
} LX_DEMOD_CMD_RESTART_struct;

typedef	struct
{ /* LX_DEMOD_CMD_RESTART_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
} LX_DEMOD_CMD_RESTART_REPLY_struct;

#endif /* DEMOD_CMD_RESTART */

#ifdef	DEMOD_CMD_GET_PROP
typedef struct
{ /* LX_DEMOD_CMD_GET_PROP_struct */
	UINT16	prop;
} LX_DEMOD_CMD_GET_PROP_struct;

typedef struct
{ /* LX_DEMOD_CMD_GET_PROP_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
	UINT32	data;
} LX_DEMOD_CMD_GET_PROP_REPLY_struct;

#define	DEMOD_CMD_GET_PROP_PROP_LSB										0
#define	DEMOD_CMD_GET_PROP_PROP_MASK									0xffffffff

#endif /* DEMOD_CMD_GET_PROP	*/

#ifdef	DEMOD_CMD_SET_PROP
typedef struct
{ /* LX_DEMOD_CMD_SET_PROP_struct */
	UINT16	prop;
	UINT32	data;
} LX_DEMOD_CMD_SET_PROP_struct;

typedef struct
{ /* LX_DEMOD_CMD_SET_PROP_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;

} LX_DEMOD_CMD_SET_PROP_REPLY_struct;

#define	DEMOD_CMD_SET_PROP_PROP_LSB										0
#define	DEMOD_CMD_SET_PROP_PROP_MASK									0xffff

#define	DEMOD_CMD_SET_PROP_DATA_LSB										0
#define	DEMOD_CMD_SET_PROP_DATA_MASK									0xffffffff
#endif /* DEMOD_CMD_SET_PROP	*/

#ifdef	DEMOD_CMD_GET_PART_INFO
typedef	struct
{ /* LX_DEMOD_CMD_GET_PART_INFO_struct */
	UINT8	nothing;
} LX_DEMOD_CMD_GET_PART_INFO_struct;

typedef struct
{ /* LX_DEMOD_CMD_GET_PART_INFO_REPLY_struct	*/
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
	UINT8	fw_major;
	UINT8	fw_minor;
	UINT8	fw_year;
	UINT8	fw_month;
	UINT8	fw_day;
	UINT8	chip_rev;
	UINT8	reserved;
} LX_DEMOD_CMD_GET_PART_INFO_REPLY_struct;

#define	DEMOD_DD_GET_PART_INFO_FW_MAJOR_LSB								0
#define	DEMOD_DD_GET_PART_INFO_FW_MAJOR_MASK							0xff
#define	DEMOD_DD_GET_PART_INFO_FW_MINOR_LSB								0
#define	DEMOD_DD_GET_PART_INFO_FW_MINOR_MASK							0xff
#define	DEMOD_DD_GET_PART_INFO_FW_YEAR_LSB								0
#define	DEMOD_DD_GET_PART_INFO_FW_YEAR_MASK								0xff
#define	DEMOD_DD_GET_PART_INFO_FW_MONTH_LSB								0
#define	DEMOD_DD_GET_PART_INFO_FW_MONTH_MASK							0xff
#define	DEMOD_DD_GET_PART_INFO_FW_DAY_LSB								0
#define	DEMOD_DD_GET_PART_INFO_FW_DAY_MASK								0xff
#define	DEMOD_DD_GET_PART_INFO_FW_CHIP_REV_LSB							0
#define	DEMOD_DD_GET_PART_INFO_FW_CHIP_REV_MASK							0xff
#define	DEMOD_DD_GET_PART_INFO_FW_RESERVED_LSB							0
#define	DEMOD_DD_GET_PART_INFO_FW_RESERVED_MASK							0xff

#endif/* DEMOD_CMD_GET_PART_INFO */

#ifdef	DEMOD_CMD_SET_TUNE
typedef	struct
{ /* LX_DEMOD_CMD_SET_TUNE_struct */
	UINT8	 nothing;
} LX_DEMOD_CMD_SET_TUNE_struct;

typedef struct
{ /* LX_DEMOD_CMD_SET_TUNE_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
} LX_DEMOD_CMD_SET_TUNE_REPLY_struct;
#endif/* DEMOD_CMD_SET_TUNE */

#ifdef	DEMOD_CMD_STATUS
typedef struct
{ /* LX_DEMOD_CMD_STATUS_struct */
	UINT8	nothing;
} LX_DEMOD_CMD_STATUS_struct;

typedef	struct
{ /* LX_DEMOD_CMD_STATUS_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT8	neverLock;
	UINT8	lock_fec;
	UINT8	reply_operMod;
} LX_DEMOD_CMD_STATUS_REPLY_struct;

#define	DEMOD_STATUS_NEVERLOCK_INIT									0
#define	DEMOD_STATUS_NEVERLOCK_PROCESSING							1
#define	DEMOD_STATUS_NEVERLOCK_LOCKED								2
#define	DEMOD_STATUS_NEVERLOCK_NO_LOCK								3

#define	DEMOD_DD_STATUS_RESPONSE_NEVERLOCK_LSB							4
#define	DEMOD_DD_STATUS_RESPONSE_NEVERLOCK_MASK							0x03
#define	DEMOD_DD_STATUS_RESPONSE_LOCK_FEC_LSB							0
#define	DEMOD_DD_STATUS_RESPONSE_LOCK_FEC_MASK							0x01

#define	DEMOD_DD_STATUS_RESPONSE_MODULATION_LSB							0
#define	DEMOD_DD_STATUS_RESPONSE_MODULATION_MASK						0xff

#endif /* DEMOD_CMD_STATUS */

#ifdef	DEMOD_CMD_TSCLK_STATUS
typedef struct
{ /* LX_DEMOD_CMD_TSCLK_STATUS_struct */
	UINT8	nothing;
} LX_DEMOD_CMD_TSCLK_STATUS_struct;

typedef	struct
{ /* LX_DEMOD_CMD_TSCLK_STATUS_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT32	tsClkRate;
} LX_DEMOD_CMD_TSCLK_STATUS_REPLY_struct;

#define	DEMOD_DD_TSCLK_STATUS_RESPONSE_TSCLKRATE_LSB					0
#define	DEMOD_DD_TSCLK_STATUS_RESPONSE_TSCLKRATE_MASK					0xffffffff
#define	DEMOD_DD_TSCLK_STATUS_RESPONSE_TSCLKRATE_UNKNOWN				0

#endif /* DEMOD_CMD_TSCLK_STATUS */

#ifdef	DEMOD_CMD_VSB_STATUS
typedef	struct
{ /* LX_DEMOD_CMD_VSB_STATUS_struct */
	UINT8	nothing;
} LX_DEMOD_CMD_VSB_STATUS_struct;

typedef	struct
{ /* LX_DEMOD_CMD_VSB_STATUS_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT16	if_agc;
	UINT16	mse_info;
	UINT32	ber;
	UINT32	cfo;
	UINT32	sfo;
	UINT8	op_mode;
	UINT8	pe;
	UINT8	constellation;
	UINT8	spInv;
	UINT8	lock_carr;
	UINT8	lock_fec;
} LX_DEMOD_CMD_VSB_STATUS_REPLY_struct;

#define	DEMOD_DD_VSB_STATUS_RESPONSE_IF_AGC_LSB							0
#define	DEMOD_DD_VSB_STATUS_RESPONSE_IF_AGC_MASK						0xFFFF

#define	DEMOD_DD_VSB_STATUS_RESPONSE_MSE_INFO_LSB						0
#define	DEMOD_DD_VSB_STATUS_RESPONSE_MSE_INFO_MASK						0xFFFF

#define	DEMOD_DD_VSB_STATUS_RESPONSE_BER_LSB							0
#define	DEMOD_DD_VSB_STATUS_RESPONSE_BER_MASK							0x00FFFFFF

#define	DEMOD_DD_VSB_STATUS_RESPONSE_CFO_LSB							0
#define	DEMOD_DD_VSB_STATUS_RESPONSE_CFO_MASK							0x00FFFFFF

#define	DEMOD_DD_VSB_STATUS_RESPONSE_OP_MODE_LSB						0
#define	DEMOD_DD_VSB_STATUS_RESPONSE_OP_MODE_MASK						0xFF

#define	DEMOD_DD_VSB_STATUS_RESPONSE_PE_LSB								0
#define	DEMOD_DD_VSB_STATUS_RESPONSE_PE_MASK							0xFF

#define	DEMOD_DD_VSB_STATUS_RESPONSE_SPECINV_LSB						7
#define	DEMOD_DD_VSB_STATUS_RESPONSE_SPECINV_MASK						0x01

#define	DEMOD_DD_VSB_STATUS_RESPONSE_SFO_LSB							0
#define	DEMOD_DD_VSB_STATUS_RESPONSE_SFO_MASK							0x00FFFFFF

#define	DEMOD_DD_VSB_STATUS_RESPONSE_LOCK_CARR_LSB						1
#define	DEMOD_DD_VSB_STATUS_RESPONSE_LOCK_CARR_MASK						0x01

#define	DEMOD_DD_VSB_STATUS_RESPONSE_LOCK_FEC_LSB						0
#define	DEMOD_DD_VSB_STATUS_RESPONSE_LOCK_FEC_MASK						0x01

#endif /*DEMOD_DD_VSB_STATUS*/

#ifdef	DEMOD_CMD_QAM_STATUS
typedef	struct
{ /* LX_DEMOD_CMD_QAM_STATUS_struct */
	UINT8	nothing;
} LX_DEMOD_CMD_QAM_STATUS_struct;

typedef	struct
{/*LX_DEMOD_CMD_QAM_STATUS_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT16	if_agc;
	UINT16	mse_info;
	UINT32	ber;
	UINT32	cfo;
	UINT32	sfo;
	UINT8	op_mode;
	UINT8	pe;
	UINT8	constellation;
	UINT8	spInv;
	UINT8	lock_carr;
	UINT8	lock_fec;
	UINT16	sym_rate;
} LX_DEMOD_CMD_QAM_STATUS_REPLY_struct;

#define	DEMOD_DD_QAM_STATUS_RESPONSE_IF_AGC_LSB							0
#define	DEMOD_DD_QAM_STATUS_RESPONSE_IF_AGC_MASK						0xFFFF

#define	DEMOD_DD_QAM_STATUS_RESPONSE_MSE_INFO_LSB						0
#define	DEMOD_DD_QAM_STATUS_RESPONSE_MSE_INFO_MASK						0xFFFF

#define	DEMOD_DD_QAM_STATUS_RESPONSE_BER_LSB							0
#define	DEMOD_DD_QAM_STATUS_RESPONSE_BER_MASK							0x00FFFFFF

#define	DEMOD_DD_QAM_STATUS_RESPONSE_CFO_LSB							0
#define	DEMOD_DD_QAM_STATUS_RESPONSE_CFO_MASK							0x00FFFFFF

#define	DEMOD_DD_QAM_STATUS_RESPONSE_OP_MODE_LSB						0
#define	DEMOD_DD_QAM_STATUS_RESPONSE_OP_MODE_MASK						0xFF

#define	DEMOD_DD_QAM_STATUS_RESPONSE_PE_LSB								0
#define	DEMOD_DD_QAM_STATUS_RESPONSE_PE_MASK							0xFF

#define	DEMOD_DD_QAM_STATUS_RESPONSE_SPECINV_LSB						7
#define	DEMOD_DD_QAM_STATUS_RESPONSE_SPECINV_MASK						0x01

#define	DEMOD_DD_QAM_STATUS_RESPONSE_SYM_RATE_LSB						0
#define	DEMOD_DD_QAM_STATUS_RESPONSE_SYM_RATE_MASK						0xFFFF

#define	DEMOD_DD_QAM_STATUS_RESPONSE_CONSTELLATION_LSB					0
#define	DEMOD_DD_QAM_STATUS_RESPONSE_CONSTELLATION_MASK					0x0f

#define	DEMOD_DD_QAM_STATUS_RESPONSE_SFO_LSB							0
#define	DEMOD_DD_QAM_STATUS_RESPONSE_SFO_MASK							0x00FFFFFF

#define	DEMOD_DD_QAM_STATUS_RESPONSE_LOCK_CARR_LSB						1
#define	DEMOD_DD_QAM_STATUS_RESPONSE_LOCK_CARR_MASK						0x01

#define	DEMOD_DD_QAM_STATUS_RESPONSE_LOCK_FEC_LSB						0
#define	DEMOD_DD_QAM_STATUS_RESPONSE_LOCK_FEC_MASK						0x01
#endif /*DEMOD_CMD_QAM_STATUS*/


/* ATSC3 definitions */
#define	DEMOD_ATSC3_PLP_DEC_MAX									4

#define	DEMOD_ATSC3_STATUS_DONE_BS_DEC_DONE						1
#define	DEMOD_ATSC3_STATUS_DONE_BS_DEC_UNDONE					0

#define	DEMOD_ATSC3_STATUS_DONE_ACQ_DONE						1
#define	DEMOD_ATSC3_STATUS_DONE_ACQ_UNDONE						0

#define	DEMOD_ATSC3_STATUS_LOCK_L1B_LOCKED						1
#define	DEMOD_ATSC3_STATUS_LOCK_L1B_UNLOCKED					0

#define	DEMOD_ATSC3_STATUS_LOCK_L1D_LOCKED						1
#define	DEMOD_ATSC3_STATUS_LOCK_L1D_UNLOCKED					0

#define	DEMOD_ATSC3_STATUS_PLP_ERR_MSG_INIT						0x00
#define	DEMOD_ATSC3_STATUS_PLP_ERR_MSG_NO_ERROR					0x01
#define	DEMOD_ATSC3_STATUS_PLP_ERR_MSG_INVALID_TI_COMBINATION	0x02
#define	DEMOD_ATSC3_STATUS_PLP_ERR_MSG_EXCESS_TI_MEM_SIZE		0x03
#define	DEMOD_ATSC3_STATUS_PLP_ERR_MSG_PROCESSING				0x04

#define	DEMOD_ATSC3_STATUS_SPECINV_INVERTED						1
#define	DEMOD_ATSC3_STATUS_SPECINV_NORMAL						0

#define	DEMOD_ATSC3_STATUS_EN_FSTO_TRACK_ENABLE					1
#define	DEMOD_ATSC3_STATUS_EN_FSTO_TRACK_DISABLE				0

#define	DEMOD_ATSC3_STATUS_BANDWIDTH_6MHZ						0
#define	DEMOD_ATSC3_STATUS_BANDWIDTH_7MHZ						1
#define	DEMOD_ATSC3_STATUS_BANDWIDTH_8MHZ						2

#define	DEMOD_ATSC3_PLP_ID_PLP_ID_FLAG_NO_VALID					0
#define	DEMOD_ATSC3_PLP_ID_PLP_ID_FLAG_VALID					1

#define	DEMOD_ATSC3_PLP_ID_LLS_VALID_NO_VALID					0
#define	DEMOD_ATSC3_PLP_ID_LLS_VALID_VALID						1

#define	DEMOD_ATSC3_PLP_ID_LDM_MODE_EL							1
#define	DEMOD_ATSC3_PLP_ID_LDM_MODE_CL							0

#define	DEMOD_ATSC3_PLP_ID_TI_MODE_CTI							1
#define	DEMOD_ATSC3_PLP_ID_TI_MODE_NO_CTI						0

#define	DEMOD_ATSC3_PLP_INFO_SUBFRAME_FFT_SIZE_8K				0
#define	DEMOD_ATSC3_PLP_INFO_SUBFRAME_FFT_SIZE_16K				1
#define	DEMOD_ATSC3_PLP_INFO_SUBFRAME_FFT_SIZE_32K				2
#define	DEMOD_ATSC3_PLP_INFO_SUBFRAME_FFT_SIZE_RESERVED			3

#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_GI_1_192					1
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_GI_2_384					2
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_GI_3_512					3
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_GI_4_768					4
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_GI_5_1024					5
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_GI_6_1536					6
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_GI_7_2048					7
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_GI_8_2432					8
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_GI_9_3072					9
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_GI_10_3648					10
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_GI_11_4096					11
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_GI_12_4864					12

#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_3_2				0
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_3_4				1
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_4_2				2
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_4_4				3
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_6_2				4
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_6_4				5
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_8_2				6
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_8_4				7
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_12_2				8
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_12_4				9
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_16_2				10
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_16_4				11
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_24_2				12
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_24_4				13
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_32_2				14
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SCATT_PP_32_4				15

#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SBS_FIRST_NO_SBS			0
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SBS_FIRST_SBS				1

#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SBS_LAST_NO_SBS			0
#define	DEMOD_ATSC3_PLP_INFO_L1B_SUB_SBS_LAST_SBS				1

#define	DEMOD_ATSC3_PLP_INFO_PLP_TI_MODE_NO_TI_MODE				0
#define	DEMOD_ATSC3_PLP_INFO_PLP_TI_MODE_CTI_MODE				1
#define	DEMOD_ATSC3_PLP_INFO_PLP_TI_MODE_HTI_MODE				2
#define	DEMOD_ATSC3_PLP_INFO_PLP_TI_MODE_RESERVED				3

#define	DEMOD_ATSC3_PLP_INFO_PLP_FEC_TYPE_BCH_16K_LDPC			0
#define	DEMOD_ATSC3_PLP_INFO_PLP_FEC_TYPE_BCH_64K_LDPC			1
#define	DEMOD_ATSC3_PLP_INFO_PLP_FEC_TYPE_CRC_16K_LDPC			2
#define	DEMOD_ATSC3_PLP_INFO_PLP_FEC_TYPE_CRC_64K_LDPC			3
#define	DEMOD_ATSC3_PLP_INFO_PLP_FEC_TYPE_16K_LDPC				4
#define	DEMOD_ATSC3_PLP_INFO_PLP_FEC_TYPE_64K_LDPC				5
#define	DEMOD_ATSC3_PLP_INFO_PLP_FEC_TYPE_RESERVED				6

#define	DEMOD_ATSC3_PLP_INFO_PLP_MOD_QPSK						0
#define	DEMOD_ATSC3_PLP_INFO_PLP_MOD_16QAM_NUC					1
#define	DEMOD_ATSC3_PLP_INFO_PLP_MOD_64QAM_NUC					2
#define	DEMOD_ATSC3_PLP_INFO_PLP_MOD_256QAM_NUC					3
#define	DEMOD_ATSC3_PLP_INFO_PLP_MOD_1024QAM_NUC				4
#define	DEMOD_ATSC3_PLP_INFO_PLP_MOD_4096QAM_NUC				5

#define	DEMOD_ATSC3_PLP_INFO_L1D_PLP_CTI_DEPTH_512				0
#define	DEMOD_ATSC3_PLP_INFO_L1D_PLP_CTI_DEPTH_724				1
#define	DEMOD_ATSC3_PLP_INFO_L1D_PLP_CTI_DEPTH_887_1254			2
#define	DEMOD_ATSC3_PLP_INFO_L1D_PLP_CTI_DEPTH_1024_1448		3
#define	DEMOD_ATSC3_PLP_INFO_L1D_PLP_CTI_DEPTH_RESERVED1		4
#define	DEMOD_ATSC3_PLP_INFO_L1D_PLP_CTI_DEPTH_RESERVED2		5
#define	DEMOD_ATSC3_PLP_INFO_L1D_PLP_CTI_DEPTH_RESERVED3		6
#define	DEMOD_ATSC3_PLP_INFO_L1D_PLP_CTI_DEPTH_RESERVED4		7

#ifdef	DEMOD_CMD_ATSC3_STATUS
/*
typedef	struct
{
} DEMOD_REQ_ATSC3_STATUS_struct;
*/

typedef struct __ATSC3_STATUS_CMD_RES_T{
	struct {
		UINT32	if_agc:16;
		UINT32	spInv:1;
		UINT32	bs_system_bw:2;
		UINT32	reply_operMod:6;
		UINT32	ti_eq:1;
		UINT32	num_plp_total:6;
	};	// word#0, left 0

	struct {
		UINT32	plp_exist:4;
		UINT32	fft_mode:4;
		UINT32	l1b_ldpc_iter:8;
		UINT32	l1d_ldpc_iter:8;
	};	// word#1, left 8

	struct {
		UINT32	demod_mse;
	};	// word#2, left 0

	struct {
		UINT32	eq_mse;
	};	// word#3, left 0

	struct {
		UINT32	sfo:24;
		UINT32	done_bs:2;
		UINT32	done_acq:2;
		UINT32	init_sts_done:2;
	};	// word#4, left 2;

	struct {
		UINT32	cfo:24;
		UINT32	l1b_scs:2;	// L1B success
		UINT32	l1b_ldpc_correct:2;
		UINT32	l1d_scs:2;	// L1D success
		UINT32	l1d_ldpc_correct:1;
	};	// word#5, left 1

	struct {
		UINT32	plp_ldpc_correct:2;
		UINT32	plp_ldpc_iter:6;
		UINT32	plp_ldpc_err:16;
		UINT32	err_msg:8;
	};	// word#6, left 0

	struct {
		UINT8	plp_pkerr[4];
	};	// word#7, left 0
} DEMOD_RES_ATSC3_STATUS_struct;
#endif /*DEMOD_CMD_ATSC3_STATUS*/

#ifdef	DEMOD_CMD_ATSC3_PLP_ID
/*
typedef	struct
{
	// empty
} DEMOD_REQ_ATSC3_PLP_ID_struct;
*/

typedef	struct
{ /* DEMOD_RES_ATSC3_PLP_ID_struct */
	UINT64 plp_id_flag;
	UINT64 lls_valid;
	UINT64 ldm_mode;
	UINT64 ti_mode;
} DEMOD_RES_ATSC3_PLP_ID_struct;
#endif /* DEMOD_CMD_ATSC3_PLP_ID */

#ifdef	DEMOD_CMD_ATSC3_PLP_INFO
/*
typedef	struct
{
//	UINT8	plp_index;
} DEMOD_REQ_ATSC3_PLP_INFO_struct;
*/

typedef	struct __ATSC3_PLP_INFO_CMD_RES_T
{
	struct {
		UINT32	bs_pre_str:5;
		UINT32	bs_l1b_mode:3;
		UINT32	bs_sym:4;
		UINT32	bs_minor:3;
		UINT32	easinfo:2;
		UINT32	bsr:6;
		UINT32	m2n:5;
	};	// #0, used 28

	struct {
		UINT32	l1b_num_subframes:8;
		UINT32	l1b_pre_num_symbols:3;
		UINT32	l1b_num_ofdm_symbols:11;
		UINT32	l1b_sub_fft_size:3;
		UINT32	l1b_sub_gi:4;
		UINT32	l1b_reduce_carr:3;
	};	// #1, used 32

	struct {
		UINT32	l1b_sub_scatt_pp:5;
		UINT32	l1b_sub_scatt_pb:3;
		UINT32	l1b_sub_sbs_first:1;
		UINT32	l1b_sub_sbs_last:1;

		UINT32	l1d_mode:3;
		UINT32	l1d_ap_mode:2;
		UINT32	l1d_segment:5;

		UINT32	pre_str_mode:5;
		UINT32	frm_mod:1;
	};	// #2, used 26

	struct {
		UINT32	frame_length_info:32;
	};	// #3, used 32

	struct {
		UINT32	dec_en:1;		//  1/32 dec en (decoding enabled include auto detect)
		UINT32	out_en:1;		//  2/32 tp out enabled
		UINT32	id:6;			//  8/32

		UINT32	fec_type:4;		// 12/32
		UINT32	cr:4;			// 16/32

		UINT32	mod:3;			// 19/32
		UINT32	ti_mode:2;		// 21/32
		UINT32	layer:1;		// 22/32
		UINT32	type:1;			// 23/32

		union {
			struct {
				UINT32	depth:3;	//	9/16,  #1, left 7
				UINT32	start_row:11;//	11/16, #2, left 5
			} cti;
			struct {
				UINT32	inter_subframe:1;
				UINT32	num_ti_blocks:4;
				UINT32	num_fec_blocks_max:12;
				UINT32	cell_interleaver:1;
				//UINT32	hti_num_fec_blocks_0:12;
			} hti;
			struct {
				UINT32	injection_level:5;
			} ldm;
		};
	} plp[DEMOD_ATSC3_PLP_DEC_MAX];	// 3 * 4 = 12 bytes

	struct {
		struct {
			UINT32	sbs_last:1;
			UINT32	sbs_first:1;
			UINT32	sp_boost:3;
			UINT32	sp_pattern:5;
			UINT32	num_ofdm_symbols:11;
			UINT32	gi:4;
			UINT32	reduce_carr:3;
			UINT32	fft_size:2;
			// used 30
		};
		struct {
			UINT32	num_plp:6;
			UINT32	null_cells:13;
			UINT32	freq_ilv:1;
			UINT32	sub_mux:1;
			UINT32	miso:2;
			UINT32	mimo:1;
			UINT32	number:8;
			// used 32
		};
	} sbf[DEMOD_ATSC3_PLP_DEC_MAX];	// 8 * 4 = 32 bytes
} DEMOD_RES_ATSC3_PLP_INFO_struct;

#endif /* DEMOD_CMD_ATSC3_PLP_INFO */


#ifdef	DEMOD_CMD_ATSC3_PLP_SELECT
typedef union
{
	struct {
		UINT8	id:6;
		UINT8	pad:1;
		UINT8	dec_active_low:1;
	};
	UINT8	idval;
} LX_DEMOD_DD_ATSC3_PLP_INDEX_struct;

typedef	struct
{
	LX_DEMOD_DD_ATSC3_PLP_INDEX_struct	 plp_dec_idx[DEMOD_ATSC3_PLP_DEC_MAX];
} DEMOD_REQ_ATSC3_PLP_SELECT_struct;

typedef	struct
{
	UINT32	retc:8;
} DEMOD_RES_ATSC3_PLP_SELECT_struct;

// Multi PLP Decoding Error code
#define ERROR_CODE_INVALID_MPLP_COMBINATION_OF_NO_ERROR					0x00
#define ERROR_CODE_INVALID_MPLP_COMBINATION_OF_MULTI_FDM_CASE			0xF4
#define ERROR_CODE_INVALID_MPLP_COMBINATION_OF_MULTI_EL_CASE			0xF5
#define ERROR_CODE_INVALID_MPLP_COMBINATION_OF_LDM_MOD_FAULT_CASE		0xF6
#define ERROR_CODE_INVALID_MPLP_COMBINATION_OF_NON_HTI_CASE				0xF7
#define ERROR_CODE_INVALID_MPLP_COMBINATION_OF_HTI_MEM_OVER_CASE		0xF8
#define ERROR_CODE_INVALID_MPLP_COMBINATION_OF_EXCEED_4PLP_CASE			0xF9
#endif /*DEMOD_DD_ATSC3_PLP_SELECT*/

#ifdef	DEMOD_CMD_ATSC3_SET_BASEADDR_AXI
typedef	struct
{
	UINT32	baseAddr;
} DEMOD_CMD_ATSC3_SET_BASEADDR_AXI_struct;

typedef struct
{
	UINT32 retc:8;
} DEMOD_RES_ATSC3_SET_BASEADDR_AXI_struct;
#endif /*DEMOD_CMD_ATSC3_SET_BASEADDR_AXI*/

#ifdef	DEMOD_CMD_SOFT_RESET
typedef	struct
{ /* LX_DEMOD_CMD_SOFT_RESET_struct */
	UINT8	softrstb;
	UINT8	softrstsyncb;
	UINT8	softrsteq1b;
	UINT8	softrsteq2b;
	UINT8	softrstdiseqcb;
	UINT8	softrstfecb;
	UINT8	softrsttpifb;
} LX_DEMOD_CMD_SOFT_RESET_struct;

typedef	struct
{ /* LX_DEMOD_CMD_SOFT_RESET_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
} LX_DEMOD_CMD_SOFT_RESET_REPLY_struct;

#define	DEMOD_CMD_SOFT_RESET_SOFTRSTB_LSB							7
#define	DEMOD_CMD_SOFT_RESET_SOFTRSTB_MASK							0x01

#define	DEMOD_CMD_SOFT_RESET_SOFTRSTSYNCB_LSB						6
#define	DEMOD_CMD_SOFT_RESET_SOFTRSTSYNCB_MASK						0x01

#define	DEMOD_CMD_SOFT_RESET_SOFTRSTEQ1B_LSB							5
#define	DEMOD_CMD_SOFT_RESET_SOFTRSTEQ1B_MASK						0x01

#define	DEMOD_CMD_SOFT_RESET_SOFTRSTEQ2B_LSB							4
#define	DEMOD_CMD_SOFT_RESET_SOFTRSTEQ2B_MASK						0x01

#define	DEMOD_CMD_SOFT_RESET_SOFTRSTDISEQCB_LSB						3
#define	DEMOD_CMD_SOFT_RESET_SOFTRSTDISEQCB_MASK						0x01

#define	DEMOD_CMD_SOFT_RESET_SOFTRSTFECB_LSB							2
#define	DEMOD_CMD_SOFT_RESET_SOFTRSTFECB_MASK						0x01

#define	DEMOD_CMD_SOFT_RESET_SOFTRSTTPIFB_LSB						1
#define	DEMOD_CMD_SOFT_RESET_SOFTRSTTPIFB_MASK						0x01
#endif /*DEMOD_DD_SOFT_RESET*/

#ifdef	DEMOD_CMD_SET_SELF_RESET_PARAM
typedef	struct
{ /*LX_DEMOD_CMD_SELF_RESET_struct */
	UINT8	rst_arg;
	UINT16	rst_time1;
	UINT16	rst_time2;
	UINT16	rst_time3;
	UINT16	rst_time4;
	UINT8	rst_cnt;
	UINT16	plp0_thd;
	UINT16	plp1_thd;
	UINT16	plp2_thd;
	UINT16	plp3_thd;
} LX_DEMOD_CMD_SELF_RESET_struct;

typedef	struct
{ /* LX_DEMOD_CMD_SELF_RESET_REPLY_struct */
	//LX_DEMOD_L1_CommonReplayObj *	STATUS;
} LX_DEMOD_CMD_SELF_RESET_REPLY_struct;

#define	DEMOD_CMD_SELF_RESET_RST_TIME1_LSB								8
#define	DEMOD_CMD_SELF_RESET_RST_TIME1_MASK								0xFF00

#define	DEMOD_CMD_SELF_RESET_RST_TIME2_LSB								0
#define	DEMOD_CMD_SELF_RESET_RST_TIME2_MASK								0x00FF

#define	DEMOD_CMD_SELF_RESET_RST_ARG_LSB								0
#define	DEMOD_CMD_SELF_RESET_RST_ARG_MASK								0xFF
#endif /*DEMOD_CMD_SELF_RESET*/

#ifdef	DEMOD_CMD_SET_ISDBT_BASEADDR_AXI
typedef	struct
{/*LX_DEMOD_CMD_SET_ISDBT_BASEADDR_AXI_struct */
	UINT32	baseAddr;
} LX_DEMOD_CMD_SET_ISDBT_BASEADDR_AXI_struct;

typedef struct
{ /* LX_DEMOD_CMD_SET_ISDBT_BASEADDR_AXI_REPLY_struct */
	//LX_DEMOD_L1_CommonReplayObj *	STATUS;
} LX_DEMOD_CMD_SET_ISDBT_BASEADDR_AXI_REPLY_struct;

#define	DEMOD_CMD_SET_ISDBT_BASEADDR_AXI_BASEADDR_LSB					0
#define	DEMOD_CMD_SET_ISDBT_BASEADDR_AXI_BASEADDR_MASK					0xFFFFFFFF
#endif /*DEMOD_DD_ISDBT_BASEADDR_AXI*/

#ifdef	DEMOD_CMD_SET_DTMB_BASEADDR_AXI
typedef	struct
{/*LX_DEMOD_CMD_SET_DTMB_BASEADDR_AXI_struct */
	UINT32	baseAddr;
} LX_DEMOD_CMD_SET_DTMB_BASEADDR_AXI_struct;

typedef struct
{ /* LX_DEMOD_CMD_SET_DTMB_BASEADDR_AXI_REPLY_struct */
	//LX_DEMOD_L1_CommonReplayObj *	STATUS;
} LX_DEMOD_CMD_SET_DTMB_BASEADDR_AXI_REPLY_struct;

#define	DEMOD_CMD_SET_DTMB_BASEADDR_AXI_BASEADDR_LSB						0
#define	DEMOD_CMD_SET_DTMB_BASEADDR_AXI_BASEADDR_MASK					0xFFFFFFFF
#endif /*DEMOD_DD_DTMB_BASEADDR_AXI*/

#ifdef	DEMOD_CMD_DVBC_SRD
typedef	struct
{ /* LX_DEMOD_CMD_DVBC_SRD_struct */
	UINT8	auto_en;
	UINT16	sym_rate;
} LX_DEMOD_CMD_DVBC_SRD_struct;

typedef	struct
{ /* LX_DEMOD_CMD_DVBC_SRD_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
} LX_DEMOD_CMD_DVBC_SRD_REPLY_struct;

#define	DEMOD_CMD_DVBC_SRD_AUTO_EN_LSB								7
#define	DEMOD_CMD_DVBC_SRD_AUTO_EN_MASK								0x01
#define	DEMOD_CMD_DVBC_SRD_AUTO_EN_ENABLE							1
#define	DEMOD_CMD_DVBC_SRD_AUTO_EN_DISABLE							0
#define	DEMOD_CMD_DVBC_SRD_SYM_RATE1_SHIFT							8
#define	DEMOD_CMD_DVBC_SRD_SYM_RATE1_MASK							0xff00
#define	DEMOD_CMD_DVBC_SRD_SYM_RATE2_LSB								0
#define	DEMOD_CMD_DVBC_SRD_SYM_RATE2_MASK							0x00ff
#endif /*DEMOD_CMD_DVBC_SRD*/


#ifdef	DEMOD_CMD_DVBT2_PLP_SELECT
typedef	struct
{/* LX_DEMOD_CMD_DVBT2_PLP_SELECT_struct */
	UINT8	plp_id;
	UINT8	plp_id_sel_mode;		//0
} LX_DEMOD_CMD_DVBT2_PLP_SELECT_struct;

typedef struct
{ /* LX_DEMOD_CMD_DVBT2_PLP_SELECT_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
} LX_DEMOD_CMD_DVBT2_PLP_SELECT_REPLY_struct;

#define	DEMOD_CMD_DVBT2_PLP_SELECT_PLP_ID_LSB						0
#define	DEMOD_CMD_DVBT2_PLP_SELECT_PLP_ID_MASK						0xFF

#define	DEMOD_CMD_DVBT2_PLP_SELECT_PLP_ID_SEL_MODE_LSB				0
#define	DEMOD_CMD_DVBT2_PLP_SELECT_PLP_ID_SEL_MODE_MASK				0x01
#define	DEMOD_CMD_DVBT2_PLP_SELECT_PLP_ID_SEL_MODE_MIN				0
#define	DEMOD_CMD_DVBT2_PLP_SELECT_PLP_ID_SEL_MODE_MAX				1
#define	DEMOD_CMD_DVBT2_PLP_SELECT_PLP_ID_SEL_MODE_AUTO				0
#define	DEMOD_CMD_DVBT2_PLP_SELECT_PLP_ID_SEL_MODE_MANUAL			1
#endif /*DEMOD_DD_DVBT2_PLP_SELECT*/


#ifdef	DEMOD_CMD_DVBC2_STARTFREQUENCY
typedef	struct
{ /* LX_DEMOD_CMD_DVBC2_STARTFREQUENCY_struct */
	UINT32	freq;
} LX_DEMOD_CMD_DVBC2_STARTFREQUENCY_struct;

typedef	struct
{ /* LX_DEMOD_CMD_DVBC2_STARTFREQUENCY_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
} LX_DEMOD_CMD_DVBC2_STARTFREQUENCY_REPLY_struct;

#define	DEMOD_CMD_DVBC2_STARTFREQUENCY_FREQ_LSB						0
#define	DEMOD_CMD_DVBC2_STARTFREQUENCY_FREQ_MASK						0xFFFFFFFF
#endif /*DEMOD_DD_DVBC2_STARTFREQUENCY*/


#ifdef	DEMOD_CMD_DVBC2_PLP_SELECT
typedef	struct
{ /* LX_DEMOD_CMD_DVBC2_PLP_SELECT_struct */
	UINT8	plp_id_mode;	//1_0
	UINT8	plp_id;		//7_0
	UINT8	ds_id;			//7_0
} LX_DEMOD_CMD_DVBC2_PLP_SELECT_struct;

typedef	struct
{ /* LX_DEMOD_CMD_DVBC2_PLP_SELECT_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
} LX_DEMOD_CMD_DVBC2_PLP_SELECT_REPLY_struct;

#define	DEMOD_CMD_DVBC2_PLP_SELECT_PLP_ID_MODE_LSB					4
#define	DEMOD_CMD_DVBC2_PLP_SELECT_PLP_ID_MODE_MASK					0x30

#define	DEMOD_CMD_DVBC2_PLP_SELECT_PLP_ID_LSB						0
#define	DEMOD_CMD_DVBC2_PLP_SELECT_PLP_ID_MASK						0xFF

#define	DEMOD_CMD_DVBC2_PLP_SELECT_DS_ID_LSB							0
#define	DEMOD_CMD_DVBC2_PLP_SELECT_DS_ID_MASK						0xFF
#endif /*DEMOD_DD_DVBC2_PLP_SELECT*/


#ifdef	DEMOD_CMD_DVBS_SYM_RATE
typedef	struct
{ /* LX_DEMOD_CMD_DVBS_SYM_RATE_struct */
	UINT8	srd_en_s;
	UINT8	sym_rate_0;
	UINT8	sym_rate_1;
	UINT16	sym_rate;
} LX_DEMOD_CMD_DVBS_SYM_RATE_struct;

typedef	struct
{ /* LX_DEMOD_CMD_DVBS_SYM_RATE_REPLY_struct	*/
	//LX_DEMOD_L1_CommonReplayObj *	STATUS;
} LX_DEMOD_CMD_DVBS_SYM_RATE_REPLY_struct;

#define	DEMOD_CMD_DVBS_SYM_RATE_SRD_EN_S_LSB							7
#define	DEMOD_CMD_DVBS_SYM_RATE_SRD_EN_S_MASK						0x01

#define	DEMOD_CMD_DVBS_SYM_RATE_SRD_TRCENTERF_S4_LSB					0
#define	DEMOD_CMD_DVBS_SYM_RATE_SRD_TRCENTERF_S4_MASK				0x000000000000FF

#define	DEMOD_CMD_DVBS_SYM_RATE_SRD_TRCENTERF_S3_LSB					0
#define	DEMOD_CMD_DVBS_SYM_RATE_SRD_TRCENTERF_S3_MASK				0x0000000000FF00

#define	DEMOD_CMD_DVBS_SYM_RATE_SRD_TRCENTERF_S2_LSB					0
#define	DEMOD_CMD_DVBS_SYM_RATE_SRD_TRCENTERF_S2_MASK				0x00000000FF0000

#define	DEMOD_CMD_DVBS_SYM_RATE_SRD_TRCENTERF_S1_LSB					0
#define	DEMOD_CMD_DVBS_SYM_RATE_SRD_TRCENTERF_S1_MASK				0x000000FF000000

#define	DEMOD_CMD_DVBS_SYM_RATE_SRD_TRCENTERF_S0_LSB					0
#define	DEMOD_CMD_DVBS_SYM_RATE_SRD_TRCENTERF_S0_MASK				0x0000FF00000000
#endif /*DEMOD_DD_DVBS_SYM_RATE*/


#ifdef	DEMOD_CMD_DVBS_OPERATING_MODE
typedef	struct
{ /* LX_DEMOD_CMD_DVBS_OPERATING_MODE_struct	*/
	UINT8	opmSel;			//blind	scan mode
	UINT32	symbolRate;
	UINT32	tuneFreq_Khz;
} LX_DEMOD_CMD_DVBS_OPERATING_MODE_struct;

typedef	struct
{ /* LX_DEMOD_CMD_DVBS_OPERATING_MODE_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
}	LX_DEMOD_CMD_DVBS_OPERATING_MODE_REPLY_struct;

#define	DEMOD_CMD_DVBS_OPERATING_MODE_OPM_SEL_LSB					0
#define	DEMOD_CMD_DVBS_OPERATING_MODE_OPM_SEL_MASK					0x3
#define	DEMOD_CMD_DVBS_OPERATING_MODE_OPM_DEBUGGING_MODE				0
#define	DEMOD_CMD_DVBS_OPERATING_MODE_OPM_NORMAL_MODE				1
#define	DEMOD_CMD_DVBS_OPERATING_MODE_OPM_BLIND_LOCK_MODE			2
#define	DEMOD_CMD_DVBS_OPERATING_MODE_OPM_BLIND_SCAN_MODE			3

#define	DEMOD_CMD_DVBS_OPERATING_MODE_SYMBOL_RATE_LSB				0
#define	DEMOD_CMD_DVBS_OPERATING_MODE_SYMBOL_RATE_MASK				0xFF

#define	DEMOD_CMD_DVBS_OPERATING_MODE_TUN_FREQ3_LSB					0
#define	DEMOD_CMD_DVBS_OPERATING_MODE_TUNE_FREQ3_MASK				0xFF000000

#define	DEMOD_CMD_DVBS_OPERATING_MODE_TUN_FREQ2_LSB					0
#define	DEMOD_CMD_DVBS_OPERATING_MODE_TUNE_FREQ2_MASK				0x00FF0000

#define	DEMOD_CMD_DVBS_OPERATING_MODE_TUN_FREQ1_LSB					0
#define	DEMOD_CMD_DVBS_OPERATING_MODE_TUNE_FREQ1_MASK				0x0000FF00

#define	DEMOD_CMD_DVBS_OPERATING_MODE_TUN_FREQ0_LSB					0
#define	DEMOD_CMD_DVBS_OPERATING_MODE_TUNE_FREQ0_MASK				0x000000FF
#endif /*DEMOD_DD_DVBS_OPERATING_MODE*/


#ifdef	DEMOD_CMD_DISEQC_SEND
typedef	struct
{ /* LX_DEMOD_CMD_DISEQC_SEND_struct	*/
	UINT8	diseqc_en;
	UINT8	tone_burst;
	UINT8	cont_tone;
	UINT8	burst_sel;
	UINT8	msg_length;
	UINT8	diseqc_repeat;
	UINT8	send_framing;
	UINT8	send_address;
	UINT8	send_command;
	UINT8	send_data0;
	UINT8	send_data1;
	UINT8	send_data2;
} LX_DEMOD_CMD_DISEQC_SEND_struct;

typedef	struct
{ /* DEMOD_CMD_DISEQC_SEND_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
} LX_DEMOD_CMD_DISEQC_SEND_REPLY_struct;


#define	DEMOD_CMD_DISEQC_SEND_DISEQC_EN_LSB							7
#define	DEMOD_CMD_DISEQC_SEND_DISEQC_EN_MASK							0x01
#define	DEMOD_CMD_DISEQC_SEND_DISEQC_ENABLE							0x01
#define	DEMOD_CMD_DISEQC_SEND_DISEQC_DISABLE							0x00

#define	DEMOD_CMD_DISEQC_SEND_TONE_BURST_LSB							6
#define	DEMOD_CMD_DISEQC_SEND_TONE_BURST_MASK						0x01
#define	DEMOD_CMD_DISEQC_SEND_TONE_BURST_ENABLE						0x01
#define	DEMOD_CMD_DISEQC_SEND_TONE_BURST_DISABLE						0x00

#define	DEMOD_CMD_DISEQC_SEND_CONT_TONE_LSB							5
#define	DEMOD_CMD_DISEQC_SEND_CONT_TONE_MASK							0x01
#define	DEMOD_CMD_DISEQC_SEND_CONT_TONE_ENABLE						0x01
#define	DEMOD_CMD_DISEQC_SEND_CONT_TONE_DISABLE						0x00

#define	DEMOD_CMD_DISEQC_SEND_BURST_SEL_LSB							4
#define	DEMOD_CMD_DISEQC_SEND_BURST_SEL_MASK							0x01
#define	DEMOD_CMD_DISEQC_SEND_BURST_SEL_MODULATED					0x01 //B
#define	DEMOD_CMD_DISEQC_SEND_BURST_SEL_UNMODUALTED					0x00 //A


#define	DEMOD_CMD_DISEQC_SEND_MSG_LENGTH_LSB							0
#define	DEMOD_CMD_DISEQC_SEND_MSG_LENGTH_MASK						0x0F

#define	DEMOD_CMD_DISEQC_SEND_SEND_FRAMING_LSB						0
#define	DEMOD_CMD_DISEQC_SEND_SEND_FRAMING_MASK						0xFF

#define	DEMOD_CMD_DISEQC_SEND_SEND_ADDRESS_LSB						0
#define	DEMOD_CMD_DISEQC_SEND_SEND_ADDRESS_MASK						0xFF

#define	DEMOD_CMD_DISEQC_SEND_SEND_COMMAND_LSB						0
#define	DEMOD_CMD_DISEQC_SEND_SEND_COMMAND_MASK						0xFF

#define	DEMOD_CMD_DISEQC_SEND_SEND_DATA0_LSB							0
#define	DEMOD_CMD_DISEQC_SEND_SEND_DATA0_MASK						0xFF

#define	DEMOD_CMD_DISEQC_SEND_SEND_DATA1_LSB							0
#define	DEMOD_CMD_DISEQC_SEND_SEND_DATA1_MASK						0xFF

#define	DEMOD_CMD_DISEQC_SEND_SEND_DATA2_LSB							0
#define	DEMOD_CMD_DISEQC_SEND_SEND_DATA2_MASK						0xFF
#endif /*DEMOD_DD_DISEQC_SEND*/


#ifdef	DEMOD_CMD_ISDBT_STATUS
typedef	struct
{ /* LX_DEMOD_CMD_ISDBT_STATUS_struct */
} LX_DEMOD_CMD_ISDBT_STATUS_struct;

typedef	struct
{ /* LX_DEMOD_CMD_ISDBT_STATUS_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT16	if_agc;
	UINT16	mse_info;
	UINT16	mse_info_demod; // 171123 swkim
	UINT32	ber;
	UINT32	cfo;
	UINT32	sfo;
	UINT8	op_mode;
	UINT8	pe;
	UINT8	spInv;
	UINT8	lock_carr;
	UINT8	lock_fec;

} LX_DEMOD_CMD_ISDBT_STATUS_REPLY_struct;

#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_IF_AGC_LSB						0
#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_IF_AGC_MASK						0xFFFF

#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_MSE_INFO_LSB						0
#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_MSE_INFO_MASK					0xFFFF

#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_BER_LSB							0
#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_BER_MASK							0x00FFFFFF

#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_CFO_LSB							0
#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_CFO_MASK							0x00FFFFFF

#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_OP_MODE_LSB						0
#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_OP_MODE_MASK						0xFF

#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_PE_LSB							0
#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_PE_MASK							0xFF

#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_SPECINV_LSB						7
#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_SPECINV_MASK						0x01

#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_SFO_LSB							0
#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_SFO_MASK							0x00FFFFFF

#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_LOCK_CARR_LSB					1
#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_LOCK_CARR_MASK					0x01

#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_LOCK_FEC_LSB						0
#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_LOCK_FEC_MASK					0x01

#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_MSE_INFO_DEMOD_LSB				0
#define	DEMOD_DD_ISDBT_STATUS_RESPONSE_MSE_INFO_DEMOD_MASK				0xFFFF // 200707 swkim
#endif /*DEMOD_CMD_ISDBT_STATUS*/


#ifdef	DEMOD_CMD_ISDBT_TMCC_INFO
typedef	struct
{ /* LX_DEMOD_CMD_ISDBT_TMCC_INFO_struct */
} LX_DEMOD_CMD_ISDBT_TMCC_INFO_struct;

typedef	struct
{ /* LX_DEMOD_CMD_ISDBT_TMCC_INFO_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT8	oqama;
	UINT8	ocra;
	UINT8	oila;
	UINT8	onsega;
	UINT8	oqamb;
	UINT8	ocrb;
	UINT8	oilb;
	UINT8	onsegb;
	UINT8	oqamc;
	UINT8	ocrc;
	UINT8	oilc;
	UINT8	onsegc;
	UINT8	fft_mode;
	UINT8	gi;

} LX_DEMOD_CMD_ISDBT_TMCC_INFO_REPLY_struct;

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_FFT_MODE_LSB					4
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_FFT_MODE_MASK					0x07

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_GI_LSB						0
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_GI_MASK						0x07
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_GI_1_32						0
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_GI_1_16						1
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_GI_1_8						2
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_GI_1_4						3
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_GI_1_128						4
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_GI_19_128						5
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_GI_19_256						6
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_GI_1_64						7

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OQAMA_LSB						4
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OQAMA_MASK					0x0F

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OCRA_LSB						0
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OCRA_MASK						0x07

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OILA_LSB						4
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OILA_MASK						0x0F

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_ONSEGA_LSB					0
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_ONSEGA_MASK					0x0F

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OQAMB_LSB						4
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OQAMB_MASK					0x0F

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OCRB_LSB						0
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OCRB_MASK						0x07

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OILB_LSB						4
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OILB_MASK						0x0F

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_ONSEGB_LSB					0
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_ONSEGB_MASK					0x0F

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OQAMC_LSB						4
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OQAMC_MASK					0x0F

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OCRC_LSB						0
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OCRC_MASK						0x07

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OILC_LSB						4
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_OILC_MASK						0x0F

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_ONSEGC_LSB					0
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_ONSEGC_MASK					0x0F

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_RESERVED0					0
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_1							1
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_2							2
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_3							3
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_4							4
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_5							5
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_6							6
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_7							7
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_8							8
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_9							9
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_10						10
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_11						11
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_12						12
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_13						13
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_RESERVED1					14
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_SEG_RESERVED2					15

#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_IT_0_0_0						0
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_IT_4_2_1						1
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_IT_8_4_2						2
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_IT_16_8_4						3
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_IT_RESERVED0					4
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_IT_RESERVED1					5
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_IT_RESERVED2					6
#define	DEMOD_DD_ISDBT_TMCC_INFO_RESPONSE_IT_RESERVED3					7
#endif /*DEMOD_CMD_ISDBT_TMCC_INFO*/


#ifdef	DEMOD_CMD_DVBC_STATUS
typedef	struct
{ /* LX_DEMOD_CMD_DVBC_STATUS_struct	*/
	UINT8	nothing;
} LX_DEMOD_CMD_DVBC_STATUS_struct;

typedef	struct
{ /* LX_DEMOD_CMD_DVBC_STATUS_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT16	if_agc;
	UINT16	mse_info;
	UINT32	ber;
	UINT32	cfo;
	UINT32	sfo;
	UINT8	op_mode;
	UINT8	pe;
	UINT8	constellation;
	UINT8	cr;
	UINT8	spInv;
	UINT8	lock_carr;
	UINT8	lock_fec;
	UINT16	sym_rate;
} LX_DEMOD_CMD_DVBC_STATUS_REPLY_struct;

#define	DEMOD_DD_DVBC_STATUS_RESPONSE_IF_AGC_LSB						0
#define	DEMOD_DD_DVBC_STATUS_RESPONSE_IF_AGC_MASK						0xFFFF

#define	DEMOD_DD_DVBC_STATUS_RESPONSE_MSE_INFO_LSB						0
#define	DEMOD_DD_DVBC_STATUS_RESPONSE_MSE_INFO_MASK						0xFFFF

#define	DEMOD_DD_DVBC_STATUS_RESPONSE_BER_LSB							0
#define	DEMOD_DD_DVBC_STATUS_RESPONSE_BER_MASK							0x00FFFFFF

#define	DEMOD_DD_DVBC_STATUS_RESPONSE_CFO_LSB							0
#define	DEMOD_DD_DVBC_STATUS_RESPONSE_CFO_MASK							0x00FFFFFF

#define	DEMOD_DD_DVBC_STATUS_RESPONSE_OP_MODE_LSB						0
#define	DEMOD_DD_DVBC_STATUS_RESPONSE_OP_MODE_MASK						0xFF

#define	DEMOD_DD_DVBC_STATUS_RESPONSE_PE_LSB							0
#define	DEMOD_DD_DVBC_STATUS_RESPONSE_PE_MASK							0xFF

#define	DEMOD_DD_DVBC_STATUS_RESPONSE_SPECINV_LSB						7
#define	DEMOD_DD_DVBC_STATUS_RESPONSE_SPECINV_MASK						0x01

#define	DEMOD_DD_DVBC_STATUS_RESPONSE_SYM_RATE_LSB						0
#define	DEMOD_DD_DVBC_STATUS_RESPONSE_SYM_RATE_MASK						0xFFFF

#define	DEMOD_DD_DVBC_STATUS_RESPONSE_CONSTELLATION_LSB					0
#define	DEMOD_DD_DVBC_STATUS_RESPONSE_CONSTELLATION_MASK				0x0f

#define	DEMOD_DD_DVBC_STATUS_RESPONSE_SFO_LSB							0
#define	DEMOD_DD_DVBC_STATUS_RESPONSE_SFO_MASK							0x00FFFFFF

#define	DEMOD_DD_DVBC_STATUS_RESPONSE_LOCK_CARR_LSB						1
#define	DEMOD_DD_DVBC_STATUS_RESPONSE_LOCK_CARR_MASK					0x01

#define	DEMOD_DD_DVBC_STATUS_RESPONSE_LOCK_FEC_LSB						0
#define	DEMOD_DD_DVBC_STATUS_RESPONSE_LOCK_FEC_MASK						0x01

#endif /*DEMOD_CMD_DVBC_STATUS*/


#ifdef	DEMOD_CMD_DVBT_STATUS
typedef	struct
{ /* LX_DEMOD_CMD_DVBT_STATUS_struct	*/
	UINT8	nothing;
} LX_DEMOD_CMD_DVBT_STATUS_struct;

typedef	struct
{ /* LX_DEMOD_CMD_DVBT_STATUS_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT16	if_agc;
	UINT16	mse_info;
	UINT16	mse_info_demod; // 171123 swkim
	UINT32	ber;
	UINT32	cfo;
	UINT32	sfo;
	UINT8	op_mode;
	UINT8	pe;
	UINT8	constellation;
	UINT8	spInv;
	UINT8	fft_mode;	// 2_0
	UINT16	cell_id;
	UINT8	lock_carr;
	UINT8	lock_fec;

	UINT8	gi; //2_0
	UINT8	hierarchy; // 2_0
	UINT8	hierarchy_sel; //	0

	UINT8	hp_cr; //2_0
	UINT8	lp_cr; //2_0
	UINT8	cellId;

	UINT8	tps_length; //5_0

	UINT8	pe_1st;
	UINT8	pe_2nd;
} LX_DEMOD_CMD_DVBT_STATUS_REPLY_struct;

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_IF_AGC_LSB						0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_IF_AGC_MASK						0xFFFF

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_MSE_INFO_LSB						0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_MSE_INFO_MASK						0xFFFF

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_BER_LSB							0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_BER_MASK							0x00FFFFFF

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_CFO_LSB							0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_CFO_MASK							0x00FFFFFF

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_OP_MODE_LSB						0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_OP_MODE_MASK						0xFF

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_PE_LSB							0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_PE_MASK							0xFF

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_SPECINV_LSB						7
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_SPECINV_MASK						0x01

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_FFT_MODE_LSB						4
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_FFT_MODE_MASK						0x07

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_GI_LSB							0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_GI_MASK							0x07
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_GI_1_32							0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_GI_1_16							1
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_GI_1_8							2
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_GI_1_4							3
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_GI_1_128							4
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_GI_19_128							5
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_GI_19_256							6
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_GI_1_64							7

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_TPS_LENGTH_LSB					0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_TPS_LENGTH_MASK					0xFF

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_CELL_ID_LSB						0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_CELL_ID_MASK						0xFFFF

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_HIERARCHY_LSB						5
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_HIERARCHY_MASK					0x07
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_HIERARCHY_ALFA1					1
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_HIERARCHY_ALFA2					2
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_HIERARCHY_ALFA4					3
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_HIERARCHY_NONE					0

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_LP_CR_LSB							0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_LP_CR_MASK						0x07

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_HP_CR_LSB							3
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_HP_CR_MASK						0x07

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_CONSTELLATION_LSB					0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_CONSTELLATION_MASK				0x0f

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_HIERARCHY_SEL_LSB					7
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_HIERARCHY_SEL_MASK				0x01
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_HIERARCHY_SEL_HP					1
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_HIERARCHY_SEL_LP					0

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_SFO_LSB							0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_SFO_MASK							0x00FFFFFF

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_LOCK_CARR_LSB						1
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_LOCK_CARR_MASK					0x01

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_LOCK_FEC_LSB						0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_LOCK_FEC_MASK						0x01

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_MSE_INFO_DEMOD_LSB				0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_MSE_INFO_DEMOD_MASK				0xFFFF

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_PE_1ST_LSB						0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_PE_1ST_MASK						0xFF

#define	DEMOD_DD_DVBT_STATUS_RESPONSE_PE_2ND_LSB						0
#define	DEMOD_DD_DVBT_STATUS_RESPONSE_PE_2ND_MASK						0xFF
#endif /*DEMOD_CMD_DVBT_STATUS*/


#ifdef	DEMOD_CMD_DVBT2_STATUS
typedef	struct
{ /* LX_DEMOD_CMD_DVBT2_STATUS_struct */
	UINT8	nothing;
} LX_DEMOD_CMD_DVBT2_STATUS_struct;

typedef	struct
{ /* LX_DEMOD_CMD_DVBT2_STATUS_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT16	if_agc;
	UINT16	mse_info;
	UINT16	mse_info_demod; // 171123 swkim
	UINT32	ber;
	UINT32	cfo;
	UINT8	op_mode;
	UINT8	pe;
	UINT8	constellation;
	UINT8	constellation_cm;
	UINT8	spInv;
	UINT8	lock_carr;
	UINT8	lock_fec;
	UINT8	cr;
	UINT8	cr_cm;
	UINT8	current_plp_id;	// 7_0
	UINT8	current_plp_id_cm;	// 7_0
	UINT8	bw_ext;			//0
	UINT8	fft_mode;			//3_0
	UINT8	gi;				//2_0
	UINT8	num_plp;			//7_0
	UINT8	num_dplp;			//7_0
	UINT8	tx_mode;			//2_0
	UINT8	icfo_lock;		//2_0
	UINT32	sfo;
	UINT16	cell_id;
} LX_DEMOD_CMD_DVBT2_STATUS_REPLY_struct;

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_IF_AGC_LSB						0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_IF_AGC_MASK						0xFFFF

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_MSE_INFO_LSB						0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_MSE_INFO_MASK					0xFFFF // 200707 swkim

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_BER_LSB							0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_BER_MASK							0xFFFFFF

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CFO_LSB							0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CFO_MASK							0xFFFFFF

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_OP_MODE_LSB						0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_OP_MODE_MASK						0xFF

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_PE_LSB							0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_PE_MASK							0xFF

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CONSTELLATION_LSB				4
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CONSTELLATION_MASK				0x07

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CONSTELLATION_CM_LSB				0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CONSTELLATION_CM_MASK			0x07

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_SPECINV_LSB						7
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_SPECINV_MASK						0x01

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CR_LSB							4
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CR_MASK							0x07

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CR_CM_LSB						0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CR_CM_MASK						0x07

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CURRENT_PLP_ID_LSB				0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CURRENT_PLP_ID_MASK				0xFF

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CURRENT_PLP_ID_CM_LSB			0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CURRENT_PLP_ID_CM_MASK			0xFF

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_BW_EXT_LSB						7
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_BW_EXT_MASK						0x01
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_BW_EXT_EXTENDED					1
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_BW_EXT_NORMAL					0

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_FFT_MODE_LSB						4
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_FFT_MODE_MASK					0x07

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_GI_LSB							0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_GI_MASK							0x07
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_GI_1_32							0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_GI_1_16							1
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_GI_1_8							2
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_GI_1_4							3
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_GI_1_128							4
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_GI_19_128						5
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_GI_19_256						6
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_GI_1_64							7

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_NUM_PLP_LSB						0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_NUM_PLP_MASK						0xFF

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_NUM_DPLP_LSB						0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_NUM_DPLP_MASK					0xFF

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_TX_MODE_LSB						7
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_TX_MODE_MASK						0x01
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_TX_MODE_MISO						1
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_TX_MODE_SISO						0

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_ICFO_LOCK_LSB					0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_ICFO_LOCK_MASK					0x01

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_SFO_LSB							0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_SFO_MASK							0xFFFFFF

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_LOCK_CARR_LSB					1
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_LOCK_CARR_MASK					0x01

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_LOCK_FEC_LSB						0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_LOCK_FEC_MASK					0x01

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_MSE_INFO_DEMOD_LSB				0
//#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_MSE_INFO_DEMOD_MASK				0x3FFF // delete 200707 swkim
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_MSE_INFO_DEMOD_MASK				0xFFFF // 200707 swkim

#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CELL_ID_LSB						0
#define	DEMOD_DD_DVBT2_STATUS_RESPONSE_CELL_ID_MASK						0xFFFF
#endif /*DEMOD_DD_DVBT2_STATUS*/

#ifdef	DEMOD_CMD_DVBS_STATUS
typedef	struct
{ /* LX_DEMOD_CMD_DVBS_STATUS_struct	*/
	UINT8	nothing;
} LX_DEMOD_CMD_DVBS_STATUS_struct;

typedef	struct
{ /* LX_DEMOD_CMD_DVBS_STATUS_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT16	if_agc;
	UINT16	mse_info;
	UINT32	ber;
	UINT32	cfo;
	UINT32	sfo;
	UINT8	op_mode;				//7_0
	UINT8	pe;					//7_0
	UINT8	constellation;		//1_0
	UINT8	spInv;		// 0
	UINT8	cr;
	UINT8	lock_carr;
	UINT8	lock_fec;
	UINT16	sym_rate;
} LX_DEMOD_CMD_DVBS_STATUS_REPLY_struct;

#define	DEMOD_DD_DVBS_STATUS_RESPONSE_IF_AGC_LSB						0
#define	DEMOD_DD_DVBS_STATUS_RESPONSE_IF_AGC_MASK						0xFFFF

#define	DEMOD_DD_DVBS_STATUS_RESPONSE_MSE_INFO_LSB						0
#define	DEMOD_DD_DVBS_STATUS_RESPONSE_MSE_INFO_MASK						0xFFFF

#define	DEMOD_DD_DVBS_STATUS_RESPONSE_BER_LSB							0
#define	DEMOD_DD_DVBS_STATUS_RESPONSE_BER_MASK							0x0000FFFF

#define	DEMOD_DD_DVBS_STATUS_RESPONSE_CFO_LSB							0
#define	DEMOD_DD_DVBS_STATUS_RESPONSE_CFO_MASK							0x00FFFFFF

#define	DEMOD_DD_DVBS_STATUS_RESPONSE_OP_MODE_LSB						0
#define	DEMOD_DD_DVBS_STATUS_RESPONSE_OP_MODE_MASK						0xFF

#define	DEMOD_DD_DVBS_STATUS_RESPONSE_PE_LSB							0
#define	DEMOD_DD_DVBS_STATUS_RESPONSE_PE_MASK							0xFF

#define	DEMOD_DD_DVBS_STATUS_RESPONSE_SPECINV_LSB						7
#define	DEMOD_DD_DVBS_STATUS_RESPONSE_SPECINV_MASK						0x01

#define	DEMOD_DD_DVBS_STATUS_RESPONSE_SYM_RATE_LSB						0
#define	DEMOD_DD_DVBS_STATUS_RESPONSE_SYM_RATE_MASK						0xFFFF

#define	DEMOD_DD_DVBS_STATUS_RESPONSE_CONSTELLATION_LSB					0
#define	DEMOD_DD_DVBS_STATUS_RESPONSE_CONSTELLATION_MASK				0x0F

#define	DEMOD_DD_DVBS_STATUS_RESPONSE_SFO_LSB							0
#define	DEMOD_DD_DVBS_STATUS_RESPONSE_SFO_MASK							0x00FFFFFF

#define	DEMOD_DD_DVBS_STATUS_RESPONSE_CR_LSB							0
#define	DEMOD_DD_DVBS_STATUS_RESPONSE_CR_MASK							0x0F

#define	DEMOD_DD_DVBS_STATUS_RESPONSE_LOCK_CARR_LSB						1
#define	DEMOD_DD_DVBS_STATUS_RESPONSE_LOCK_CARR_MASK					0x01

#define	DEMOD_DD_DVBS_STATUS_RESPONSE_LOCK_FEC_LSB						0
#define	DEMOD_DD_DVBS_STATUS_RESPONSE_LOCK_FEC_MASK						0x01

#endif /*DEMOD_CMD_DVBS_STATUS*/


#ifdef	DEMOD_CMD_DVBS2_STATUS
typedef	struct
{ /* LX_DEMOD_CMD_DVBS2_STATUS_struct */
	 UINT8	 nothing;
} LX_DEMOD_CMD_DVBS2_STATUS_struct;

typedef	struct
{ /* LX_DEMOD_CMD_DVBS2_STATUS_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT16	if_agc;
	UINT16	mse_info;
	UINT32	ber;
	UINT32	cfo;
	UINT32	sfo;
	UINT8	op_mode;				//7_0
	UINT8	pe;					//7_0
	UINT8	constellation;			//1_0
	UINT8	spInv;			// 0
	UINT8	pp;
	UINT8	cr;
	UINT8	lock_carr;
	UINT8	lock_fec;
	UINT16	sym_rate;
} LX_DEMOD_CMD_DVBS2_STATUS_REPLY_struct;


#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_IF_AGC_LSB						0
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_IF_AGC_MASK						0xFFFF

#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_MSE_INFO_LSB						0
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_MSE_INFO_MASK					0xFFFF

#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_BER_LSB							0
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_BER_MASK							0x0000FFFF

#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_CFO_LSB							0
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_CFO_MASK							0x00FFFFFF

#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_OP_MODE_LSB						0
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_OP_MODE_MASK						0xFF

#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_PE_LSB							0
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_PE_MASK							0xFF

#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_SPECINV_LSB						7
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_SPECINV_MASK						0x01

#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_SYM_RATE_LSB						0
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_SYM_RATE_MASK					0xFFFF

#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_CONSTELLATION_LSB				0
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_CONSTELLATION_MASK				0x0F

#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_SFO_LSB							0
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_SFO_MASK							0x00FFFFFF

#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_PP_LSB							7
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_PP_MASK							0x01
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_PP_PILOT							1
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_PP_NO_PILOT						0

#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_CR_LSB							0
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_CR_MASK							0x0F

#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_LOCK_CARR_LSB					1
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_LOCK_CARR_MASK					0x01

#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_LOCK_FEC_LSB						0
#define	DEMOD_DD_DVBS2_STATUS_RESPONSE_LOCK_FEC_MASK					0x01

#endif /*DEMOD_CMD_DVBS2_STATUS*/


#ifdef	DEMOD_CMD_DISEQC_STATUS
typedef struct
{ /* LX_DEMOD_CMD_DISEQC_STATUS_struct */
	UINT8	nothing;
} LX_DEMOD_CMD_DISEQC_STATUS_struct;

typedef	struct
{ /* LX_DEMOD_CMD_DISEQC_STATUS_REPLY_struct	*/
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT8	bus_state;
	UINT8	reply_status;
	UINT8	reply_length;
	UINT8	end_of_reply;
	UINT8	diseqc_mode;
	UINT8	reply_frame;
	UINT8	reply_byte1;
	UINT8	reply_byte2;
} LX_DEMOD_CMD_DISEQC_STATUS_REPLY_struct;

#define	DEMOD_CMD_DISEQC_STATUS_LISTEN_LSB							0
#define	DEMOD_CMD_DISEQC_STATUS_LISTEN_MASK							0x03
#define	DEMOD_CMD_DISEQC_STATUS_LISTEN_MIN							0
#define	DEMOD_CMD_DISEQC_STATUS_LISTEN_MAX							2
#define	DEMOD_CMD_DISEQC_STATUS_LISTEN_AUTO							0
#define	DEMOD_CMD_DISEQC_STATUS_LISTEN_LISTEN						1
#define	DEMOD_CMD_DISEQC_STATUS_LISTEN_NO_CHANGE						2

#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_BUS_STATE_LSB					0
#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_BUS_STATE_MASK					0x01
#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_BUS_STATE_BUSY					0
#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_BUS_STATE_READY					1

#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_REPLY_STATUS_LSB				1
#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_REPLY_STATUS_MASK				0x03
#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_REPLY_STATUS_MISSING_BITS		2
#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_REPLY_STATUS_NO_REPLY			0
#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_REPLY_STATUS_PARITY_ERROR		1
#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_REPLY_STATUS_REPLY_OK			3

#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_REPLY_LENGTH_LSB				3
#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_REPLY_LENGTH_MASK				0x03

#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_END_OF_REPLY_LSB				6
#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_END_OF_REPLY_MASK				0x01

#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_REPLY_FRAME_LSB					0
#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_REPLY_FRAME_MASK				0xff

#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_REPLY_BYTE1_LSB					0
#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_REPLY_BYTE1_MASK				0xff

#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_REPLY_BYTE2_LSB					0
#define	DEMOD_DD_DISEQC_STATUS_RESPONSE_REPLY_BYTE2_MASK				0xff
#endif /* DEMOD_CMD_DISEQC_STATUS */


#ifdef	DEMOD_CMD_DVBC2_STATUS
typedef	struct
{ /* LX_DEMOD_CMD_DVBC2_STATUS_struct */
	 UINT8	 nothing;

} LX_DEMOD_CMD_DVBC2_STATUS_struct;

typedef	struct
{/* LX_DEMOD_CMD_DVBC2_STATUS_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT16	if_agc;
	UINT16	mse_info;
	UINT16	ber;
	UINT32	cfo;
	UINT8	op_mode;
	UINT8	pe;
	UINT8	constellation;
	UINT8	spInv;
	UINT8	lock_tr;
	UINT8	lock_carr;
	UINT8	lock_psync;
	UINT8	lock_fec;
	UINT8	neverlock;
	UINT8	cr;
	UINT8	current_plp_id;
	UINT8	start_plp_id;
	UINT8	multi_plp_id;
} LX_DEMOD_CMD_DVBC2_STATUS_REPLY_struct;

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_IF_AGC_LSB						0
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_IF_AGC_MASK						0xFFFF

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_MSE_INFO_LSB						0
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_MSE_INFO_MASK					0xFFFF

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_BER_LSB							0
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_BER_MASK							0xFFFF

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_CFO_LSB							0
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_CFO_MASK							0xFFFFFFFF

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_OP_MODE_LSB						0
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_OP_MODE_MASK						0xFF

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_PE_LSB							0
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_PE_MASK							0xFF

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_LOCK_TR_LSB						0
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_LOCK_TR_MASK						0x01

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_LOCK_PSYNC_LSB					0
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_LOCK_PSYNC_MASK					0x01

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_CONSTELLATION_LSB				6
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_CONSTELLATION_MASK				0x03

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_SPECINV_LSB						5
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_SPECINV_MASK						0x01

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_CR_LSB							0
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_CR_MASK							0x07

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_NEVERLOCK_LSB					3
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_NEVERLOCK_MASK					0x01

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_CURRENT_PLP_ID_LSB				0
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_CURRENT_PLP_ID_MASK				0xFF

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_START_PLP_ID_LSB					0
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_START_PLP_ID_MASK				0xFF

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_MULTI_PLP_ID_LSB					0
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_MULTI_PLP_ID_MASK				0xFF

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_LOCK_CARR_LSB					1
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_LOCK_CARR_MASK					0x01

#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_LOCK_FEC_LSB						0
#define	DEMOD_DD_DVBC2_STATUS_RESPONSE_LOCK_FEC_MASK					0x01
#endif /*DEMOD_DD_DVBC2_STATUS*/


#ifdef	DEMOD_CMD_LOCKTIME
typedef	struct
{ /* LX_DEMOD_CMD_LOCKTIME_struct */
	UINT8	nothing;

} LX_DEMOD_CMD_LOCKTIME_struct;

typedef struct
{ /* LX_DEMOD_CMD_LOCKTIME_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
	UINT32	locktime1;
	UINT32	locktime2;
	UINT32	locktime3;
	UINT32	locktime4;
	UINT32	locktime5;
	UINT32	locktime6;
} LX_DEMOD_CMD_LOCKTIME_REPLY_struct;
#endif /*DEMOD_DD_LOCKTIME*/


#ifdef	DEMOD_CMD_GET_SIGSRCH_NUM
typedef	struct
{ /* LX_DEMOD_CMD_GET_SIGSRCH_NUM_struct */
	UINT8	nothing;

} LX_DEMOD_CMD_GET_SIGSRCH_NUM_struct;

typedef struct
{ /* LX_DEMOD_CMD_GET_SIGSRCH_NUM_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
	UINT16	ch_num;
} LX_DEMOD_CMD_GET_SIGSRCH_NUM_REPLY_struct;

#define	DEMOD_DD_GET_DD_SIGSRCH_NUM_RESPONSE_CH_NUM_LSB					0
#define	DEMOD_DD_GET_DD_SIGSRCH_NUM_RESPONSE_CH_NUM_MASK				0xFFFF
#endif /*DEMOD_DD_GET_DD_SIGSRCH_NUM*/


#ifdef	DEMOD_CMD_GET_SIGSRCH_INFO
typedef	struct
{ /* LX_DEMOD_CMD_GET_SIGSRCH_INFO_struct	*/
	UINT8	nothing;

} LX_DEMOD_CMD_GET_SIGSRCH_INFO_struct;

typedef struct
{ /* LX_DEMOD_CMD_GET_SIGSRCH_INFO_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
		UINT8	sigsrch_lock;
		UINT8	sigsrch_num;
		UINT32	center_idx;
		UINT32	bw_idx;

} LX_DEMOD_CMD_GET_SIGSRCH_INFO_REPLY_struct;

#define	DEMOD_DD_GET_DD_SIGSRCH_INFO_RESPONSE_SIGSRCH_LOCK_LSB			0
#define	DEMOD_DD_GET_DD_SIGSRCH_INFO_RESPONSE_SIGSRCH_LOCK_MASK			0xFF

#define	DEMOD_DD_GET_DD_SIGSRCH_INFO_RESPONSE_SIGSRCH_NUM_LSB			0
#define	DEMOD_DD_GET_DD_SIGSRCH_INFO_RESPONSE_SIGSRCH_NUM_MASK			0xFF

#define	DEMOD_DD_GET_DD_SIGSRCH_INFO_RESPONSE_CENTER_IDX_LSB			0
#define	DEMOD_DD_GET_DD_SIGSRCH_INFO_RESPONSE_CENTER_IDX_MASK			0xFFFFFFFF

#define	DEMOD_DD_GET_DD_SIGSRCH_INFO_RESPONSE_BW_IDX_LSB				0
#define	DEMOD_DD_GET_DD_SIGSRCH_INFO_RESPONSE_BW_IDX_MASK				0xFFFF
#endif /*DEMOD_DD_GET_DD_SIGSRCH_INFO*/


#ifdef	DEMOD_CMD_GET_DVBT2_PLP_ID
typedef	struct
{ /* LX_DEMOD_CMD_GET_DVBT2_PLP_ID_struct */
	UINT8	plp_index;

} LX_DEMOD_CMD_GET_DVBT2_PLP_ID_struct;

typedef	struct
{ /* LX_DEMOD_CMD_GET_DVBT2_PLP_ID_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj	* STATUS;
	UINT8	plp_id;	 //yunj
	UINT8	plp_conf;	//yunj
} LX_DEMOD_CMD_GET_DVBT2_PLP_ID_REPLY_struct;

#define	DEMOD_DD_GET_DVBT2_PLP_ID_RESPONSE_PLP_ID_LSB					0
#define	DEMOD_DD_GET_DVBT2_PLP_ID_RESPONSE_PLP_ID_MASK					0xff

#define	DEMOD_DD_GET_DVBT2_PLP_ID_RESPONSE_PLP_CONF_LSB					0
#define	DEMOD_DD_GET_DVBT2_PLP_ID_RESPONSE_PLP_CONF_MASK				0x07
#define	DEMOD_DD_GET_DVBT2_PLP_ID_RESPONSE_PLP_CONF_CPLP				0
#define	DEMOD_DD_GET_DVBT2_PLP_ID_RESPONSE_PLP_CONF_DPLP_TYPE1			1
#define	DEMOD_DD_GET_DVBT2_PLP_ID_RESPONSE_PLP_CONF_DPLP_TYPE2			2
#define	DEMOD_DD_GET_DVBT2_PLP_ID_RESPONSE_PLP_CONF_RESERVED			7
#endif /*DEMOD_CMD_GET_DVBT2_PLP_ID*/


#ifdef	DEMOD_CMD_BLIND_STATUS
typedef struct
{ /* LX_DEMOD_CMD_BLIND_STATUS_struct */
	UINT8	nothing;

} LX_DEMOD_CMD_BLIND_STATUS_struct;

typedef	struct
{ /* DEMOD_CMD_BLIND_STATUS_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT8	blindLock;
	UINT8	blindDone;
	UINT8	blindStatus;
	UINT8	srdFlg;
	UINT8	srdDone;
	UINT16	symRate;
	UINT8	symbolFlg;
	UINT8	channel_num_cnt;
	UINT8	channel_num;
	UINT8	auto_en;
	UINT8	siginfoStatus;
	UINT8	sig_count;
	UINT8	auto_chnum_cnt;
	UINT32	specCenter;
	UINT8	srdCnt;
	UINT8	sigsrchCnt;
	UINT8	debug1;
	UINT8	debug2;
	UINT8	debug3;

	UINT16	falling_idx[10];
	UINT16	rising_idx[10];

	UINT8	realSnum_L;
	UINT8	realSnum_M;
	UINT8	realSnum_H;
	UINT8	realSnum_All;

	UINT8	overLapEn;
	UINT8	jumpCnt;

	UINT32	temp_upCenterKhz;
	UINT32	tempDelta;
	UINT32	trCenter;
	UINT32	crCenter;
	UINT32	diffBwKhz;
	UINT32	uniFreq0;
	UINT32	ubFreq;
	UINT32	ubFreqC;
	UINT32	uniFreqT;
	UINT32	sigCeterKhz;
	UINT32	refCenterKhz;
	UINT32	diffBw_bw;
	UINT32	realCenterKhz;

	SINT32	uniFreq0_cfo;
	SINT32	sig_crcenter;

	UINT16	tempUpRidx;
	UINT16	tempUpFidx;
	UINT16	diffBw_rIdx;
	UINT16	diffBw_fIdx;

	SINT16	ubFreqStep;

	UINT8	lowSearchEn;
	UINT8	lockcheckEn;
	UINT8	clearJumpBuffer;
	UINT8	searchRange;
	UINT8	pwrcoeDone;
	UINT8	uniCableEn;
	UINT8	uniCnt;
	UINT8	uniCableLockCheck;
	UINT8	uniCalDone;
	UINT8	uniLockMonEn;
	UINT8	ubCnt;
	UINT8	ubLockPre;
	UINT8	ubLock;
	UINT8	nbw_val;
	UINT8	resetFlag;
	UINT8	rdData1;
	UINT8	rdData2;
} LX_DEMOD_CMD_BLIND_STATUS_REPLY_struct;

#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDLOCK_LSB					0
#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDLOCK_MASK					0x03
#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDLOCK_INIT					0
#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDLOCK_PROCESSING				1
#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDLOCK_LOCKED					2
#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDLOCK_NOTLOCKED				3

#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDDONE_LSB					2
#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDDONE_MASK					0x03
#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDDONE_INIT					0
#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDDONE_PROCESSING				1
#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDDONE_DONE					2
#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDDONE_NOTDONE				3

#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDSTATUS_LSB					4
#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDSTATUS_MASK					0x03
#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDSTATUS_INIT					0
#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDSTATUS_PROCESSING			1
#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDSTATUS_LOCKED				2
#define	DEMOD_DD_BLIND_STATUS_RESPONSE_BLINDSTATUS_NOTLOCKED			3
#endif /*DEMOD_CMD_BLIND_STATUS*/


#ifdef	DEMOD_CMD_BLIND_INIT
typedef struct
{ /* LX_DEMOD_CMD_BLIND_INIT_struct */
	UINT32	startFreq;
	UINT32	endFreq;
} LX_DEMOD_CMD_BLIND_INIT_struct;

typedef	struct
{ /* DEMOD_CMD_BLIND_INIT_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
} LX_DEMOD_CMD_BLIND_INIT_REPLY_struct;

#define	DEMOD_CMD_BLIND_INIT_STARTFREQ_LSB							0
#define	DEMOD_CMD_BLIND_INIT_STARTFREQ_MASK							0xffffffff

#define	DEMOD_CMD_BLIND_INIT_ENDFREQ_LSB								0
#define	DEMOD_CMD_BLIND_INIT_ENDFREQ_MASK							0xffffffff
#endif /*DEMOD_CMD_BLIND_INIT*/


#ifdef	DEMOD_CMD_BLIND_FOUNDINFO
typedef struct
{ /* LX_DEMOD_CMD_BLIND_STATUS_struct */
	UINT8	nothing;
} LX_DEMOD_CMD_BLIND_FOUNDINFO_struct;

typedef	struct
{ /* DEMOD_CMD_BLIND_STATUS_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT32	symrate;
	UINT32	center;
} LX_DEMOD_CMD_BLIND_FOUNDINFO_REPLY_struct;

#define	DEMOD_DD_BLIND_FOUNDINFO_RESPONSE_SYMRATE_LSB					0
#define	DEMOD_DD_BLIND_FOUNDINFO_RESPONSE_SYMRATE_MASK					0xFFFF

#define	DEMOD_DD_BLIND_FOUNDINFO_RESPONSE_CENTER_LSB					0
#define	DEMOD_DD_BLIND_FOUNDINFO_RESPONSE_CENTER_MASK					0xFFFFFFFF
#endif /*DEMOD_CMD_BLIND_FOUNDINFO*/


#ifdef	DEMOD_CMD_BLIND_END
typedef struct
{ /* LX_DEMOD_CMD_BLIND_END_struct */
	UINT8	nothing;
} LX_DEMOD_CMD_BLIND_END_struct;

typedef	struct
{ /* DEMOD_CMD_BLIND_END_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
} LX_DEMOD_CMD_BLIND_END_REPLY_struct;
#endif /*DEMOD_CMD_BLIND_STATUS*/


#ifdef	DEMOD_CMD_SET_DVBT2_BASEADDR_AXI
typedef	struct
{/*LX_DEMOD_CMD_SET_DVBT2_BASEADDR_AXI_struct */
	UINT8	nothing;
	UINT32	baseAddr1;
	UINT32	baseAddr2;
} LX_DEMOD_CMD_SET_DVBT2_BASEADDR_AXI_struct;

typedef struct
{ /* LX_DEMOD_CMD_SET_DVBT2_BASEADDR_AXI_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
} LX_DEMOD_CMD_SET_DVBT2_BASEADDR_AXI_REPLY_struct;

#define	DEMOD_CMD_SET_DVBT2_BASEADDR_AXI_BASEADDR_LSB					0
#define	DEMOD_CMD_SET_DVBT2_BASEADDR_AXI_BASEADDR_MASK					0xFFFFFFFF
#endif /*DEMOD_DD_DVBT2_BASEADDR_AXI*/


#ifdef	DEMOD_CMD_SET_DVB_BASEADDR_AXI
typedef	struct
{/*LX_DEMOD_CMD_SET_DVB_BASEADDR_AXI_struct */
	 UINT8	 nothing;
	 UINT32	 baseAddr1;
	 UINT32	 baseAddr2;
	 UINT32	 baseAddr3;

} LX_DEMOD_CMD_SET_DVB_BASEADDR_AXI_struct;

typedef struct
{ /* LX_DEMOD_CMD_SET_DVB_BASEADDR_AXI_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj *	STATUS;
} LX_DEMOD_CMD_SET_DVB_BASEADDR_AXI_REPLY_struct;

#define	DEMOD_CMD_SET_DVB_BASEADDR_AXI_BASEADDR_LSB						0
#define	DEMOD_CMD_SET_DVB_BASEADDR_AXI_BASEADDR_MASK						0xFFFFFFFF
#endif /*DEMOD_DD_DVB_BASEADDR_AXI*/


#ifdef	DEMOD_CMD_DTMB_STATUS
typedef	struct
{ /* LX_DEMOD_CMD_DTMB_STATUS_struct	*/
	 UINT8	 nothing;

} LX_DEMOD_CMD_DTMB_STATUS_struct;

typedef	struct
{ /* LX_DEMOD_CMD_DTMB_STATUS_REPLY_struct */
//	LX_DEMOD_L1_CommonReplayObj * STATUS;
	UINT16	if_agc;
	UINT16	mse_info;
	UINT32	ber;
	UINT32	cfo;
	UINT32	sfo;
	UINT8	op_mode;
	UINT8	pe;
	UINT8	constellation;
	UINT8	spInv;
	UINT8	lock_carr;
	UINT8	lock_fec;
	UINT8	il_mode;
	UINT8	carr_mode;
	UINT8	pn_const;
	UINT8	pn_mode;
	UINT8	cr;
} LX_DEMOD_CMD_DTMB_STATUS_REPLY_struct;

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_IF_AGC_LSB						0
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_IF_AGC_MASK						0xFFFF

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_MSE_INFO_LSB						0
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_MSE_INFO_MASK						0xFFFF

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_BER_LSB							0
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_BER_MASK							0x00FFFFFF

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_CFO_LSB							0
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_CFO_MASK							0x00FFFFFF

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_OP_MODE_LSB						0
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_OP_MODE_MASK						0xFF

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_PE_LSB							0
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_PE_MASK							0xFF

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_SPECINV_LSB						7
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_SPECINV_MASK						0x01

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_SFO_LSB							0
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_SFO_MASK							0x00FFFFFF

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_IL_MODE_LSB						4
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_IL_MODE_MASK						0x01
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_IL_MODE_720						1
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_IL_MODE_240						0

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_CONSTELLATION_LSB					0
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_CONSTELLATION_MASK				0x0F

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_CARR_MODE_LSB						7
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_CARR_MODE_MASK					0x01
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_CARR_MODE_MC						1
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_CARR_MODE_SC						0

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_PN_CONST_LSB						6
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_PN_CONST_MASK						0x01
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_PN_CONST_CONSTANT					1
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_PN_CONST_VARIABLE					0

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_PN_MODE_LSB						4
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_PN_MODE_MASK						0x03
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_PN_MODE_PN945						3
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_PN_MODE_PN595						2
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_PN_MODE_PN420						1

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_CR_LSB							0
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_CR_MASK							0x0f

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_LOCK_CARR_LSB						1
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_LOCK_CARR_MASK					0x01

#define	DEMOD_DD_DTMB_STATUS_RESPONSE_LOCK_FEC_LSB						0
#define	DEMOD_DD_DTMB_STATUS_RESPONSE_LOCK_FEC_MASK						0x01
#endif /*DEMOD_DD_DTMB_STATUS*/


/* --------------------------------------------*/
/* COMMANDS STRUCT				 */
/* This is used to store all command fields	 */
/* --------------------------------------------*/
typedef struct
{ /* DEMOD_CmdObj struct */

#ifdef	DEMOD_CMD_SET_REG
LX_DEMOD_CMD_SET_REG_struct											dd_set_reg;
#endif /* DEMOD_DD_REG_CMD */

#ifdef	DEMOD_CMD_SET_PROP
LX_DEMOD_CMD_SET_PROP_struct											set_property;
#endif /* DEMOD_L1_SET_PROP_CMD	*/

#ifdef	DEMOD_CMD_SET_REPEAT
LX_DEMOD_CMD_SET_REPEAT_struct										dd_set_repeat;
#endif /* DEMOD_CMD_SET_REPEAT */

#ifdef	DEMOD_CMD_RESTART
LX_DEMOD_CMD_RESTART_struct											dd_restart;
#endif /* DEMOD_CMD_RESTART */

#ifdef	DEMOD_CMD_SOFT_RESET
LX_DEMOD_CMD_SOFT_RESET_struct										dd_soft_reset;
#endif /* DEMOD_CMD_SOFT_RESET */

#ifdef	DEMOD_CMD_POWER_SAVE
LX_DEMOD_CMD_POWER_SAVE_struct										power_save;
#endif /* DEMOD_CMD_POWER_SAVE */

#ifdef	DEMOD_CMD_GET_REG
LX_DEMOD_CMD_GET_REG_struct											dd_get_reg;
#endif /* DEMOD_CMD_GET_REG */

#ifdef	DEMOD_CMD_GET_PROP
LX_DEMOD_CMD_GET_PROP_struct											get_property;
#endif /* DEMOD_L1_GET_PROP_CMD	*/

#ifdef	DEMOD_CMD_GET_PART_INFO
LX_DEMOD_CMD_GET_PART_INFO_struct									part_info;
#endif /* DEMOD_CMD_GET_PART_INFO */

#ifdef	DEMOD_CMD_SET_TUNE
LX_DEMOD_CMD_SET_TUNE_struct											dd_tune;
#endif /* DEMOD_CMD_SET_TUNE	*/

#ifdef	DEMOD_CMD_STATUS
LX_DEMOD_CMD_STATUS_struct											dd_status;
#endif /* DEMOD_CMD_STATUS */

#ifdef	DEMOD_CMD_TSCLK_STATUS
LX_DEMOD_CMD_TSCLK_STATUS_struct										dd_tsclk_status;
#endif /* DEMOD_CMD_TSCLK_STATUS */


#ifdef	DEMOD_CMD_VSB_STATUS
LX_DEMOD_CMD_VSB_STATUS_struct										vsb_status;
#endif /*DEMOD_CMD_VSB_STATUS */

#ifdef	DEMOD_CMD_QAM_STATUS
LX_DEMOD_CMD_QAM_STATUS_struct										qam_status;
#endif /*DEMOD_CMD_QAM_STATUS */

#ifdef	DEMOD_CMD_ATSC3_STATUS
//DEMOD_REQ_ATSC3_STATUS_struct										atsc3_status;
#endif /* DEMOD_CMD_ATSC3_STATUS */

#ifdef	DEMOD_CMD_ATSC3_PLP_ID
//DEMOD_REQ_ATSC3_PLP_ID_struct										atsc3_plp_id;
#endif /* DEMOD_CMD_ATSC3_PLP_ID */

#ifdef	DEMOD_CMD_ATSC3_PLP_INFO
//LX_DEMOD_CMD_ATSC3_PLP_INFO_struct									atsc3_plp_info;
#endif /* DEMOD_CMD_ATSC3_PLP_INFO */

#ifdef	DEMOD_CMD_ATSC3_PLP_SELECT
DEMOD_REQ_ATSC3_PLP_SELECT_struct									atsc3_plp_select;
#endif /* DEMOD_CMD_ATSC3_PLP_SELECT	*/

#ifdef DEMOD_CMD_ATSC3_SET_BASEADDR_AXI
DEMOD_CMD_ATSC3_SET_BASEADDR_AXI_struct									atsc3_baseaddr_axi;
#endif /* DEMOD_CMD_ATSC3_SET_BASEADDR_AXI */

#ifdef	DEMOD_CMD_SET_SELF_RESET_PARAM
LX_DEMOD_CMD_SELF_RESET_struct											dd_selfrst;
#endif /* DEMOD_CMD_SELF_RESET */

#ifdef	DEMOD_CMD_LOCKTIME
LX_DEMOD_CMD_LOCKTIME_struct											dd_locktime;
#endif /*DEMOD_CMD_LOCKTIME */

/*******************************************************************************/
/*******************************************************************************/
/*******************************************************************************/
/***************ISDBT /	DVBT/ DVBT2 / DVBS / DVBS2/DVBC/ DVBC2/	 DEBUG*********/
/*******************************************************************************/
/*******************************************************************************/
/*******************************************************************************/

#ifdef	DEMOD_CMD_SET_ISDBT_BASEADDR_AXI
LX_DEMOD_CMD_SET_ISDBT_BASEADDR_AXI_struct								isdbt_baseaddr_axi;
#endif /*DEMOD_CMD_SET_ISDBT_BASEADDR_AXI */

#ifdef	DEMOD_CMD_SET_DTMB_BASEADDR_AXI
LX_DEMOD_CMD_SET_DTMB_BASEADDR_AXI_struct								dtmb_baseaddr_axi;
#endif /*DEMOD_CMD_SET_DTMB_BASEADDR_AXI	*/

#ifdef	DEMOD_CMD_DVBT2_PLP_SELECT
LX_DEMOD_CMD_DVBT2_PLP_SELECT_struct									dvbt2_plp_select;
#endif /* DEMOD_CMD_DVBT2_PLP_SELECT	*/

#ifdef	DEMOD_CMD_DISEQC_STATUS
LX_DEMOD_CMD_DISEQC_STATUS_struct									dd_diseqc_status;
#endif /* DEMOD_CMD_DISEQC_STATUS */

#ifdef	DEMOD_CMD_DVBC_SRD
LX_DEMOD_CMD_DVBC_SRD_struct											dvbc_sym_rate;
#endif /* DEMOD_CMD_DVBC_SRD	*/

#ifdef	DEMOD_CMD_DVBC2_STARTFREQUENCY
LX_DEMOD_CMD_DVBC2_STARTFREQUENCY_struct								dvbc2_start_frequency;
#endif /* DEMOD_CMD_DVBC2_STARTFREQUENCY */

#ifdef	DEMOD_CMD_DVBC2_PLP_SELECT
LX_DEMOD_CMD_DVBC2_PLP_SELECT_struct									dvbc2_plp_info;
#endif /* DEMOD_CMD_DVBC2_PLP_SELECT	*/

#ifdef	DEMOD_CMD_DVBS_SYM_RATE
LX_DEMOD_CMD_DVBS_SYM_RATE_struct									dvbs_sym_rate;
#endif /* DEMOD_CMD_DVBS_SYM_RATE */

#ifdef	DEMOD_CMD_DVBS_OPERATING_MODE
LX_DEMOD_CMD_DVBS_OPERATING_MODE_struct								operate_mode;
#endif /* DEMOD_CMD_DVBS_OPERATING_MODE */

#ifdef	DEMOD_CMD_DISEQC_SEND
LX_DEMOD_CMD_DISEQC_SEND_struct										dd_diseqc_send;
#endif /* DEMOD_CMD_DISEQC_SEND */

#ifdef	DEMOD_CMD_DVBS_STATUS
LX_DEMOD_CMD_DVBS_STATUS_struct										dvbs_status;
#endif /* DEMOD_CMD_DVBS_STATUS */

#ifdef	DEMOD_CMD_DVBS2_STATUS
LX_DEMOD_CMD_DVBS2_STATUS_struct										dvbs2_status;
#endif /* DEMOD_CMD_DVBS2_STATUS */

#ifdef	DEMOD_CMD_DVBT_STATUS
LX_DEMOD_CMD_DVBT_STATUS_struct										dvbt_status;
#endif /* DEMOD_CMD_DVBT_STATUS */

#ifdef	DEMOD_CMD_DVBT2_STATUS
LX_DEMOD_CMD_DVBT2_STATUS_struct										dvbt2_status;
#endif /* DEMOD_CMD_DVBT2_STATUS */

#ifdef	DEMOD_CMD_DVBT2_PLP_INFO
LX_DEMOD_CMD_DVBT2_PLP_INFO_struct									dvbt2_plp_info;
#endif /* DEMOD_CMD_DVBT2_PLP_INFO */

#ifdef	DEMOD_CMD_ISDBT_STATUS
LX_DEMOD_CMD_ISDBT_STATUS_struct										isdbt_status;
#endif /*DEMOD_CMD_ISDBT_STATUS */

#ifdef	DEMOD_CMD_ISDBT_TMCC_INFO
LX_DEMOD_CMD_ISDBT_TMCC_INFO_struct									isdbt_tmcc_info;
#endif /*DEMOD_CMD_ISDBT_TMCC_INFO */

#ifdef	DEMOD_CMD_DVBC_STATUS
LX_DEMOD_CMD_DVBC_STATUS_struct										dvbc_status;
#endif /* DEMOD_CMD_DVBC_STATUS */

#ifdef	DEMOD_CMD_DVBC2_STATUS
LX_DEMOD_CMD_DVBC2_STATUS_struct										dvbc2_status;
#endif /* DEMOD_CMD_DVBC2_STATUS */

#ifdef	DEMOD_CMD_GET_SIGSRCH_INFO
LX_DEMOD_CMD_GET_SIGSRCH_INFO_struct								dd_sigsrch_info;
#endif /*DEMOD_CMD_GET_SIGSRCH_INFO */

#ifdef	DEMOD_CMD_GET_SIGSRCH_NUM
LX_DEMOD_CMD_GET_SIGSRCH_NUM_struct								dd_sigsrch_num;
#endif /*DEMOD_CMD_GET_SIGSRCH_NUM */

#ifdef	DEMOD_CMD_GET_DVBT2_PLP_ID
LX_DEMOD_CMD_GET_DVBT2_PLP_ID_struct									dvbt2_plp_id;
#endif /* DEMOD_CMD_GET_DVBT2_PLP_ID	*/

#ifdef	DEMOD_CMD_BLIND_STATUS
LX_DEMOD_CMD_BLIND_STATUS_struct										blind_status;
#endif /* DEMOD_CMD_BLIND_STATUS */

#ifdef	DEMOD_CMD_BLIND_INIT
LX_DEMOD_CMD_BLIND_INIT_struct										blind_init;
#endif /* DEMOD_CMD_BLIND_INIT */

#ifdef	DEMOD_CMD_BLIND_FOUNDINFO
LX_DEMOD_CMD_BLIND_FOUNDINFO_struct									blind_foundinfo;
#endif /* DEMOD_CMD_BLIND_FOUNDINFO */

#ifdef	DEMOD_CMD_BLIND_END
LX_DEMOD_CMD_BLIND_END_struct										blind_end;
#endif /* DEMOD_CMD_BLIND_END */

#ifdef	DEMOD_CMD_SET_DVBT2_BASEADDR_AXI
LX_DEMOD_CMD_SET_DVBT2_BASEADDR_AXI_struct								dvbt2_baseaddr_axi;
#endif /*DEMOD_CMD_SET_DVBT2_BASEADDR_AXI */

#ifdef	DEMOD_CMD_DTMB_STATUS
LX_DEMOD_CMD_DTMB_STATUS_struct										dtmb_status;
#endif /*DEMOD_CMD_DTMB_STATUS */

} LX_DEMOD_L1_CmdObj;


/* --------------------------------------------*/
/* COMMANDS REPLY STRUCT			 */
/* This stores all command reply fields	 */
/* --------------------------------------------*/
typedef	struct
{ /* DEMOD_CmdReplyObj struct */

#ifdef	DEMOD_CMD_SET_REG
LX_DEMOD_CMD_SET_REG_REPLY_struct									dd_set_reg;
#endif /* DEMOD_DD_REG_CMD */

#ifdef	DEMOD_CMD_SET_PROP
LX_DEMOD_CMD_SET_PROP_REPLY_struct									set_property;
#endif /* DEMOD_L1_SET_PROP_CMD	*/

#ifdef	DEMOD_CMD_SET_REPEAT
LX_DEMOD_CMD_SET_REPEAT_REPLY_struct									dd_set_repeat;
#endif /* DEMOD_CMD_SET_REPEAT */

#ifdef	DEMOD_CMD_RESTART
LX_DEMOD_CMD_RESTART_REPLY_struct									dd_restart;
#endif /* DEMOD_CMD_RESTART */

#ifdef	DEMOD_CMD_SOFT_RESET
LX_DEMOD_CMD_SOFT_RESET_REPLY_struct									dd_soft_reset;
#endif /* DEMOD_CMD_SOFT_RESET */

#ifdef	DEMOD_CMD_POWER_SAVE
LX_DEMOD_CMD_POWER_SAVE_REPLY_struct									power_save;
#endif /* DEMOD_CMD_POWER_SAVE */

#ifdef	DEMOD_CMD_GET_REG
LX_DEMOD_CMD_GET_REG_REPLY_struct									dd_get_reg;
#endif /* DEMOD_CMD_GET_REG */

#ifdef	DEMOD_CMD_GET_PROP
LX_DEMOD_CMD_GET_PROP_REPLY_struct									get_property;
#endif /* DEMOD_L1_GET_PROP_CMD	*/

#ifdef	DEMOD_CMD_GET_PART_INFO
LX_DEMOD_CMD_GET_PART_INFO_REPLY_struct								part_info;
#endif /* DEMOD_CMD_GET_PART_INFO */

#ifdef	DEMOD_CMD_SET_TUNE
LX_DEMOD_CMD_SET_TUNE_REPLY_struct									dd_tune;
#endif /* DEMOD_CMD_SET_TUNE	*/

#ifdef	DEMOD_CMD_STATUS
LX_DEMOD_CMD_STATUS_REPLY_struct										dd_status;
#endif /* DEMOD_CMD_STATUS */

#ifdef	DEMOD_CMD_TSCLK_STATUS
LX_DEMOD_CMD_TSCLK_STATUS_REPLY_struct								dd_tsclk_status;
#endif /* DEMOD_CMD_TSCLK_STATUS */

#ifdef	DEMOD_CMD_VSB_STATUS
LX_DEMOD_CMD_VSB_STATUS_REPLY_struct									vsb_status;
#endif /*DEMOD_CMD_VSB_STATUS */

#ifdef	DEMOD_CMD_QAM_STATUS
LX_DEMOD_CMD_QAM_STATUS_REPLY_struct									qam_status;
#endif /*DEMOD_CMD_QAM_STATUS */

#ifdef	DEMOD_CMD_ATSC3_STATUS
DEMOD_RES_ATSC3_STATUS_struct										atsc3_status;
#endif /* DEMOD_CMD_ATSC3_STATUS */

#ifdef	DEMOD_CMD_ATSC3_PLP_ID
DEMOD_RES_ATSC3_PLP_ID_struct										atsc3_plp_id;
#endif /* DEMOD_CMD_ATSC3_PLP_ID */

#ifdef	DEMOD_CMD_ATSC3_PLP_INFO
DEMOD_RES_ATSC3_PLP_INFO_struct										atsc3_plp_info;
#endif /* DEMOD_CMD_ATSC3_PLP_INFO */

#ifdef	DEMOD_CMD_ATSC3_PLP_SELECT
DEMOD_RES_ATSC3_PLP_SELECT_struct									atsc3_plp_select;
#endif /* DEMOD_CMD_ATSC3_PLP_SELECT	*/

#ifdef	DEMOD_CMD_SELF_RESET
LX_DEMOD_CMD_SELF_RESET_REPLY_struct									dd_selfrst;
#endif /* DEMOD_CMD_SELF_RESET */

#ifdef	DEMOD_CMD_LOCKTIME
LX_DEMOD_CMD_LOCKTIME_REPLY_struct									dd_locktime;
#endif /*DEMOD_CMD_LOCKTIME */

/*******************************************************************************/
/*******************************************************************************/
/*******************************************************************************/
/***************ISDBT /	DVBT/ DVBT2 / DVBS / DVBS2/DVBC/ DVBC2/	 DEBUG*********/
/*******************************************************************************/
/*******************************************************************************/
/*******************************************************************************/

#ifdef	DEMOD_CMD_SET_ISDBT_BASEADDR_AXI
LX_DEMOD_CMD_SET_ISDBT_BASEADDR_AXI_REPLY_struct							isdbt_baseaddr_axi;
#endif /*DEMOD_CMD_SET_ISDBT_BASEADDR_AXI */

#ifdef	DEMOD_CMD_SET_DTMB_BASEADDR_AXI
LX_DEMOD_CMD_SET_DTMB_BASEADDR_AXI_REPLY_struct							dtmb_baseaddr_axi;
#endif /*DEMOD_CMD_SET_DTMB_BASEADDR_AXI	*/

#ifdef	DEMOD_CMD_DVBT2_PLP_SELECT
LX_DEMOD_CMD_DVBT2_PLP_SELECT_REPLY_struct							dvbt2_plp_select;
#endif /* DEMOD_CMD_DVBT2_PLP_SELECT	*/

#ifdef	DEMOD_CMD_DISEQC_STATUS
LX_DEMOD_CMD_DISEQC_STATUS_REPLY_struct								dd_diseqc_status;
#endif /* DEMOD_CMD_DISEQC_STATUS */

#ifdef	DEMOD_CMD_DVBC_SRD
LX_DEMOD_CMD_DVBC_SRD_REPLY_struct									dvbc_sym_rate;
#endif /* DEMOD_CMD_DVBC_SRD	*/

#ifdef	DEMOD_CMD_DVBC2_STARTFREQUENCY
LX_DEMOD_CMD_DVBC2_STARTFREQUENCY_REPLY_struct						dvbc2_start_frequency;
#endif /* DEMOD_CMD_DVBC2_STARTFREQUENCY */

#ifdef	DEMOD_CMD_DVBC2_PLP_SELECT
LX_DEMOD_CMD_DVBC2_PLP_SELECT_REPLY_struct							dvbc2_plp_info;
#endif /* DEMOD_CMD_DVBC2_PLP_SELECT	*/

#ifdef	DEMOD_CMD_DVBS_SYM_RATE
LX_DEMOD_CMD_DVBS_SYM_RATE_REPLY_struct								dvbs_sym_rate;
#endif /* DEMOD_CMD_DVBS_SYM_RATE */

#ifdef	DEMOD_CMD_DVBS_OPERATING_MODE
LX_DEMOD_CMD_DVBS_OPERATING_MODE_REPLY_struct						operate_mode;
#endif /* DEMOD_CMD_DVBS_OPERATING_MODE */

#ifdef	DEMOD_CMD_DISEQC_SEND
LX_DEMOD_CMD_DISEQC_SEND_REPLY_struct								dd_diseqc_send;
#endif /* DEMOD_CMD_DISEQC_SEND */

#ifdef	DEMOD_CMD_DVBS_STATUS
LX_DEMOD_CMD_DVBS_STATUS_REPLY_struct								dvbs_status;
#endif /* DEMOD_CMD_DVBS_STATUS */

#ifdef	DEMOD_CMD_DVBS2_STATUS
LX_DEMOD_CMD_DVBS2_STATUS_REPLY_struct								dvbs2_status;
#endif /* DEMOD_CMD_DVBS2_STATUS */

#ifdef	DEMOD_CMD_DVBT_STATUS
LX_DEMOD_CMD_DVBT_STATUS_REPLY_struct								dvbt_status;
#endif /* DEMOD_CMD_DVBT_STATUS */

#ifdef	DEMOD_CMD_DVBT2_STATUS
LX_DEMOD_CMD_DVBT2_STATUS_REPLY_struct								dvbt2_status;
#endif /* DEMOD_CMD_DVBT2_STATUS */

#ifdef	DEMOD_CMD_DVBT2_PLP_INFO
LX_DEMOD_CMD_DVBT2_PLP_INFO_REPLY_struct								dvbt2_plp_info;
#endif /* DEMOD_DVBT2_PLP_INFO_CMD */

#ifdef	DEMOD_CMD_ISDBT_STATUS
LX_DEMOD_CMD_ISDBT_STATUS_REPLY_struct								isdbt_status;
#endif /*DEMOD_CMD_ISDBT_STATUS */

#ifdef	DEMOD_CMD_ISDBT_TMCC_INFO
LX_DEMOD_CMD_ISDBT_TMCC_INFO_REPLY_struct							isdbt_tmcc_info;
#endif /*DEMOD_CMD_ISDBT_TMCC_INFO */

#ifdef	DEMOD_CMD_DVBC_STATUS
LX_DEMOD_CMD_DVBC_STATUS_REPLY_struct								dvbc_status;
#endif /* DEMOD_CMD_DVBC_STATUS */

#ifdef	DEMOD_CMD_DVBC2_STATUS
LX_DEMOD_CMD_DVBC2_STATUS_REPLY_struct								dvbc2_status;
#endif /* DEMOD_CMD_DVBC2_STATUS */

#ifdef	DEMOD_CMD_GET_SIGSRCH_INFO
LX_DEMOD_CMD_GET_SIGSRCH_INFO_REPLY_struct						dd_sigsrch_info;
#endif /*DEMOD_DD_GET_DD_SIGSRCH_CMD */

#ifdef	DEMOD_CMD_GET_SIGSRCH_NUM
LX_DEMOD_CMD_GET_SIGSRCH_NUM_REPLY_struct							dd_sigsrch_num;
#endif /*DEMOD_CMD_GET_SIGSRCH_INFO */

#ifdef	DEMOD_CMD_GET_DVBT2_PLP_ID
LX_DEMOD_CMD_GET_DVBT2_PLP_ID_REPLY_struct							dvbt2_plp_id;
#endif /* DEMOD_CMD_GET_DVBT2_PLP_ID	*/

#ifdef	DEMOD_CMD_BLIND_STATUS
LX_DEMOD_CMD_BLIND_STATUS_REPLY_struct								blind_status;
#endif /* DEMOD_CMD_BLIND_STATUS */

#ifdef	DEMOD_CMD_BLIND_INIT
LX_DEMOD_CMD_BLIND_INIT_REPLY_struct									blind_init;
#endif /* DEMOD_CMD_BLIND_INIT */

#ifdef	DEMOD_CMD_BLIND_FOUNDINFO
LX_DEMOD_CMD_BLIND_FOUNDINFO_REPLY_struct							blind_foundinfo;
#endif /* DEMOD_CMD_BLIND_FOUNDINFO */

#ifdef	DEMOD_CMD_BLIND_END
LX_DEMOD_CMD_BLIND_END_REPLY_struct									blind_end;
#endif /* DEMOD_CMD_BLIND_END */

#ifdef	DEMOD_CMD_SET_DVBT2_BASEADDR_AXI
LX_DEMOD_CMD_SET_DVBT2_BASEADDR_AXI_REPLY_struct							dvbt2_baseaddr_axi;
#endif /*DEMOD_CMD_SET_DVBT2_BASEADDR_AXI */

#ifdef	DEMOD_CMD_SET_DVB_BASEADDR_AXI
LX_DEMOD_CMD_SET_DVB_BASEADDR_AXI_REPLY_struct							dvb_baseaddr_axi;
#endif /*DEMOD_CMD_SET_DVB_BASEADDR_AXI */

#ifdef	DEMOD_CMD_DTMB_STATUS
LX_DEMOD_CMD_DTMB_STATUS_REPLY_struct								dtmb_status;
#endif /*DEMOD_CMD_DTMB_STATUS */


} LX_DEMOD_L1_CmdReplyObj;

#endif /*_DBB_DEMOD_L1_COMMANDS_H_ */




