/*
	SIC LABORATORY, LG ELECTRONICS INC., SEOUL, KOREA
	Copyright(c) 2013 by LG Electronics Inc.

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	version 2 as published by the Free Software Foundation.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.
*/


/** @file
 *
 * main driver implementation for de device.
 * de device will teach you how to make device driver with new platform.
 *
 * author     jaemo.kim (jaemo.kim@lge.com)
 * version    1.0
 * date       2011.04.06
 * note       Additional information.
 *
 * @addtogroup lg1152_de
 * @{
 */

#ifndef  DE_CFG_E60_INC
#define  DE_CFG_E60_INC

/*----------------------------------------------------------------------------------------
 *   Control Constants
 *---------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------
 *   File Inclusions
 *---------------------------------------------------------------------------------------*/
#include "de_model.h"
#include "de_ver_def.h"
#include "de_cfg_def_e60.h"

/*----------------------------------------------------------------------------------------
 *   Constant Definitions
 *---------------------------------------------------------------------------------------*/
#define VIDEO_E60_FRAME_DDR_LW_SCR          783
#define VIDEO_E60_FRAME_DDR_LW_CAP          348
#define VIDEO_E60_FRAME_DDR_LW_TNR_IPC      870
#define VIDEO_E60_FRAME_DDR_RW_SCR          783
#define VIDEO_E60_FRAME_DDR_RW_CAP          348
#define VIDEO_E60_FRAME_DDR_RW_TNR_IPC      696
#define VIDEO_E60_FRAME_DDR_SW_VCR          228
#define VIDEO_E60_FRAME_DDR_SW_MDI          138
#define VIDEO_E60_FRAME_DDR_LW_TNM          69
#define VIDEO_E60_FRAME_DDR_LW_CSC          416

#define VIDEO_E60_CODEC_DDR_BASE            (0x70000000)
#define VIDEO_E60_LOWER_DDR_BASE            (0x80000000)

#if (CONFIG_LX_BOARD_FPGA==1)
#define VIDEO_E60_FRAME_DDR_BASE            (0xA0000000)		/* FPGA board */
#else
#define VIDEO_E60_FRAME_DDR_BASE            (0x80000000)		/* SYSTEM board */
#endif
#define VIDEO_E60_FRAME_FIRMWARE_OFFSET     (0x00000000)

#define VIDEO_E60_CODEC_DDR_OFFSET          (0x2000000)

#define VIDEO_E60_ROW2PHY(_r)               (CONV_MEM_ROW2BYTE(_r) | g_FwBase_E60)

#define VIDEO_E60_FIRMWARE_ROW_SIZE_OF_DE   (VIDEO_MEM_FIRMWARE_ROW_SIZE*2)
#define VIDEO_E60_FIRMWARE_ROW_SIZE_OF_LED  (VIDEO_MEM_FIRMWARE_ROW_SIZE)
#define VIDEO_E60_FIRMWARE_ROW_SIZE_OF_IPC  (VIDEO_MEM_FIRMWARE_ROW_SIZE)
#define VIDEO_E60_FIRMWARE_ROW_SIZE_IPC_MC	(1)
#define VIDEO_E60_FIRMWARE_ROW_SIZE_DDR_UP	(1)
#define VIDEO_E60_FIRMWARE_ROW_SIZE_OF_TTX	(1)
#define VIDEO_E60_FIRMWARE_ROW_SIZE_WEB_OS	(1)
#define VIDEO_E60_FIRMWARE_ROW_SIZE_REG_TR	(1)
#define VIDEO_E60_FIRMWARE_ROW_SIZE_DOLBY_HDR	(1)

#define VIDEO_E60_FIRMWARE_ROW_BASE_OF_DE	(VIDEO_E60_FRAME_FIRMWARE_OFFSET/VIDEO_ROW_STRIDE)
#define VIDEO_E60_FIRMWARE_ROW_BASE_OF_LED	(VIDEO_E60_FIRMWARE_ROW_BASE_OF_DE  + VIDEO_E60_FIRMWARE_ROW_SIZE_OF_DE)
#define VIDEO_E60_FIRMWARE_ROW_BASE_OF_IPC	(VIDEO_E60_FIRMWARE_ROW_BASE_OF_LED + VIDEO_E60_FIRMWARE_ROW_SIZE_OF_LED)
#define VIDEO_E60_START_OF_FRAME_MEMORY		(VIDEO_E60_FIRMWARE_ROW_BASE_OF_IPC + VIDEO_E60_FIRMWARE_ROW_SIZE_OF_IPC)

#define VIDEO_E60_ROW_SIZE_OF_FRAME_MEMORY  (VIDEO_E60_FRAME_DDR_LW_SCR + VIDEO_E60_FRAME_DDR_LW_TNR_IPC + VIDEO_E60_FRAME_DDR_RW_SCR + VIDEO_E60_FRAME_DDR_RW_TNR_IPC + VIDEO_E60_FRAME_DDR_SW_VCR + VIDEO_E60_FRAME_DDR_LW_TNM)
#define VIDEO_E60_ROW_SIZE_OF_FRAME_PREW    (VIDEO_E60_FRAME_DDR_LW_CAP + VIDEO_E60_FRAME_DDR_RW_CAP + 32)
#define VIDEO_E60_ROW_SIZE_OF_FRAME_GRAP    (VIDEO_E60_FRAME_DDR_SW_MDI)
#define VIDEO_E60_ROW_SIZE_OF_FRAME_GCSC    (VIDEO_E60_FRAME_DDR_LW_CSC)

#define VIDEO_E60_FIRMWARE_ROW_BASE_IPC_MC	(VIDEO_E60_FIRMWARE_ROW_BASE_OF_IPC                                     )
#define VIDEO_E60_FIRMWARE_ROW_BASE_DDR_UP	(VIDEO_E60_FIRMWARE_ROW_BASE_OF_IPC + VIDEO_E60_FIRMWARE_ROW_SIZE_IPC_MC)
#define VIDEO_E60_FIRMWARE_ROW_BASE_OF_TTX	(VIDEO_E60_FIRMWARE_ROW_BASE_DDR_UP + VIDEO_E60_FIRMWARE_ROW_SIZE_DDR_UP)
#define VIDEO_E60_FIRMWARE_ROW_BASE_WEB_OS	(VIDEO_E60_FIRMWARE_ROW_BASE_OF_TTX + VIDEO_E60_FIRMWARE_ROW_SIZE_OF_TTX)
#define VIDEO_E60_FIRMWARE_ROW_BASE_REG_TR	(VIDEO_E60_FIRMWARE_ROW_BASE_WEB_OS + VIDEO_E60_FIRMWARE_ROW_SIZE_WEB_OS)
#define VIDEO_E60_FIRMWARE_ROW_BASE_DOLBY_HDR	(VIDEO_E60_FIRMWARE_ROW_BASE_REG_TR + VIDEO_E60_FIRMWARE_ROW_SIZE_REG_TR)


#define VIDEO_E60_FIRMWARE_MEM_BASE_OF_DE   VIDEO_E60_ROW2PHY(VIDEO_E60_FIRMWARE_ROW_BASE_OF_DE)
#define VIDEO_E60_FIRMWARE_MEM_BASE_OF_LED  VIDEO_E60_ROW2PHY(VIDEO_E60_FIRMWARE_ROW_BASE_OF_LED)
#define VIDEO_E60_FIRMWARE_MEM_BASE_OF_IPC  VIDEO_E60_ROW2PHY(VIDEO_E60_FIRMWARE_ROW_BASE_OF_IPC)
#define VIDEO_E60_FIRMWARE_MEM_BASE_DDR_UP	VIDEO_E60_ROW2PHY(VIDEO_E60_FIRMWARE_ROW_BASE_DDR_UP)
#define VIDEO_E60_FIRMWARE_MEM_BASE_OF_TTX	VIDEO_E60_ROW2PHY(VIDEO_E60_FIRMWARE_ROW_BASE_OF_TTX)
#define VIDEO_E60_FIRMWARE_MEM_BASE_WEB_OS	VIDEO_E60_ROW2PHY(VIDEO_E60_FIRMWARE_ROW_BASE_WEB_OS)
#define VIDEO_E60_FIRMWARE_MEM_BASE_REG_TR	VIDEO_E60_ROW2PHY(VIDEO_E60_FIRMWARE_ROW_BASE_REG_TR)
#define VIDEO_E60_FIRMWARE_MEM_BASE_DOLBY_HDR	VIDEO_E60_ROW2PHY(VIDEO_E60_FIRMWARE_ROW_BASE_DOLBY_HDR)

#define VIDEO_E60_MBASE_OF_FRAME_MEMORY     VIDEO_E60_ROW2PHY(VIDEO_E60_START_OF_FRAME_MEMORY)

#define VIDEO_E60_FIRMWARE_MEM_SIZE_OF_DE	CONV_MEM_ROW2BYTE(VIDEO_E60_FIRMWARE_ROW_SIZE_OF_DE)
#define VIDEO_E60_FIRMWARE_MEM_SIZE_OF_LED	CONV_MEM_ROW2BYTE(VIDEO_E60_FIRMWARE_ROW_SIZE_OF_LED)
#define VIDEO_E60_FIRMWARE_MEM_SIZE_OF_IPC	CONV_MEM_ROW2BYTE(VIDEO_E60_FIRMWARE_ROW_SIZE_OF_IPC)
#define VIDEO_E60_FIRMWARE_MEM_SIZE_DDR_UP	CONV_MEM_ROW2BYTE(VIDEO_E60_FIRMWARE_ROW_SIZE_DDR_UP)
#define VIDEO_E60_FIRMWARE_MEM_SIZE_OF_TTX	CONV_MEM_ROW2BYTE(VIDEO_E60_FIRMWARE_ROW_SIZE_OF_TTX)
#define VIDEO_E60_FIRMWARE_MEM_SIZE_WEB_OS	CONV_MEM_ROW2BYTE(VIDEO_E60_FIRMWARE_ROW_SIZE_WEB_OS)
#define VIDEO_E60_FIRMWARE_MEM_SIZE_REG_TR	CONV_MEM_ROW2BYTE(VIDEO_E60_FIRMWARE_ROW_SIZE_REG_TR)
#define VIDEO_E60_MEM_SIZE_OF_FRAME_MEMORY  CONV_MEM_ROW2BYTE(VIDEO_E60_ROW_SIZE_OF_FRAME_MEMORY)
//#define VIDEO_E60_MEM_SIZE_OF_FRAME_PREW    CONV_MEM_ROW2BYTE(VIDEO_E60_ROW_SIZE_OF_FRAME_PREW)
#define VIDEO_E60_MEM_SIZE_OF_FRAME_GRAP    CONV_MEM_ROW2BYTE(VIDEO_E60_ROW_SIZE_OF_FRAME_GRAP)
#define VIDEO_E60_MEM_SIZE_OF_FRAME_GCSC    CONV_MEM_ROW2BYTE(VIDEO_E60_ROW_SIZE_OF_FRAME_GCSC)

#define VIDEO_E60_FIRMWARE_ROW_OFST_IPC_MC	(0)
#define VIDEO_E60_FIRMWARE_ROW_OFST_DDR_UP	(VIDEO_E60_FIRMWARE_ROW_OFST_IPC_MC + VIDEO_E60_FIRMWARE_ROW_SIZE_IPC_MC)
#define VIDEO_E60_FIRMWARE_ROW_OFST_OF_TTX	(VIDEO_E60_FIRMWARE_ROW_OFST_DDR_UP + VIDEO_E60_FIRMWARE_ROW_SIZE_DDR_UP)
#define VIDEO_E60_FIRMWARE_ROW_OFST_WEB_OS	(VIDEO_E60_FIRMWARE_ROW_OFST_OF_TTX + VIDEO_E60_FIRMWARE_ROW_SIZE_WEB_OS)
#define VIDEO_E60_FIRMWARE_ROW_OFST_REG_TR	(VIDEO_E60_FIRMWARE_ROW_OFST_WEB_OS + VIDEO_E60_FIRMWARE_ROW_SIZE_OF_TTX)

#define VIDEO_E60_FW_SHARED_OFST_VTM		(0)
#define VIDEO_E60_FW_SHARED_SIZE_VTM		(32*1024)
#define VIDEO_E60_FW_SHARED_OFST_VTV		(VIDEO_E60_FW_SHARED_OFST_VTM+VIDEO_E60_FW_SHARED_SIZE_VTM)
#define VIDEO_E60_FW_SHARED_SIZE_VTV		(32*1024)
#define VIDEO_E60_FW_SHARED_OFST_GPS		(VIDEO_E60_FW_SHARED_OFST_VTV+VIDEO_E60_FW_SHARED_SIZE_VTV)
#define VIDEO_E60_FW_SHARED_SIZE_GPS		(32*1024)
#define VIDEO_E60_FW_SHARED_OFST_DLY		(VIDEO_E60_FW_SHARED_OFST_GPS+VIDEO_E60_FW_SHARED_SIZE_GPS)
#define VIDEO_E60_FW_SHARED_SIZE_DLY		(32*1024)
#define VIDEO_E60_FW_SHARED_OFST_FPP		(VIDEO_E60_FW_SHARED_OFST_DLY+VIDEO_E60_FW_SHARED_SIZE_DLY)
#define VIDEO_E60_FW_SHARED_SIZE_FPP		(1*1024*1024)
#define VIDEO_E60_FW_SHARED_OFST_FPP_DNN	(VIDEO_E60_FW_SHARED_OFST_FPP+(32*1024))

#if 0
#define VIDEO_E60_MEM_SIZE_OF_FRAME_PREW      ( 71 * 1024 * 1024)
#define VIDEO_E60_MEM_SIZE_OF_FRAME_DE_M15A   (149 * 1024 * 1024) // 149MB ,  2.0GB DDR
#define VIDEO_E60_MEM_SIZE_OF_FRAME_DE_20GB   ( 93 * 1024 * 1024) //  93MB ,  2.0GB DDR
//#define VIDEO_E60_MEM_SIZE_OF_FRAME_DE_20GB   ( 72 * 1024 * 1024) //  72MB ,  2.0GB DDR
#define VIDEO_E60_MEM_SIZE_OF_FRAME_DE_15GB   (139 * 1024 * 1024) // 139MB ,  1.5GB DDR
#define VIDEO_E60_MEM_SIZE_OF_FRAME_DE_NODEJ  ( 90 * 1024 * 1024) //  90MB ,  120Hz model with F16
#define VIDEO_E60_MEM_SIZE_OF_FRAME_DELAY     ( 40 * 1024 * 1024) // Additional delay for BT speaker
#define VIDEO_E60_MEM_SIZE_OF_FRAME_HDRFB     ( 90 * 1024 * 1024) //  90MB ,  2.0GB DDR

#define VIDEO_E60_MEM_SIZE_OF_FRAME_DE_M16A_BT     (VIDEO_E60_MEM_SIZE_OF_FRAME_DE_M15A + VIDEO_E60_MEM_SIZE_OF_FRAME_DELAY)
#define VIDEO_E60_MEM_SIZE_OF_FRAME_DE_15GB_BT     (VIDEO_E60_MEM_SIZE_OF_FRAME_DE_15GB + VIDEO_E60_MEM_SIZE_OF_FRAME_DELAY)
#define VIDEO_E60_MEM_SIZE_OF_FRAME_DE_20GB_HDRFB  (VIDEO_E60_MEM_SIZE_OF_FRAME_DE_20GB + VIDEO_E60_MEM_SIZE_OF_FRAME_HDRFB)
#define VIDEO_E60_MEM_SIZE_OF_FRAME_DE_NODEJ_BT    (VIDEO_E60_MEM_SIZE_OF_FRAME_DE_NODEJ + VIDEO_E60_MEM_SIZE_OF_FRAME_DELAY)
#endif

// DDR0
//#define VIDEO_E60_MEM_SIZE_OF_FRAME_PREW      (36 * 1024 * 1024) // 28MB(PREW) + 3MB(SUB) + 8MB(GSC0_Y)
#define VIDEO_E60_MEM_SIZE_OF_FRAME_PREW      (72 * 1024 * 1024) // 64MB(PREW) + 3MB(SUB) + 8MB(GSC0_Y)  !!! Test for HDMI Dolby HDR W/A
#define VIDEO_E60_MEM_SIZE_OF_FRAME_PREW_C0   (58 * 1024 * 1024)
#define VIDEO_E60_MEM_SIZE_OF_FRAME_PREW_15GB (28 * 1024 * 1024) // 25MB(PREW) + 3MB(SUB)

// DDR1
#define VIDEO_E60_MEM_SIZE_OF_FRAME_DE       (272 * 1024 * 1024) // 271 MB(frame+frc) + 1MB
//#define VIDEO_E60_MEM_SIZE_OF_FRAME_DE_C0    (216 * 1024 * 1024) // 216 MB(frame+frc)
#define VIDEO_E60_MEM_SIZE_OF_FRAME_DE_C0    (300 * 1024 * 1024) // 216 MB(frame+frc)
#define VIDEO_E60_MEM_SIZE_OF_FRAME_DE_15GB  (163 * 1024 * 1024) // 162 MB(frame+frc) + 1MB

// TBD (on DDR1)
#define VIDEO_E60_MEM_SIZE_OF_FRAME_DELAY    (40 * 1024 * 1024)  // Additional delay for BT speaker
#define VIDEO_E60_MEM_SIZE_OF_VT_2K          ( 9 * 1024 * 1024)  // 9 MB
#define VIDEO_E60_MEM_SIZE_OF_VT_4K          (40 * 1024 * 1024)  // 40 MB(3x12MB + 4MB)
#define VIDEO_E60_MEM_SIZE_OF_VT_2K_C0       (15 * 1024 * 1024)  // 15 MB
#define VIDEO_E60_MEM_SIZE_OF_VT_4K_C0       (60 * 1024 * 1024)  // 60 MB(5x12MB)

#define __DOLBY_NEW_ARCH_IN_E60__

#define VIDEO_E60_HDR_IPC_MEM_SIZE	3*1024*1024 //256KB
#define VIDEO_E60_HDR_IPC_MEM_SIZE_C0        3*1024*1024 //3MB

// E60 map from SICDTV-6289
#define E60_DE_MEM_SIZE_PREW_M0 (34 * 1024 * 1024) // AVTASK-343:0 -> 64 -> 65 -> 17 -> 34
#define E60_PREW_VDEC_SHARED_POOL_SIZE (550*1024*1024)

#define E60_DE_MEM_SIZE_FRM_M1  (222 * 1024 * 1024) // AVTASK-343:214 -> 355 -> 396 -> 204 -> 219 -> 222
#define E60_DE_MEM_SIZE_FRM_M2  (329 * 1024 * 1024) // AVTASK-343:210 -> 299 -> 355 -> 323 -> 329

#define E60_DE_MEM_SIZE_FRM_M1_EXT  (124 * 1024 * 1024) // AVTASK-516:222 -> 124
#define E60_DE_MEM_SIZE_FRM_M2_EXT  (133 * 1024 * 1024) // AVTASK-516:329 -> 133

#define E60_DE_MEM_SIZE_BT_M0     ( 0 * 1024 * 1024) // AVTASK-343:0 -> 20 -> 0
#define E60_DE_MEM_SIZE_BT_M1     ( 0 * 1024 * 1024) // AVTASK-343:0 -> 20 -> 0

#define E60_DE_MEM_SIZE_VT_M1_GAV (  8 * 1024 * 1024) // 4k 1buf + gps(27MB) C, GAV:Y(M2 16MB),C(M1 8MB)(AVTASK-343)
#define E60_DE_MEM_SIZE_VT_M2_GAV ( 16 * 1024 * 1024) // 3 buffer            Y, GAV:Y(M2 16MB),C(M1 8MB)(AVTASK-343)
#define E60_DE_MEM_SIZE_VT_M1_VTG (  4 * 1024 * 1024) // 4k 420  C,          VTG:M2(8MB),M1(4MB)(AVTASK-343)
#define E60_DE_MEM_SIZE_VT_M2_VTG (  8 * 1024 * 1024) // 4k 420  Y 1 buffer, VTG:M2(8MB),M1(4MB)(AVTASK-343)

//#undef __DOLBY_NEW_ARCH_IN_E60__
/*----------------------------------------------------------------------------------------
 *   Macro Definitions
 *---------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------
 *   Type Definitions
 *---------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------
 *   External Function Prototype Declarations
 *---------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------
 *   External Variables
 *---------------------------------------------------------------------------------------*/
extern UINT32 g_FwBase_E60;

#endif   /* ----- #ifndef DE_CFG_E60_INC  ----- */
/**  @} */
