/*
	SIC LABORATORY, LG ELECTRONICS INC., SEOUL, KOREA
	Copyright(c) 2013 by LG Electronics Inc.

	This program is free software; you can redistribute it and/or 
	modify it under the terms of the GNU General Public License
	version 2 as published by the Free Software Foundation.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
	GNU General Public License for more details.
*/ 



/** @file 
 *
 *  driver interface header for afe device. ( used only within kdriver )
 *	afe device will teach you how to make device driver with new platform.
 *
 *  @author		wonsik.do (wonsik.do@lge.com)
 *  @version	1.0 
 *  @date		2019.06.24
 *
 *  @addtogroup lg1150_afe
 *	@{
 */

#ifndef	_HDMICEC_DRV_H_
#define	_HDMICEC_DRV_H_

/*----------------------------------------------------------------------------------------
	Control Constants
----------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------
    File Inclusions
----------------------------------------------------------------------------------------*/

#ifdef	__cplusplus
extern "C"
{
#endif /* __cplusplus */

/*----------------------------------------------------------------------------------------
	Constant Definitions
----------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------
	Macro Definitions
----------------------------------------------------------------------------------------*/
/* CEC */
#define DW_HDMI_MAX_ADDRS	4
#define DW_HDMI_MAX_RETRIES	3

/* id_cec Registers */
#define GLOBAL_SWRESET_REQUEST		0x0020
#define GLOBAL_SWENABLE				0x0024
#define HDMI_CEC_TX_CONTROL			0x2000
#define HDMI_CEC_TX_CONTROL			0x2000
#define HDMI_CEC_STATUS				0x2004
#define HDMI_CEC_CONFIG				0x2008
#define HDMI_CEC_ADDR				0x200C
#define HDMI_CEC_TX_COUNT			0x2020
#define HDMI_CEC_TX_DATA(x)			(0x2024 + ((x) * 4))
#define HDMI_CEC_TX_DATA_MAX_LEN		4
#define HDMI_CEC_RX_COUNT_STATUS		0x2040
#define HDMI_CEC_RX_DATA(x)			(0x2044 + ((x) * 4))
#define HDMI_CEC_LOCK_CONTROL			0x2054
#define HDMI_CEC_RXQUAL_BITTIME_CONFIG		0x2060
#define HDMI_CEC_RX_BITTIME_CONFIG		0x2064
#define HDMI_CEC_TX_BITTIME_CONFIG		0x2068

/* id_cec_interrupt Registers */
#define HDMI_CEC_INT_STATUS			0x5100
#define HDMI_CEC_INT_MASK_N			0x5104
#define HDMI_CEC_INT_CLEAR			0x5108
#define HDMI_CEC_INT_FORCE			0x510C

#define E60_INTERRUPT_GIC_BASE	32

#define E60_HDMICEC_IRQ_PORT1		(E60_INTERRUPT_GIC_BASE + 151)
#define E60_HDMICEC_IRQ_PORT2		(E60_INTERRUPT_GIC_BASE + 152)
#define E60_HDMICEC_IRQ_PORT3		(E60_INTERRUPT_GIC_BASE + 153)
#define E60_HDMICEC_IRQ_PORT4		(E60_INTERRUPT_GIC_BASE + 154)

#define O22_HDMICEC_IRQ_PORT1		(E60_INTERRUPT_GIC_BASE + 103)
#define O22_HDMICEC_IRQ_PORT2		(E60_INTERRUPT_GIC_BASE + 104)
#define O22_HDMICEC_IRQ_PORT3		(E60_INTERRUPT_GIC_BASE + 107)
#define O22_HDMICEC_IRQ_PORT4		(E60_INTERRUPT_GIC_BASE + 110)

#define M23_HDMICEC_IRQ_PORT1		(E60_INTERRUPT_GIC_BASE + 119)
#define M23_HDMICEC_IRQ_PORT2		(E60_INTERRUPT_GIC_BASE + 122)
#define M23_HDMICEC_IRQ_PORT3		(E60_INTERRUPT_GIC_BASE + 125)
#define M23_HDMICEC_IRQ_PORT4		(E60_INTERRUPT_GIC_BASE + 128)

#define O24_HDMICEC_IRQ_PORT1		(E60_INTERRUPT_GIC_BASE + 142)
#define O24_HDMICEC_IRQ_PORT2		(E60_INTERRUPT_GIC_BASE + 145)
#define O24_HDMICEC_IRQ_PORT3		(E60_INTERRUPT_GIC_BASE + 148)
#define O24_HDMICEC_IRQ_PORT4		(E60_INTERRUPT_GIC_BASE + 151)

#define O26_HDMICEC_IRQ_PORT1		(E60_INTERRUPT_GIC_BASE + 150)
#define O26_HDMICEC_IRQ_PORT2		(E60_INTERRUPT_GIC_BASE + 153)
#define O26_HDMICEC_IRQ_PORT3		(E60_INTERRUPT_GIC_BASE + 156)
#define O26_HDMICEC_IRQ_PORT4		(E60_INTERRUPT_GIC_BASE + 159)
/*----------------------------------------------------------------------------------------
    Type Definitions
----------------------------------------------------------------------------------------*/
enum {
/* --- id_mainunit --- */
	/* CORE_ID field values */
	HDMI_CORE_ID_VALUE = 0x48515258,
	/* CONFIG_REG field values */
	HDMI_CONFIG_REG_PHY_EXTERNAL = BIT(24),
	HDMI_CONFIG_REG_VESA_DSC = BIT(13),
	HDMI_CONFIG_REG_CEC = BIT(12),
	HDMI_CONFIG_REG_HDCP22_INTERFACE = BIT(6),
	HDMI_CONFIG_REG_HDCP14_EXTERNAL_DKSET = BIT(5),
	HDMI_CONFIG_REG_HDCP14_INTERNAL_DKSET = BIT(4),
	HDMI_CONFIG_REG_AUDIO_TRIPLE_INTERFACE = BIT(0),
/* --- id_reset_manager --- */
	/* GLOBAL_SWRESET_REQUEST field values */
	HDMI_GLOBAL_SWRESET_REQUEST_APB = BIT(17),
	HDMI_GLOBAL_SWRESET_REQUEST_CEC = BIT(16),
	HDMI_GLOBAL_SWRESET_REQUEST_CEC_OFFSET =16,
	HDMI_GLOBAL_SWRESET_REQUEST_DATAPATH = BIT(12),
	HDMI_GLOBAL_SWRESET_REQUEST_PKTFIFO = BIT(11),
	HDMI_GLOBAL_SWRESET_REQUEST_HDCP = BIT(10),
	HDMI_GLOBAL_SWRESET_REQUEST_AUDIO = BIT(9),
	HDMI_GLOBAL_SWRESET_REQUEST_AVPUNIT = BIT(8),
	HDMI_GLOBAL_SWRESET_REQUEST_MAIN = BIT(0),
/* --- id_timer_base --- */
	/* GLOBAL_TIMER_REF_BASE field values */
	HDMI_GLOBAL_TIMER_REF_BASE_MASK = GENMASK(28,0),
/* --- id_pmu --- */
/* --- id_cmu --- */
	/* CORE_CONFIG field values */
	HDMI_CORE_CONFIG_HPD_MASK = GENMASK(3,0),
	HDMI_CORE_CONFIG_HPD_OFFSET = 0,
	HDMI_CORE_CONFIG_HPD_D = BIT(3),
	HDMI_CORE_CONFIG_HPD_C = BIT(2),
	HDMI_CORE_CONFIG_HPD_B = BIT(1),
	HDMI_CORE_CONFIG_HPD_A = BIT(0),
	/* CMU_STATUS field values */
	HDMI_CMU_STATUS_TIMER_BASE_LOCKED = BIT(28),
	HDMI_CMU_STATUS_TMDSQP_CK_OFF = BIT(5),
	HDMI_CMU_STATUS_TMDSQP_CK_LOCKED = BIT(4),
	HDMI_CMU_STATUS_AUDIO_CK_OFF = BIT(1),
	HDMI_CMU_STATUS_AUDIO_CK_LOCKED = BIT(0),
/* --- id_phy_logic --- */
	/* PHY_CONFIG field values */
	HDMI_PHY_CONFIG_TMDS_CLOCK_RATIO_MASK = BIT(16),
	HDMI_PHY_CONFIG_TMDS_CLOCK_RATIO_OFFSET = 16,
	HDMI_PHY_CONFIG_RXDATA_WIDTH_MASK = BIT(15),
	HDMI_PHY_CONFIG_RXDATA_WIDTH_OFFSET = 15,
	HDMI_PHY_CONFIG_REFFREQ_SEL_MASK = GENMASK(11,9),
	HDMI_PHY_CONFIG_REFFREQ_SEL_OFFSET = 9,
	HDMI_PHY_CONFIG_HDMI_DISABLE_MASK = BIT(8),
	HDMI_PHY_CONFIG_HDMI_DISABLE_OFFSET = 8,
	HDMI_PHY_CONFIG_SVSRET_MODEZ_MASK = BIT(6),
	HDMI_PHY_CONFIG_SVSRET_MODEZ_OFFSET = 6,
	HDMI_PHY_CONFIG_CFGCLK_FREQ_MASK = GENMASK(5,4),
	HDMI_PHY_CONFIG_CFGCLK_FREQ_OFFSET = 4,
	HDMI_PHY_CONFIG_PORT_SELECT_MASK = GENMASK(3,2),
	HDMI_PHY_CONFIG_PORT_SELECT_OFFSET = 2,
	HDMI_PHY_CONFIG_PDDQ_MASK = BIT(1),
	HDMI_PHY_CONFIG_PDDQ_OFFSET = 1,
	HDMI_PHY_CONFIG_RESET_MASK = BIT(0),
	HDMI_PHY_CONFIG_RESET_OFFSET = 0,
	/* PHY_STATUS field values */
	HDMI_PHY_STATUS_HDMI_DISABLE_ACK = BIT(1),
	HDMI_PHY_STATUS_PDDQ_ACK = BIT(0),
	/* PHY_JTAG_CONFIG field values */
	HDMI_PHY_JTAG_CONFIG_EARC_TRST_N_MASK = BIT(4),
	HDMI_PHY_JTAG_CONFIG_EARC_TRST_N_OFFSET = 4,
	HDMI_PHY_JTAG_CONFIG_TRST_N_MASK = BIT(0),
	HDMI_PHY_JTAG_CONFIG_TRST_N_OFFSET = 0,
	/* PHY_JTAG_TAP_TCLK field values */
	HDMI_PHY_JTAG_TAP_EARC_TCLK_MASK = BIT(4),
	HDMI_PHY_JTAG_TAP_EARC_TCLK_OFFSET = 4,
	HDMI_PHY_JTAG_TAP_TCLK_MASK = BIT(0),
	HDMI_PHY_JTAG_TAP_TCLK_OFFSET = 0,
	/* PHY_JTAG_TAP_IN field values */
	HDMI_PHY_JTAG_TAP_IN_EARC_TMS = BIT(12),
	HDMI_PHY_JTAG_TAP_IN_EARC_TDI = BIT(8),
	HDMI_PHY_JTAG_TAP_IN_TMS = BIT(4),
	HDMI_PHY_JTAG_TAP_IN_TDI = BIT(0),
	/* PHY_JTAG_TAP_OUT field values */
	HDMI_PHY_JTAG_TAP_OUT_EARC_TDO_EN = BIT(12),
	HDMI_PHY_JTAG_TAP_OUT_EARC_TDO = BIT(8),
	HDMI_PHY_JTAG_TAP_OUT_TDO_EN = BIT(4),
	HDMI_PHY_JTAG_TAP_OUT_TDO = BIT(0),
/* --- id_mhl_cdsense_status --- */
	/* MAINUNIT_STATUS field values */
	HDMI_MAINUNIT_STATUS_TMDSVALID_STABLE = BIT(1),
	HDMI_MAINUNIT_STATUS_AUDPLL_LOCK_STABLE = BIT(0),
/* --- id_i2c_slave --- */
	/* I2C_SLAVE_CONFIG0 field values */
	HDMI_I2C_SLAVE_CONFIG0_H22_SEL_ADDR_MASK = GENMASK(19,12),
	HDMI_I2C_SLAVE_CONFIG0_H22_SEL_ADDR_OFFSET = 12,
	HDMI_I2C_SLAVE_CONFIG0_SPIKE_SUPPR_MASK = GENMASK(9,8),
	HDMI_I2C_SLAVE_CONFIG0_SPIKE_SUPPR_OFFSET = 8,
	HDMI_I2C_SLAVE_CONFIG0_TIMEOUT_EN_MASK = BIT(4),
	HDMI_I2C_SLAVE_CONFIG0_TIMEOUT_EN_OFFSET = 4,
	HDMI_I2C_SLAVE_CONFIG0_TIMEOUT_CNT_MASK = GENMASK(2,0),
	HDMI_I2C_SLAVE_CONFIG0_TIMEOUT_CNT_OFFSET = 0,
	/* I2C_SLAVE_CONFIG1 field values */
	HDMI_I2C_SLAVE_CONFIG1_SDA_OUT_HOLD_VALUE_MASK = GENMASK(15,8),
	HDMI_I2C_SLAVE_CONFIG1_SDA_OUT_HOLD_VALUE_OFFSET = 8,
	HDMI_I2C_SLAVE_CONFIG1_SDA_IN_HOLD_VALUE_MASK = GENMASK(7,0),
	HDMI_I2C_SLAVE_CONFIG1_SDA_IN_HOLD_VALUE_OFFSET = 0,
/* --- id_descrambler ---*/
	HDMI_DESCRAND_STATUS_FRL_SYNC = BIT(8),
/* --- id_deframer --- */
	/* DEFRAMER_CONFIG0 field values */
	HDMI_DEFRAMER_CONFIG0_VS_CNT_THR_MASK = GENMASK(27,20),
	HDMI_DEFRAMER_CONFIG0_VS_CNT_THR_OFFSET = 20,
	HDMI_DEFRAMER_CONFIG0_HS_POL_MASK = GENMASK(19,18),
	HDMI_DEFRAMER_CONFIG0_HS_POL_OFFSET = 18,
	HDMI_DEFRAMER_CONFIG0_VS_POL_MASK = GENMASK(17,16),
	HDMI_DEFRAMER_CONFIG0_VS_POL_OFFSET = 16,
	HDMI_DEFRAMER_CONFIG0_CTL_SPIKEFILTER_EN_MASK = BIT(12),
	HDMI_DEFRAMER_CONFIG0_CTL_SPIKEFILTER_EN_OFFSET = 12,
	HDMI_DEFRAMER_CONFIG0_VS_REMAPFILTER_EN_MASK = BIT(8),
	HDMI_DEFRAMER_CONFIG0_VS_REMAPFILTER_EN_OFFSET = 8,
	HDMI_DEFRAMER_CONFIG0_HS_FILTER_ORDER_MASK = GENMASK(3,2),
	HDMI_DEFRAMER_CONFIG0_HS_FILTER_ORDER_OFFSET = 2,
	HDMI_DEFRAMER_CONFIG0_VS_FILTER_ORDER_MASK = GENMASK(1,0),
	HDMI_DEFRAMER_CONFIG0_VS_FILTER_ORDER_OFFSET = 0,
	/* DEFRAMER_CONFIG1 field values */
	HDMI_DEFRAMER_CONFIG1_HDMI2DVI_THR_MASK = GENMASK(26,24),
	HDMI_DEFRAMER_CONFIG1_HDMI2DVI_THR_OFFSET = 24,
	HDMI_DEFRAMER_CONFIG1_DVI2HDMI_THR_MASK = GENMASK(22,20),
	HDMI_DEFRAMER_CONFIG1_DVI2HDMI_THR_OFFSET = 20,
	HDMI_DEFRAMER_CONFIG1_OPMODE_HDMI_MASK = GENMASK(17,16),
	HDMI_DEFRAMER_CONFIG1_OPMODE_HDMI_OFFSET = 16,
		/* DEFRAMER_CONFIG1_OPMODE_HDMI possible values */
		HDMI_DEFRAMER_CONFIG1_OPMODE_AUTO = 0x0,
		HDMI_DEFRAMER_CONFIG1_OPMODE_DVI = 0x1,
		HDMI_DEFRAMER_CONFIG1_OPMODE_HDMI = 0x2,
	HDMI_DEFRAMER_CONFIG1_GB_ERR_THR_MASK = GENMASK(15,8),
	HDMI_DEFRAMER_CONFIG1_GB_ERR_THR_OFFSET = 8,
	HDMI_DEFRAMER_CONFIG1_LAST_FRAME_GB_CHECK_MASK = GENMASK(7,4),
	HDMI_DEFRAMER_CONFIG1_LAST_FRAME_GB_CHECK_OFFSET = 4,
	HDMI_DEFRAMER_CONFIG1_NUM_PREAMBLE_LOCK_MASK = GENMASK(3,0),
	HDMI_DEFRAMER_CONFIG1_NUM_PREAMBLE_LOCK_OFFSET = 0,
	/* DEFRAMER_STATUS field values */
	HDMI_DEFRAMER_STATUS_OPMODE_MASK = GENMASK(6,4),
	HDMI_DEFRAMER_STATUS_OPMODE_OFFSET = 4,
	HDMI_DEFRAMER_STATUS_AUTOHDMIDVI = BIT(0),
/* --- id_hdcp14 --- */
	/* HDMI_HDCP14_CONFIG field values */
	HDMI_HDCP14_CONFIG_REPEATER_MASK = BIT(28),
	HDMI_HDCP14_CONFIG_REPEATER_OFFSET = 28,
	HDMI_HDCP14_CONFIG_FASTREAUTH_MASK = BIT(27),
	HDMI_HDCP14_CONFIG_FASTREAUTH_OFFSET = 27,
	HDMI_HDCP14_CONFIG_FEATURES_1DOT1_MASK = BIT(26),
	HDMI_HDCP14_CONFIG_FEATURES_1DOT1_OFFSET = 26,
	HDMI_HDCP14_CONFIG_FASTI2C_MASK = BIT(25),
	HDMI_HDCP14_CONFIG_FASTI2C_OFFSET = 25,
	HDMI_HDCP14_CONFIG_HDMI_RSVD_MASK = BIT(24),
	HDMI_HDCP14_CONFIG_HDMI_RSVD_OFFSET = 24,
	HDMI_HDCP14_CONFIG_EESS_CTL_THR_MASK = GENMASK(19,16),
	HDMI_HDCP14_CONFIG_EESS_CTL_THR_OFFSET = 16,
	HDMI_HDCP14_CONFIG_OESS_CTL3_THR_MASK = GENMASK(11,8),
	HDMI_HDCP14_CONFIG_OESS_CTL3_THR_OFFSET = 8,
	HDMI_HDCP14_CONFIG_EESS_OESS_SEL_MASK = GENMASK(5,4),
	HDMI_HDCP14_CONFIG_EESS_OESS_SEL_OFFSET = 4,
	HDMI_HDCP14_CONFIG_KEY_DECRYPT_EN_MASK = BIT(0),
	HDMI_HDCP14_CONFIG_KEY_DECRYPT_EN_OFFSET = 0,
	/* HDMI_HDCP14_WOO_CONFIG field values */
	HDMI_HDCP14_WOO_CONFIG_END_MASK = GENMASK(25,16),
	HDMI_HDCP14_WOO_CONFIG_END_OFFSET = 16,
	HDMI_HDCP14_WOO_CONFIG_START_MASK = GENMASK(9,0),
	HDMI_HDCP14_WOO_CONFIG_START_OFFSET = 0,
	/* HDMI_HDCP14_KEY_SEED field values */
	HDMI_HDCP14_KEY_SEED_MASK = GENMASK(15,0),
	HDMI_HDCP14_KEY_SEED_OFFSET = 0,
	/* HDMI_HDCP14_KEY_STATUS field values */
	HDMI_HDCP14_KEY_STATUS_KEY_WR_OK = BIT(8),
	HDMI_HDCP14_KEY_STATUS_KEY_INDEX = GENMASK(5,0),
	/* HDMI_HDCP14_STATUS field values */
	HDMI_HDCP14_STATUS_DECRYPT_ON = BIT(8),
	HDMI_HDCP14_STATUS_AUTH_CURSTATE_MASK = GENMASK(1,0),
	HDMI_HDCP14_STATUS_AUTH_CURSTATE_OFFSET = 0,
/* --- id_hdcp22 --- */
	/* HDCP22_CONFIG field values */
	HDMI_HDCP22_CONFIG_CD_OVR_VALUE_MASK = GENMASK(23,20),
	HDMI_HDCP22_CONFIG_CD_OVR_VALUE_OFFSET = 20,
	HDMI_HDCP22_CONFIG_CD_OVR_EN_MASK = BIT(16),
	HDMI_HDCP22_CONFIG_CD_OVR_EN_OFFSET = 16,
	HDMI_HDCP22_CONFIG_HPD_MASK = BIT(12),
	HDMI_HDCP22_CONFIG_HPD_OFFSET = 12,
	HDMI_HDCP22_CONFIG_PKT_ERR_OVR_VALUE_MASK = BIT(9),
	HDMI_HDCP22_CONFIG_PKT_ERR_OVR_VALUE_OFFSET = 9,
	HDMI_HDCP22_CONFIG_PKT_ERR_OVR_EN_MASK = BIT(8),
	HDMI_HDCP22_CONFIG_PKT_ERR_OVR_EN_OFFSET = 8,
	HDMI_HDCP22_CONFIG_AVMUTE_OVR_VALUE_MASK = BIT(5),
	HDMI_HDCP22_CONFIG_AVMUTE_OVR_VALUE_OFFSET = 5,
	HDMI_HDCP22_CONFIG_AVMUTE_OVR_EN_MASK = BIT(4),
	HDMI_HDCP22_CONFIG_AVMUTE_OVR_EN_OFFSET = 4,
	HDMI_HDCP22_CONFIG_SWITCH_OVR_VALUE_MASK = BIT(2),
	HDMI_HDCP22_CONFIG_SWITCH_OVR_VALUE_OFFSET = 2,
	HDMI_HDCP22_CONFIG_SWITCH_OVR_EN_MASK = BIT(1),
	HDMI_HDCP22_CONFIG_SWITCH_OVR_EN_OFFSET = 1,
	HDMI_HDCP22_CONFIG_SWITCH_LCK_MASK = BIT(0),
	HDMI_HDCP22_CONFIG_SWITCH_LCK_OFFSET = 0,
	/* HDCP22_STATUS field values */
	HDMI_HDCP22_STATUS_CD_MASK = GENMASK(15,12),
	HDMI_HDCP22_STATUS_CD_OFFSET = 12,
	HDMI_HDCP22_STATUS_AVMUTE = BIT(8),
	HDMI_HDCP22_STATUS_SWITCH_LCK = BIT(7),
	HDMI_HDCP22_STATUS_OVR_EN = BIT(6),
	HDMI_HDCP22_STATUS_OVR_VAL = BIT(5),
	HDMI_HDCP22_STATUS_TYPE_SEL = BIT(4),
	HDMI_HDCP22_STATUS_IN_AVMUTE = BIT(1),
	HDMI_HDCP22_STATUS_DECRYPTED = BIT(0),
/* --- id_video_processor --- */
	/* VIDEO_CONFIG2 field values */
	HDMI_VIDEO_CONFIG2_HSYNC_POL_OVR_EN_MASK = BIT(16),
	HDMI_VIDEO_CONFIG2_HSYNC_POL_OVR_EN_OFFSET = 16,
	HDMI_VIDEO_CONFIG2_HSYNC_POL_OVR_MASK = BIT(17),
	HDMI_VIDEO_CONFIG2_HSYNC_POL_OVR_OFFSET = 17,
	HDMI_VIDEO_CONFIG2_VSYNC_POL_OVR_EN_MASK = BIT(18),
	HDMI_VIDEO_CONFIG2_VSYNC_POL_OVR_EN_OFFSET = 18,
	HDMI_VIDEO_CONFIG2_VSYNC_POL_OVR_MASK = BIT(19),
	HDMI_VIDEO_CONFIG2_VSYNC_POL_OVR_OFFSET = 19,
	/* VIDEO_STATUS field values */
	HDMI_VIDEO_STATUS_PP_DIFF_CNT_MASK = GENMASK(15,8),
	HDMI_VIDEO_STATUS_PP_DIFF_CNT_OFFSET = 8,
	HDMI_VIDEO_STATUS_PP_CURRENT_MASK = GENMASK(6,4),
	HDMI_VIDEO_STATUS_PP_CURRENT_OFFSET = 4,
	HDMI_VIDEO_STATUS_CD_CURRENT_MASK = GENMASK(3,0),
	HDMI_VIDEO_STATUS_CD_CURRENT_OFFSET = 0,
/* --- id_audio --- */
	/* AUDIO_FIFO_CONFIG field values */
	HDMI_AUDIO_FIFO_CONFIG_BYPASS_EN_MASK = BIT(2),
	HDMI_AUDIO_FIFO_CONFIG_BYPASS_EN_OFFSET = 2,
	HDMI_AUDIO_FIFO_CONFIG_FILL_STOP_MASK = BIT(1),
	HDMI_AUDIO_FIFO_CONFIG_FILL_STOP_OFFSET = 1,
	HDMI_AUDIO_FIFO_CONFIG_FILL_RESTART_MASK = BIT(0),
	HDMI_AUDIO_FIFO_CONFIG_FILL_RESTART_OFFSET = 0,
	/* AUDIO_FIFO_CONTROL field values */
	HDMI_AUDIO_FIFO_CONTROL_CLR_MAX_P_MASK = BIT(2),
	HDMI_AUDIO_FIFO_CONTROL_CLR_MAX_P_OFFSET = 2,
	HDMI_AUDIO_FIFO_CONTROL_CLR_MIN_P_MASK = BIT(1),
	HDMI_AUDIO_FIFO_CONTROL_CLR_MIN_P_OFFSET = 1,
	HDMI_AUDIO_FIFO_CONTROL_INIT_P_MASK = BIT(0),
	HDMI_AUDIO_FIFO_CONTROL_INIT_P_OFFSET = 0,
	/* AUDIO_FIFO_STATUS1 field values */
	HDMI_AUDIO_FIFO_STATUS1_FILL_STATE_MAX_MASK = GENMASK(31,16),
	HDMI_AUDIO_FIFO_STATUS1_FILL_STATE_MAX_OFFSET = 16,
	HDMI_AUDIO_FIFO_STATUS1_FILL_STATE_MIN_MASK = GENMASK(15,0),
	HDMI_AUDIO_FIFO_STATUS1_FILL_STATE_MIN_OFFSET = 0,
	/* AUDIO_FIFO_STATUS2 field values */
	HDMI_AUDIO_FIFO_STATUS2_UNDERFLOW = BIT(25),
	HDMI_AUDIO_FIFO_STATUS2_OVERFLOW = BIT(24),
	HDMI_AUDIO_FIFO_STATUS2_FILL_STATE_MASK = GENMASK(15,0),
	HDMI_AUDIO_FIFO_STATUS2_FILL_STATE_OFFSET = 0,
/* --- id_audio_processor --- */
	/* AUDIO_PROC_CONFIG0 field values */
	HDMI_AUDIO_PROC_CONFIG0_SPEAKER_ALLOC_OVR_VALUE_MASK = GENMASK(27,20),
	HDMI_AUDIO_PROC_CONFIG0_SPEAKER_ALLOC_OVR_VALUE_OFFSET = 20,
	HDMI_AUDIO_PROC_CONFIG0_SPEAKER_ALLOC_OVR_EN_MASK = BIT(16),
	HDMI_AUDIO_PROC_CONFIG0_SPEAKER_ALLOC_OVR_EN_OFFSET = 16,
	HDMI_AUDIO_PROC_CONFIG0_MUTE_OVR_VALUE_MASK = BIT(13),
	HDMI_AUDIO_PROC_CONFIG0_MUTE_OVR_VALUE_OFFSET = 13,
	HDMI_AUDIO_PROC_CONFIG0_MUTE_OVR_EN_MASK = BIT(12),
	HDMI_AUDIO_PROC_CONFIG0_MUTE_OVR_EN_OFFSET = 12,
	HDMI_AUDIO_PROC_CONFIG0_I2S_BPCUV_EN_MASK = BIT(4),
	HDMI_AUDIO_PROC_CONFIG0_I2S_BPCUV_EN_OFFSET = 4,
	HDMI_AUDIO_PROC_CONFIG0_SPDIF_EN_MASK = BIT(2),
	HDMI_AUDIO_PROC_CONFIG0_SPDIF_EN_OFFSET = 2,
	HDMI_AUDIO_PROC_CONFIG0_I2S_EN_MASK = BIT(1),
	HDMI_AUDIO_PROC_CONFIG0_I2S_EN_OFFSET = 1,
	HDMI_AUDIO_PROC_CONFIG0_PAO_EN_MASK = BIT(0),
	HDMI_AUDIO_PROC_CONFIG0_PAO_EN_OFFSET = 0,
	/* AUDIO_PROC_CONFIG1 field values */
	HDMI_AUDIO_PROC_CONFIG1_LAYOUT_OVR_VALUE_MASK = BIT(1),
	HDMI_AUDIO_PROC_CONFIG1_LAYOUT_OVR_VALUE_OFFSET = 1,
	HDMI_AUDIO_PROC_CONFIG1_LAYOUT_OVR_EN_MASK = BIT(0),
	HDMI_AUDIO_PROC_CONFIG1_LAYOUT_OVR_EN_OFFSET = 0,
	/* AUDIO_PROC_CONFIG2 field values */
	HDMI_AUDIO_PROC_CONFIG2_AUD_FMT_CHG_MUTEMASK_N_MASK = BIT(1),
	HDMI_AUDIO_PROC_CONFIG2_AUD_FMT_CHG_MUTEMASK_N_OFFSET = 1,
	/* AUDIO_PROC_STATUS1 field values */
	HDMI_AUDIO_PROC_STATUS1_SPEAKER_ALLOC_MASK = GENMASK(23,16),
	HDMI_AUDIO_PROC_STATUS1_SPEAKER_ALLOC_OFFSET = 16,
	HDMI_AUDIO_PROC_STATUS1_MUTE = BIT(8),
	HDMI_AUDIO_PROC_STATUS1_LAYOUT_MASK = BIT(3),
	HDMI_AUDIO_PROC_STATUS1_LAYOUT_OFFSET = 3,
	HDMI_AUDIO_PROC_STATUS1_FMT_MASK = GENMASK(2,0),
	HDMI_AUDIO_PROC_STATUS1_FMT_OFFSET = 0,
	/* AUDIO_PROC_STATUS2 field values */
	HDMI_AUDIO_PROC_STATUS2_SAMPLE_PRESENT_MASK = GENMASK(7,4),
	HDMI_AUDIO_PROC_STATUS2_SAMPLE_PRESENT_OFFSET = 4,
	HDMI_AUDIO_PROC_STATUS2_SAMPLE_FLAT_MASK = GENMASK(3,0),
	HDMI_AUDIO_PROC_STATUS2_SAMPLE_FLAT_OFFSET = 0,
/* --- id_scdc --- */
	/* SCDC_CONFIG field values */
	HDMI_SCDC_CONFIG_RR_IFFLAGS_ALREADYSET_MASK = BIT(5),
	HDMI_SCDC_CONFIG_RR_IFFLAGS_ALREADYSET_OFFSET = 5,
	HDMI_SCDC_CONFIG_HPDLOW_MASK = BIT(1),
	HDMI_SCDC_CONFIG_HPDLOW_OFFSET = 1,
	HDMI_SCDC_CONFIG_POWERPROVIDED_MASK = BIT(0),
	HDMI_SCDC_CONFIG_POWERPROVIDED_OFFSET = 0,
	/* SCDC_REGBANK_STATUS0 field values */
	HDMI_SCDC_REGBANK_STATUS0_FRL_START_STS = BIT(28),
	HDMI_SCDC_REGBANK_STATUS0_RSED_UPDATE = BIT(14),
	HDMI_SCDC_REGBANK_STATUS0_FLT_UPDATE = BIT(13),
	HDMI_SCDC_REGBANK_STATUS0_FRL_START = BIT(12),
	HDMI_SCDC_REGBANK_STATUS0_SOURCE_TEST_UPDATE = BIT(11),
	HDMI_SCDC_REGBANK_STATUS0_RRTEST = BIT(10),
	HDMI_SCDC_REGBANK_STATUS0_CEDUPDATE = BIT(9),
	HDMI_SCDC_REGBANK_STATUS0_STATUSUPDATE = BIT(8),
	HDMI_SCDC_REGBANK_STATUS0_SOURCEVERSION_MASK = GENMASK(7,0),
	HDMI_SCDC_REGBANK_STATUS0_SOURCEVERSION_OFFSET = 0,
	/* SCDC_REGBANK_STATUS1 field values */
	HDMI_SCDC_REGBANK_STATUS1_SCRAMB_STATUS = BIT(8),
	HDMI_SCDC_REGBANK_STATUS1_TMDSBITCLKRATIO = BIT(1),
	HDMI_SCDC_REGBANK_STATUS1_SCRAMB_EN = BIT(0),
	/* SCDC_REGBANK_STATUS2 field values */
	HDMI_SCDC_REGBANK_STATUS2_FFE_LEVELS_MASK = GENMASK(15, 12),
	HDMI_SCDC_REGBANK_STATUS2_FFE_LEVELS_OFFSET = 12,
	HDMI_SCDC_REGBANK_STATUS2_FRL_RATE_MASK = GENMASK(11, 8),
	HDMI_SCDC_REGBANK_STATUS2_FRL_RATE_OFFSET = 8,
	HDMI_SCDC_REGBANK_STATUS2_FLT_NO_RETRAIN = BIT(1),
	HDMI_SCDC_REGBANK_STATUS2_RRENABLE = BIT(0),
	/* SCDC_REGBANK_STATUS3 field values */
	HDMI_SCDC_REGBANK_STATUS3_FLT_LN3_LTP_REQ_MASK = GENMASK(31,28),
	HDMI_SCDC_REGBANK_STATUS3_FLT_LN3_LTP_REQ_OFFSET = 28,
	HDMI_SCDC_REGBANK_STATUS3_FLT_LN2_LTP_REQ_MASK = GENMASK(27,24),
	HDMI_SCDC_REGBANK_STATUS3_FLT_LN2_LTP_REQ_OFFSET = 24,
	HDMI_SCDC_REGBANK_STATUS3_FLT_LN1_LTP_REQ_MASK = GENMASK(23,20),
	HDMI_SCDC_REGBANK_STATUS3_FLT_LN1_LTP_REQ_OFFSET = 20,
	HDMI_SCDC_REGBANK_STATUS3_FLT_LN0_LTP_REQ_MASK = GENMASK(19,16),
	HDMI_SCDC_REGBANK_STATUS3_FLT_LN0_LTP_REQ_OFFSET = 16,
	HDMI_SCDC_REGBANK_STATUS3_FLT_READY = BIT(14),
	HDMI_SCDC_REGBANK_STATUS3_LN3LOCKED = BIT(12),
	HDMI_SCDC_REGBANK_STATUS3_LN2LOCKED = BIT(11),
	HDMI_SCDC_REGBANK_STATUS3_LN1LOCKED = BIT(10),
	HDMI_SCDC_REGBANK_STATUS3_LN0LOCKED = BIT(9),
	HDMI_SCDC_REGBANK_STATUS3_CH2LOCKED = BIT(3),
	HDMI_SCDC_REGBANK_STATUS3_CH1LOCKED = BIT(2),
	HDMI_SCDC_REGBANK_STATUS3_CH0LOCKED = BIT(1),
	HDMI_SCDC_REGBANK_STATUS3_CLOCKDETECTED = BIT(0),
	/* SCDC_REGBANK_STATUS4 field values */
	HDMI_SCDC_REGBANK_STATUS4_ERR_DET1_VALID = BIT(31),
	HDMI_SCDC_REGBANK_STATUS4_ERR_DET1_MASK = GENMASK(30,16),
	HDMI_SCDC_REGBANK_STATUS4_ERR_DET1_OFFSET = 16,
	HDMI_SCDC_REGBANK_STATUS4_ERR_DET0_VALID = BIT(15),
	HDMI_SCDC_REGBANK_STATUS4_ERR_DET0_MASK = GENMASK(14,0),
	HDMI_SCDC_REGBANK_STATUS4_ERR_DET0_OFFSET = 0,
	/* SCDC_REGBANK_STATUS5 field values */
	HDMI_SCDC_REGBANK_STATUS5_ERDET_LANE0_VALID = BIT(31),
	HDMI_SCDC_REGBANK_STATUS5_ERDET_LANE0_MASK = GENMASK(30,16),
	HDMI_SCDC_REGBANK_STATUS5_ERDET_LANE0_OFFSET = 16,
	HDMI_SCDC_REGBANK_STATUS5_ERR_DET2_VALID = BIT(15),
	HDMI_SCDC_REGBANK_STATUS5_ERR_DET2_MASK = GENMASK(14,0),
	HDMI_SCDC_REGBANK_STATUS5_ERR_DET2_OFFSET = 0,
	/* SCDC_REGBANK_STATUS6 field values */
	HDMI_SCDC_REGBANK_STATUS6_ERDET_LANE2_VALID = BIT(31),
	HDMI_SCDC_REGBANK_STATUS6_ERDET_LANE2_MASK = GENMASK(30,16),
	HDMI_SCDC_REGBANK_STATUS6_ERDET_LANE2_OFFSET = 16,
	HDMI_SCDC_REGBANK_STATUS6_ERDET_LANE1_VALID = BIT(15),
	HDMI_SCDC_REGBANK_STATUS6_ERDET_LANE1_MASK = GENMASK(14,0),
	HDMI_SCDC_REGBANK_STATUS6_ERDET_LANE1_OFFSET = 0,
	/* SCDC_REGBANK_STATUS7 field values */
	HDMI_SCDC_REGBANK_STATUS7_RSFEC_CERDET_VALID = BIT(31),
	HDMI_SCDC_REGBANK_STATUS7_RSFEC_CERDET_MASK = GENMASK(30,16),
	HDMI_SCDC_REGBANK_STATUS7_RSFEC_CERDET_OFFSET = 16,
	HDMI_SCDC_REGBANK_STATUS7_ERDET_LANE3_VALID = BIT(15),
	HDMI_SCDC_REGBANK_STATUS7_ERDET_LANE3_MASK = GENMASK(14,0),
	HDMI_SCDC_REGBANK_STATUS7_ERDET_LANE3_OFFSET = 0,
	/* SCDC_REGBANK_CONFIG0 field values */
	HDMI_SCDC_REGBANK_CONFIG0_SINKVERSION_QST_MASK = GENMASK(7,0),
	HDMI_SCDC_REGBANK_CONFIG0_SINKVERSION_QST_OFFSET = 0,
/* --- id_psvg --- */
	/* PSVG_CONFIG0 field values */
	HDMI_PSVG_CONFIG0_CONNECTION_SEL_QST_MASK = GENMASK(29,28),
	HDMI_PSVG_CONFIG0_CONNECTION_SEL_QST_OFFSET = 28,
	HDMI_PSVG_CONFIG0_COLORRANGE_QST_MASK = BIT(24),
	HDMI_PSVG_CONFIG0_COLORRANGE_QST_OFFSET = 24,
	HDMI_PSVG_CONFIG0_COLORDEPTH_QST_MASK = GENMASK(23,20),
	HDMI_PSVG_CONFIG0_COLORDEPTH_QST_OFFSET = 20,
	HDMI_PSVG_CONFIG0_PREPETITION_QST_MASK = GENMASK(19,16),
	HDMI_PSVG_CONFIG0_PREPETITION_QST_OFFSET = 16,
	HDMI_PSVG_CONFIG0_COLORIMETRY_QST_MASK = GENMASK(14,12),
	HDMI_PSVG_CONFIG0_COLORIMETRY_QST_OFFSET = 12,
	HDMI_PSVG_CONFIG0_VBLANKOSC_QST_MASK = BIT(9),
	HDMI_PSVG_CONFIG0_VBLANKOSC_QST_OFFSET = 9,
	HDMI_PSVG_CONFIG0_ILACE_QST_MASK = BIT(8),
	HDMI_PSVG_CONFIG0_ILACE_QST_OFFSET = 8,
	HDMI_PSVG_CONFIG0_VS_POL_QST_MASK = BIT(6),
	HDMI_PSVG_CONFIG0_VS_POL_QST_OFFSET = 6,
	HDMI_PSVG_CONFIG0_HS_POL_QST_MASK = BIT(5),
	HDMI_PSVG_CONFIG0_HS_POL_QST_OFFSET = 5,
	HDMI_PSVG_CONFIG0_DE_POL_QST_MASK = BIT(4),
	HDMI_PSVG_CONFIG0_DE_POL_QST_OFFSET = 4,
	HDMI_PSVG_CONFIG0_EN_MASK = BIT(0),
	HDMI_PSVG_CONFIG0_EN_OFFSET = 0,
	/* PSVG_CONFIG1 field values */
	HDMI_PSVG_CONFIG1_PATT_MODE_QST_MASK = GENMASK(17,16),
	HDMI_PSVG_CONFIG1_PATT_MODE_QST_OFFSET = 16,
	HDMI_PSVG_CONFIG1_3D_STRUCT_QST_MASK = GENMASK(7,4),
	HDMI_PSVG_CONFIG1_3D_STRUCT_QST_OFFSET = 4,
	HDMI_PSVG_CONFIG1_3D_FRAMESEQ_QST_MASK = BIT(1),
	HDMI_PSVG_CONFIG1_3D_FRAMESEQ_QST_OFFSET = 1,
	HDMI_PSVG_CONFIG1_3D_EN_QST_MASK = BIT(0),
	HDMI_PSVG_CONFIG1_3D_EN_QST_OFFSET = 0,
/* --- id_frl_ced --- */
	/* FRL_CED_DYN_STATUS1 field values */
	HDMI_FRL_CED_DYN_STATUS1_ERRCNT_LANE1_MASK = GENMASK(30,16),
	HDMI_FRL_CED_DYN_STATUS1_ERRCNT_LANE1_OFFSET = 16,
	HDMI_FRL_CED_DYN_STATUS1_ERRCNT_LANE0_MASK = GENMASK(14,0),
	HDMI_FRL_CED_DYN_STATUS1_ERRCNT_LANE0_OFFSET = 0,
	/* FRL_CED_DYN_STATUS2 field values */
	HDMI_FRL_CED_DYN_STATUS2_ERRCNT_LANE3_MASK = GENMASK(30,16),
	HDMI_FRL_CED_DYN_STATUS2_ERRCNT_LANE3_OFFSET = 16,
	HDMI_FRL_CED_DYN_STATUS2_ERRCNT_LANE2_MASK = GENMASK(14,0),
	HDMI_FRL_CED_DYN_STATUS2_ERRCNT_LANE2_OFFSET = 0,
/* --- id_packet_extractor --- */
	/* PKTEX_BCHERR_ACC_STATUS field values */
	HDMI_PKTEX_BCHERR_ACC_STATUS_AUDERR_MASK = GENMASK(31,16),
	HDMI_PKTEX_BCHERR_ACC_STATUS_AUDERR_OFFSET = 16,
	HDMI_PKTEX_BCHERR_ACC_STATUS_ERR_MASK = GENMASK(15,0),
	HDMI_PKTEX_BCHERR_ACC_STATUS_ERR_OFFSET = 0,
/* --- id_frl_unpacker --- */
	/* FRL_UNPACKER_STATUS field values */
	HDMI_FRL_UNPACKER_STATUS_TYPE_ERR_CNT_MASK = GENMASK(23,16),
	HDMI_FRL_UNPACKER_STATUS_TYPE_ERR_CNT_OFFSET = 16,
	HDMI_FRL_UNPACKER_STATUS_LENGTH_ERR_CNT_MASK = GENMASK(7,0),
	HDMI_FRL_UNPACKER_STATUS_LENGTH_ERR_CNT_OFFSET = 0,
/* --- id_packet_decoder --- */
	/* PKTDEC_ACR_CONFIG field values */
	HDMI_PKTDEC_ACR_CONFIG_DELTACTS_THR_MASK = GENMASK(6,4),
	HDMI_PKTDEC_ACR_CONFIG_DELTACTS_THR_OFFSET = 4,
	HDMI_PKTDEC_ACR_CONFIG_CTS_N_OVR_EN_MASK = BIT(0),
	HDMI_PKTDEC_ACR_CONFIG_CTS_N_OVR_EN_OFFSET = 0,
/* --- id_video_monitor --- */
	/* HDMI_VMON_CONTROL field values */
	HDMI_VMON_CONTROL_SOURCE_SEL_MASK = GENMASK(30,28),
	HDMI_VMON_CONTROL_SOURCE_SEL_OFFSET = 28,
	/* HDMI_VMON_STATUS1 field values */
	HDMI_VMON_STATUS1_HSYNCWIDTH_MASK = GENMASK(31,16),
	HDMI_VMON_STATUS1_HSYNCWIDTH_OFFSET = 16,
	HDMI_VMON_STATUS1_HFRONT_MASK = GENMASK(15,0),
	HDMI_VMON_STATUS1_HFRONT_OFFSET = 0,
	/* HDMI_VMON_STATUS2 field values */
	HDMI_VMON_STATUS2_HBLANK_MASK = GENMASK(31,16),
	HDMI_VMON_STATUS2_HBLANK_OFFSET = 16,
	HDMI_VMON_STATUS2_HBACK_MASK = GENMASK(15,0),
	HDMI_VMON_STATUS2_HBACK_OFFSET = 0,
	/* HDMI_VMON_STATUS3 field values */
	HDMI_VMON_STATUS3_HTOTAL_MASK = GENMASK(31,16),
	HDMI_VMON_STATUS3_HTOTAL_OFFSET = 16,
	HDMI_VMON_STATUS3_HACTIVE_MASK = GENMASK(15,0),
	HDMI_VMON_STATUS3_HACTIVE_OFFSET = 0,
	/* HDMI_VMON_STATUS4 field values */
	HDMI_VMON_STATUS4_VSYNCWIDTH_MASK = GENMASK(31,16),
	HDMI_VMON_STATUS4_VSYNCWIDTH_OFFSET = 16,
	HDMI_VMON_STATUS4_VFRONT_MASK = GENMASK(15,0),
	HDMI_VMON_STATUS4_VFRONT_OFFSET = 0,
	/* HDMI_VMON_STATUS5 field values */
	HDMI_VMON_STATUS5_VBLANK_MASK = GENMASK(31,16),
	HDMI_VMON_STATUS5_VBLANK_OFFSET = 16,
	HDMI_VMON_STATUS5_VBACK_MASK = GENMASK(15,0),
	HDMI_VMON_STATUS5_VBACK_OFFSET = 0,
	/* HDMI_VMON_STATUS6 field values */
	HDMI_VMON_STATUS6_VTOTAL_MASK = GENMASK(31,16),
	HDMI_VMON_STATUS6_VTOTAL_OFFSET = 16,
	HDMI_VMON_STATUS6_VACTIVE_MASK = GENMASK(15,0),
	HDMI_VMON_STATUS6_VACTIVE_OFFSET = 0,
	/* HDMI_VMON_STATUS7 field values */
	HDMI_VMON_STATUS7_ALT_DETECT = BIT(8),
	HDMI_VMON_STATUS7_ILACE_DETECT = BIT(4),
	HDMI_VMON_STATUS7_FIELD_DETECT = BIT(0),
/* --- id_cec --- */
	/* HDMI_CEC_STATUS field values */
	HDMI_CEC_STATUS_TX_BUSY = BIT(8),
	HDMI_CEC_STATUS_RX_BUSY = BIT(4),
	HDMI_CEC_STATUS_FRAME_SEND_PENDING = BIT(0),
	/* HDMI_CEC_CONFIG field values */
	HDMI_CEC_CONFIG_RX_AUTOMATIC_DRIVE_ACKNOWLEDGE_MASK = BIT(9),
	HDMI_CEC_CONFIG_RX_AUTOMATIC_DRIVE_ACKNOWLEDGE_OFFSET = 9,
	HDMI_CEC_CONFIG_CECFILTER_MASK = BIT(8),
	HDMI_CEC_CONFIG_CECFILTER_OFFSET = 8,
	HDMI_CEC_CONFIG_FRAME_NRETRANS_MASK = GENMASK(5,4),
	HDMI_CEC_CONFIG_FRAME_NRETRANS_OFFSET = 4,
	HDMI_CEC_CONFIG_BROADCAST_NACK_MASK = BIT(1),
	HDMI_CEC_CONFIG_BROADCAST_NACK_OFFSET = 1,
	HDMI_CEC_CONFIG_TXREQ_DISCARD_IF_RXBUSY_MASK = BIT(0),
	HDMI_CEC_CONFIG_TXREQ_DISCARD_IF_RXBUSY_OFFSET = 0,
	/* HDMI_CEC_ADDR field values */
	HDMI_CEC_ADDR_FOLLOWER_ADDR_MASK = GENMASK(14,0),
	HDMI_CEC_ADDR_FOLLOWER_ADDR_OFFSET = 0,
/* --- id_main_unit_interrupt --- */
	/* MAINUNIT_0_INT_STATUS field values */
	HDMI_MAINUNIT_0_INT_STATUS_REGBANK_READY = BIT(31),
	HDMI_MAINUNIT_0_INT_STATUS_APB_IF_READY = BIT(30),
	HDMI_MAINUNIT_0_INT_STATUS_TIMER_BASE_LOCKED = BIT(26),
	HDMI_MAINUNIT_0_INT_STATUS_TMDSQP_CK_OFF = BIT(5),
	HDMI_MAINUNIT_0_INT_STATUS_TMDSQP_CK_LOCKED = BIT(4),
	HDMI_MAINUNIT_0_INT_STATUS_AUDIO_CK_OFF = BIT(1),
	HDMI_MAINUNIT_0_INT_STATUS_AUDIO_CK_LOCKED = BIT(0),
	/* MAINUNIT_0_INT_MASK_N field values */
	HDMI_MAINUNIT_0_INT_MASK_N_REGBANK_READY_MASK = BIT(31),
	HDMI_MAINUNIT_0_INT_MASK_N_REGBANK_READY_OFFSET = 31,
	HDMI_MAINUNIT_0_INT_MASK_N_APB_IF_READY_MASK = BIT(30),
	HDMI_MAINUNIT_0_INT_MASK_N_APB_IF_READY_OFFSET = 30,
	HDMI_MAINUNIT_0_INT_MASK_N_TIMER_BASE_LOCKED_MASK = BIT(26),
	HDMI_MAINUNIT_0_INT_MASK_N_TIMER_BASE_LOCKED_OFFSET = 26,
	HDMI_MAINUNIT_0_INT_MASK_N_TMDSQP_CK_OFF_MASK = BIT(5),
	HDMI_MAINUNIT_0_INT_MASK_N_TMDSQP_CK_OFF_OFFSET = 5,
	HDMI_MAINUNIT_0_INT_MASK_N_TMDSQP_CK_LOCKED_MASK = BIT(4),
	HDMI_MAINUNIT_0_INT_MASK_N_TMDSQP_CK_LOCKED_OFFSET = 4,
	HDMI_MAINUNIT_0_INT_MASK_N_AUDIO_CK_OFF_MASK = BIT(1),
	HDMI_MAINUNIT_0_INT_MASK_N_AUDIO_CK_OFF_OFFSET = 1,
	HDMI_MAINUNIT_0_INT_MASK_N_AUDIO_CK_LOCKED_MASK = BIT(0),
	HDMI_MAINUNIT_0_INT_MASK_N_AUDIO_CK_LOCKED_OFFSET = 0,
	/* MAINUNIT_0_INT_CLEAR field values */
	HDMI_MAINUNIT_0_INT_CLEAR_REGBANK_READY_MASK = BIT(31),
	HDMI_MAINUNIT_0_INT_CLEAR_REGBANK_READY_OFFSET = 31,
	HDMI_MAINUNIT_0_INT_CLEAR_APB_IF_READY_MASK = BIT(30),
	HDMI_MAINUNIT_0_INT_CLEAR_APB_IF_READY_OFFSET = 30,
	HDMI_MAINUNIT_0_INT_CLEAR_TIMER_BASE_LOCKED_MASK = BIT(26),
	HDMI_MAINUNIT_0_INT_CLEAR_TIMER_BASE_LOCKED_OFFSET = 26,
	HDMI_MAINUNIT_0_INT_CLEAR_TMDSQP_CK_OFF_MASK = BIT(5),
	HDMI_MAINUNIT_0_INT_CLEAR_TMDSQP_CK_OFF_OFFSET = 5,
	HDMI_MAINUNIT_0_INT_CLEAR_TMDSQP_CK_LOCKED_MASK = BIT(4),
	HDMI_MAINUNIT_0_INT_CLEAR_TMDSQP_CK_LOCKED_OFFSET = 4,
	HDMI_MAINUNIT_0_INT_CLEAR_AUDIO_CK_OFF_MASK = BIT(1),
	HDMI_MAINUNIT_0_INT_CLEAR_AUDIO_CK_OFF_OFFSET = 1,
	HDMI_MAINUNIT_0_INT_CLEAR_AUDIO_CK_LOCKED_MASK = BIT(0),
	HDMI_MAINUNIT_0_INT_CLEAR_AUDIO_CK_LOCKED_OFFSET = 0,
	/* MAINUNIT_1_INT_STATUS field values */
	HDMI_MAINUNIT_1_INT_STATUS_CEC_POWERED_DOWN = BIT(13),
	HDMI_MAINUNIT_1_INT_STATUS_CEC_POWERED_UP = BIT(12),
	HDMI_MAINUNIT_1_INT_STATUS_AVPUNIT_POWERED_DOWN = BIT(1),
	HDMI_MAINUNIT_1_INT_STATUS_AVPUNIT_POWERED_UP = BIT(0),
	/* MAINUNIT_1_INT_MASK_N field values */
	HDMI_MAINUNIT_1_INT_MASK_N_CEC_POWERED_DOWN_MASK = BIT(13),
	HDMI_MAINUNIT_1_INT_MASK_N_CEC_POWERED_DOWN_OFFSET = 13,
	HDMI_MAINUNIT_1_INT_MASK_N_CEC_POWERED_UP_MASK = BIT(12),
	HDMI_MAINUNIT_1_INT_MASK_N_CEC_POWERED_UP_OFFSET = 12,
	HDMI_MAINUNIT_1_INT_MASK_N_AVPUNIT_POWERED_DOWN_MASK = BIT(1),
	HDMI_MAINUNIT_1_INT_MASK_N_AVPUNIT_POWERED_DOWN_OFFSET = 1,
	HDMI_MAINUNIT_1_INT_MASK_N_AVPUNIT_POWERED_UP_MASK = BIT(0),
	HDMI_MAINUNIT_1_INT_MASK_N_AVPUNIT_POWERED_UP_OFFSET = 0,
	/* MAINUNIT_1_INT_CLEAR field values */
	HDMI_MAINUNIT_1_INT_CLEAR_CEC_POWERED_DOWN_MASK = BIT(13),
	HDMI_MAINUNIT_1_INT_CLEAR_CEC_POWERED_DOWN_OFFSET = 13,
	HDMI_MAINUNIT_1_INT_CLEAR_CEC_POWERED_UP_MASK = BIT(12),
	HDMI_MAINUNIT_1_INT_CLEAR_CEC_POWERED_UP_OFFSET = 12,
	HDMI_MAINUNIT_1_INT_CLEAR_AVPUNIT_POWERED_DOWN_MASK = BIT(1),
	HDMI_MAINUNIT_1_INT_CLEAR_AVPUNIT_POWERED_DOWN_OFFSET = 1,
	HDMI_MAINUNIT_1_INT_CLEAR_AVPUNIT_POWERED_UP_MASK = BIT(0),
	HDMI_MAINUNIT_1_INT_CLEAR_AVPUNIT_POWERED_UP_OFFSET = 0,
	/* MAINUNIT_2_INT_STATUS field values */
	HDMI_MAINUNIT_2_INT_STATUS_TMDSVALID_STABLE = BIT(1),
	HDMI_MAINUNIT_2_INT_STATUS_AUDPLL_LOCK_STABLE = BIT(0),
	/* MAINUNIT_2_INT_MASK_N field values */
	HDMI_MAINUNIT_2_INT_MASK_N_TMDSVALID_STABLE_MASK = BIT(1),
	HDMI_MAINUNIT_2_INT_MASK_N_TMDSVALID_STABLE_OFFSET = 1,
	HDMI_MAINUNIT_2_INT_MASK_N_AUDPLL_LOCK_STABLE_MASK = BIT(0),
	HDMI_MAINUNIT_2_INT_MASK_N_AUDPLL_LOCK_STABLE_OFFSET = 0,
	/* MAINUNIT_2_INT_CLEAR field values */
	HDMI_MAINUNIT_2_INT_CLEAR_TMDSVALID_STABLE_MASK = BIT(1),
	HDMI_MAINUNIT_2_INT_CLEAR_TMDSVALID_STABLE_OFFSET = 1,
	HDMI_MAINUNIT_2_INT_CLEAR_AUDPLL_LOCK_STABLE_MASK = BIT(0),
	HDMI_MAINUNIT_2_INT_CLEAR_AUDPLL_LOCK_STABLE_OFFSET = 0,
/* --- id_avpunit_interrupt --- */
	/* AVPUNIT_1_INT_STATUS field values */
	HDMI_AVPUNIT_1_INT_STATUS_VMON_VMEAS = BIT(31),
	HDMI_AVPUNIT_1_INT_STATUS_VMON_HMEAS = BIT(30),
	HDMI_AVPUNIT_1_INT_STATUS_AUD_CHSTATUS_SP3 = BIT(24),
	HDMI_AVPUNIT_1_INT_STATUS_AUD_CHSTATUS_SP2 = BIT(23),
	HDMI_AVPUNIT_1_INT_STATUS_AUD_CHSTATUS_SP1 = BIT(22),
	HDMI_AVPUNIT_1_INT_STATUS_AUD_CHSTATUS_SP0 = BIT(21),
	HDMI_AVPUNIT_1_INT_STATUS_AUD_MUTE = BIT(20),
	HDMI_AVPUNIT_1_INT_STATUS_AFIFO_UNDERFLOW = BIT(19),
	HDMI_AVPUNIT_1_INT_STATUS_AFIFO_OVERFLOW = BIT(18),
	HDMI_AVPUNIT_1_INT_STATUS_AFIFO_THR_PASS = BIT(13),
	HDMI_AVPUNIT_1_INT_STATUS_AUD_FMT_CHG = BIT(12),
	HDMI_AVPUNIT_1_INT_STATUS_DEFRAMER_DVIHDMI_CHG = BIT(3),
	HDMI_AVPUNIT_1_INT_STATUS_DEFRAMER_GBDET_ERR = BIT(2),
	/* AVPUNIT_1_INT_MASK_N field values */
	HDMI_AVPUNIT_1_INT_MASK_N_VMON_VMEAS_MASK = BIT(31),
	HDMI_AVPUNIT_1_INT_MASK_N_VMON_VMEAS_OFFSET = 31,
	HDMI_AVPUNIT_1_INT_MASK_N_VMON_HMEAS_MASK = BIT(30),
	HDMI_AVPUNIT_1_INT_MASK_N_VMON_HMEAS_OFFSET = 30,
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP3_MASK = BIT(24),
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP3_OFFSET = 24,
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP2_MASK = BIT(23),
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP2_OFFSET = 23,
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP1_MASK = BIT(22),
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP1_OFFSET = 22,
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP0_MASK = BIT(21),
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP0_OFFSET = 21,
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_MUTE_MASK = BIT(20),
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_MUTE_OFFSET = 20,
	HDMI_AVPUNIT_1_INT_MASK_N_AFIFO_UNDERFLOW_MASK = BIT(19),
	HDMI_AVPUNIT_1_INT_MASK_N_AFIFO_UNDERFLOW_OFFSET = 19,
	HDMI_AVPUNIT_1_INT_MASK_N_AFIFO_THR_PASS_MASK = BIT(13),
	HDMI_AVPUNIT_1_INT_MASK_N_AFIFO_THR_PASS_OFFSET = 13,
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_FMT_CHG_MASK = BIT(12),
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_FMT_CHG_OFFSET = 12,
	HDMI_AVPUNIT_1_INT_MASK_N_AFIFO_OVERFLOW_MASK = BIT(18),
	HDMI_AVPUNIT_1_INT_MASK_N_AFIFO_OVERFLOW_OFFSET = 18,
	HDMI_AVPUNIT_1_INT_MASK_N_DEFRAMER_DVIHDMI_CHG_MASK = BIT(3),
	HDMI_AVPUNIT_1_INT_MASK_N_DEFRAMER_DVIHDMI_CHG_OFFSET = 3,
	HDMI_AVPUNIT_1_INT_MASK_N_DEFRAMER_GBDET_ERR_MASK = BIT(2),
	HDMI_AVPUNIT_1_INT_MASK_N_DEFRAMER_GBDET_ERR_OFFSET = 2,
	/* AVPUNIT_1_INT_CLEAR field values */
	HDMI_AVPUNIT_1_INT_CLEAR_VMON_VMEAS_MASK = BIT(31),
	HDMI_AVPUNIT_1_INT_CLEAR_VMON_VMEAS_OFFSET = 31,
	HDMI_AVPUNIT_1_INT_CLEAR_VMON_HMEAS_MASK = BIT(30),
	HDMI_AVPUNIT_1_INT_CLEAR_VMON_HMEAS_OFFSET = 30,
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP3_MASK = BIT(24),
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP3_OFFSET = 24,
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP2_MASK = BIT(23),
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP2_OFFSET = 23,
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP1_MASK = BIT(22),
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP1_OFFSET = 22,
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP0_MASK = BIT(21),
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP0_OFFSET = 21,
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_MUTE_MASK = BIT(20),
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_MUTE_OFFSET = 20,
	HDMI_AVPUNIT_1_INT_CLEAR_AFIFO_UNDERFLOW_MASK = BIT(19),
	HDMI_AVPUNIT_1_INT_CLEAR_AFIFO_UNDERFLOW_OFFSET = 19,
	HDMI_AVPUNIT_1_INT_CLEAR_AFIFO_OVERFLOW_MASK = BIT(18),
	HDMI_AVPUNIT_1_INT_CLEAR_AFIFO_OVERFLOW_OFFSET = 18,
	HDMI_AVPUNIT_1_INT_CLEAR_DEFRAMER_DVIHDMI_CHG_MASK = BIT(3),
	HDMI_AVPUNIT_1_INT_CLEAR_DEFRAMER_DVIHDMI_CHG_OFFSET = 3,
	HDMI_AVPUNIT_1_INT_CLEAR_DEFRAMER_GBDET_ERR_MASK = BIT(2),
	HDMI_AVPUNIT_1_INT_CLEAR_DEFRAMER_GBDET_ERR_OFFSET = 2,
/* --- id_packet_interrupt --- */
	/* PKT_0_INT_STATUS field values */
	HDMI_PKT_0_INT_STATUS_GENPKT1 = BIT(18),
	HDMI_PKT_0_INT_STATUS_GENPKT0 = BIT(17),
	HDMI_PKT_0_INT_STATUS_DRMIF = BIT(16),
	HDMI_PKT_0_INT_STATUS_NTSCVBIIF = BIT(15),
	HDMI_PKT_0_INT_STATUS_AUDIF = BIT(13),
	HDMI_PKT_0_INT_STATUS_SRCPDIF = BIT(12),
	HDMI_PKT_0_INT_STATUS_AVIIF = BIT(11),
	HDMI_PKT_0_INT_STATUS_VSIF = BIT(10),
	HDMI_PKT_0_INT_STATUS_AMD = BIT(9),
	HDMI_PKT_0_INT_STATUS_GMD = BIT(8),
	HDMI_PKT_0_INT_STATUS_ISRC2 = BIT(7),
	HDMI_PKT_0_INT_STATUS_ISRC1 = BIT(6),
	HDMI_PKT_0_INT_STATUS_ACP = BIT(5),
	HDMI_PKT_0_INT_STATUS_GCP = BIT(4),
	HDMI_PKT_0_INT_STATUS_ACR = BIT(3),
	HDMI_PKT_0_INT_STATUS_ACP_TIMEOUT = BIT(2),
	HDMI_PKT_0_INT_STATUS_ACR_N = BIT(1),
	HDMI_PKT_0_INT_STATUS_ACR_CTS = BIT(0),
	/* PKT_0_INT_MASK_N field values */
	HDMI_PKT_0_INT_MASK_N_GENPKT1_MASK = BIT(18),
	HDMI_PKT_0_INT_MASK_N_GENPKT1_OFFSET = 18,
	HDMI_PKT_0_INT_MASK_N_GENPKT0_MASK = BIT(17),
	HDMI_PKT_0_INT_MASK_N_GENPKT0_OFFSET = 17,
	HDMI_PKT_0_INT_MASK_N_DRMIF_MASK = BIT(16),
	HDMI_PKT_0_INT_MASK_N_DRMIF_OFFSET = 16,
	HDMI_PKT_0_INT_MASK_N_NTSCVBIIF_MASK = BIT(15),
	HDMI_PKT_0_INT_MASK_N_NTSCVBIIF_OFFSET = 15,
	HDMI_PKT_0_INT_MASK_N_AUDIF_MASK = BIT(13),
	HDMI_PKT_0_INT_MASK_N_AUDIF_OFFSET = 13,
	HDMI_PKT_0_INT_MASK_N_SRCPDIF_MASK = BIT(12),
	HDMI_PKT_0_INT_MASK_N_SRCPDIF_OFFSET = 12,
	HDMI_PKT_0_INT_MASK_N_AVIIF_MASK = BIT(11),
	HDMI_PKT_0_INT_MASK_N_AVIIF_OFFSET = 11,
	HDMI_PKT_0_INT_MASK_N_VSIF_MASK = BIT(10),
	HDMI_PKT_0_INT_MASK_N_VSIF_OFFSET = 10,
	HDMI_PKT_0_INT_MASK_N_AMD_MASK = BIT(9),
	HDMI_PKT_0_INT_MASK_N_AMD_OFFSET = 9,
	HDMI_PKT_0_INT_MASK_N_GMD_MASK = BIT(8),
	HDMI_PKT_0_INT_MASK_N_GMD_OFFSET = 8,
	HDMI_PKT_0_INT_MASK_N_ISRC2_MASK = BIT(7),
	HDMI_PKT_0_INT_MASK_N_ISRC2_OFFSET = 7,
	HDMI_PKT_0_INT_MASK_N_ISRC1_MASK = BIT(6),
	HDMI_PKT_0_INT_MASK_N_ISRC1_OFFSET = 6,
	HDMI_PKT_0_INT_MASK_N_ACP_MASK = BIT(5),
	HDMI_PKT_0_INT_MASK_N_ACP_OFFSET = 5,
	HDMI_PKT_0_INT_MASK_N_GCP_MASK = BIT(4),
	HDMI_PKT_0_INT_MASK_N_GCP_OFFSET = 4,
	HDMI_PKT_0_INT_MASK_N_ACR_MASK = BIT(3),
	HDMI_PKT_0_INT_MASK_N_ACR_OFFSET = 3,
	HDMI_PKT_0_INT_MASK_N_ACP_TIMEOUT_MASK = BIT(2),
	HDMI_PKT_0_INT_MASK_N_ACP_TIMEOUT_OFFSET = 2,
	HDMI_PKT_0_INT_MASK_N_ACR_N_MASK = BIT(1),
	HDMI_PKT_0_INT_MASK_N_ACR_N_OFFSET = 1,
	HDMI_PKT_0_INT_MASK_N_ACR_CTS_MASK = BIT(0),
	HDMI_PKT_0_INT_MASK_N_ACR_CTS_OFFSET = 0,
	/* PKT_0_INT_CLEAR field values */
	HDMI_PKT_0_INT_CLEAR_GENPKT1_MASK = BIT(18),
	HDMI_PKT_0_INT_CLEAR_GENPKT1_OFFSET = 18,
	HDMI_PKT_0_INT_CLEAR_GENPKT0_MASK = BIT(17),
	HDMI_PKT_0_INT_CLEAR_GENPKT0_OFFSET = 17,
	HDMI_PKT_0_INT_CLEAR_DRMIF_MASK = BIT(16),
	HDMI_PKT_0_INT_CLEAR_DRMIF_OFFSET = 16,
	HDMI_PKT_0_INT_CLEAR_NTSCVBIIF_MASK = BIT(15),
	HDMI_PKT_0_INT_CLEAR_NTSCVBIIF_OFFSET = 15,
	HDMI_PKT_0_INT_CLEAR_AUDIF_MASK = BIT(13),
	HDMI_PKT_0_INT_CLEAR_AUDIF_OFFSET = 13,
	HDMI_PKT_0_INT_CLEAR_SRCPDIF_MASK = BIT(12),
	HDMI_PKT_0_INT_CLEAR_SRCPDIF_OFFSET = 12,
	HDMI_PKT_0_INT_CLEAR_AVIIF_MASK = BIT(11),
	HDMI_PKT_0_INT_CLEAR_AVIIF_OFFSET = 11,
	HDMI_PKT_0_INT_CLEAR_VSIF_MASK = BIT(10),
	HDMI_PKT_0_INT_CLEAR_VSIF_OFFSET = 10,
	HDMI_PKT_0_INT_CLEAR_AMD_MASK = BIT(9),
	HDMI_PKT_0_INT_CLEAR_AMD_OFFSET = 9,
	HDMI_PKT_0_INT_CLEAR_GMD_MASK = BIT(8),
	HDMI_PKT_0_INT_CLEAR_GMD_OFFSET = 8,
	HDMI_PKT_0_INT_CLEAR_ISRC2_MASK = BIT(7),
	HDMI_PKT_0_INT_CLEAR_ISRC2_OFFSET = 7,
	HDMI_PKT_0_INT_CLEAR_ISRC1_MASK = BIT(6),
	HDMI_PKT_0_INT_CLEAR_ISRC1_OFFSET = 6,
	HDMI_PKT_0_INT_CLEAR_ACP_MASK = BIT(5),
	HDMI_PKT_0_INT_CLEAR_ACP_OFFSET = 5,
	HDMI_PKT_0_INT_CLEAR_GCP_MASK = BIT(4),
	HDMI_PKT_0_INT_CLEAR_GCP_OFFSET = 4,
	HDMI_PKT_0_INT_CLEAR_ACR_MASK = BIT(3),
	HDMI_PKT_0_INT_CLEAR_ACR_OFFSET = 3,
	HDMI_PKT_0_INT_CLEAR_ACP_TIMEOUT_MASK = BIT(2),
	HDMI_PKT_0_INT_CLEAR_ACP_TIMEOUT_OFFSET = 2,
	HDMI_PKT_0_INT_CLEAR_ACR_N_MASK = BIT(1),
	HDMI_PKT_0_INT_CLEAR_ACR_N_OFFSET = 1,
	HDMI_PKT_0_INT_CLEAR_ACR_CTS_MASK = BIT(0),
	HDMI_PKT_0_INT_CLEAR_ACR_CTS_OFFSET = 0,
	/* PKT_1_INT_STATUS field values */
	HDMI_PKT_1_INT_STATUS_NEW_ENTRY = BIT(6),
	HDMI_PKT_1_INT_STATUS_OVERFLOW = BIT(5),
	HDMI_PKT_1_INT_STATUS_UNDERFLOW = BIT(4),
	HDMI_PKT_1_INT_STATUS_THR_HIGH = BIT(2),
	HDMI_PKT_1_INT_STATUS_THR_PASS = BIT(1),
	HDMI_PKT_1_INT_STATUS_THR_LOW = BIT(0),
	/* PKT_1_INT_MASK_N field values */
	HDMI_PKT_1_INT_MASK_N_NEW_ENTRY_MASK = BIT(6),
	HDMI_PKT_1_INT_MASK_N_NEW_ENTRY_OFFSET = 6,
	HDMI_PKT_1_INT_MASK_N_OVERFLOW_MASK = BIT(5),
	HDMI_PKT_1_INT_MASK_N_OVERFLOW_OFFSET = 5,
	HDMI_PKT_1_INT_MASK_N_UNDERFLOW_MASK = BIT(4),
	HDMI_PKT_1_INT_MASK_N_UNDERFLOW_OFFSET = 4,
	HDMI_PKT_1_INT_MASK_N_THR_HIGH_MASK = BIT(2),
	HDMI_PKT_1_INT_MASK_N_THR_HIGH_OFFSET = 2,
	HDMI_PKT_1_INT_MASK_N_THR_PASS_MASK = BIT(1),
	HDMI_PKT_1_INT_MASK_N_THR_PASS_OFFSET = 1,
	HDMI_PKT_1_INT_MASK_N_THR_LOW_MASK = BIT(0),
	HDMI_PKT_1_INT_MASK_N_THR_LOW_OFFSET = 0,
	/* PKT_1_INT_CLEAR field values */
	HDMI_PKT_1_INT_CLEAR_NEW_ENTRY_MASK = BIT(6),
	HDMI_PKT_1_INT_CLEAR_NEW_ENTRY_OFFSET = 6,
	HDMI_PKT_1_INT_CLEAR_OVERFLOW_MASK = BIT(5),
	HDMI_PKT_1_INT_CLEAR_OVERFLOW_OFFSET = 5,
	HDMI_PKT_1_INT_CLEAR_UNDERFLOW_MASK = BIT(4),
	HDMI_PKT_1_INT_CLEAR_UNDERFLOW_OFFSET = 4,
	HDMI_PKT_1_INT_CLEAR_THR_HIGH_MASK = BIT(2),
	HDMI_PKT_1_INT_CLEAR_THR_HIGH_OFFSET = 2,
	HDMI_PKT_1_INT_CLEAR_THR_PASS_MASK = BIT(1),
	HDMI_PKT_1_INT_CLEAR_THR_PASS_OFFSET = 1,
	HDMI_PKT_1_INT_CLEAR_THR_LOW_MASK = BIT(0),
	HDMI_PKT_1_INT_CLEAR_THR_LOW_OFFSET = 0,
/* --- id_scdc_interrupt --- */
	/* SCDC_INT_STATUS field values */
	HDMI_SCDC_INT_STATUS_FRL_RATE_FFE_LEVELS_WR = BIT(4),
	HDMI_SCDC_INT_STATUS_TMDS_CFG = BIT(2),
	HDMI_SCDC_INT_STATUS_SC = BIT(1),
	HDMI_SCDC_INT_STATUS_CFG = BIT(0),
	/* SCDC_INT_MASK_N field values */
	HDMI_SCDC_INT_MASK_N_FRL_RATE_FFE_LEVELS_WR_MASK = BIT(4),
	HDMI_SCDC_INT_MASK_N_FRL_RATE_FFE_LEVELS_WR_OFFSET = 4,
	HDMI_SCDC_INT_MASK_N_TMDS_CFG_MASK = BIT(2),
	HDMI_SCDC_INT_MASK_N_TMDS_CFG_OFFSET = 2,
	HDMI_SCDC_INT_MASK_N_SC_MASK = BIT(1),
	HDMI_SCDC_INT_MASK_N_SC_OFFSET = 1,
	HDMI_SCDC_INT_MASK_N_CFG_MASK = BIT(0),
	HDMI_SCDC_INT_MASK_N_CFG_OFFSET = 0,
	/* SCDC_INT_CLEAR field values */
	HDMI_SCDC_INT_CLEAR_FRL_RATE_FFE_LEVELS_WR_MASK = BIT(4),
	HDMI_SCDC_INT_CLEAR_FRL_RATE_FFE_LEVELS_WR_OFFSET = 4,
	HDMI_SCDC_INT_CLEAR_TMDS_CFG_MASK = BIT(2),
	HDMI_SCDC_INT_CLEAR_TMDS_CFG_OFFSET = 2,
	HDMI_SCDC_INT_CLEAR_SC_MASK = BIT(1),
	HDMI_SCDC_INT_CLEAR_SC_OFFSET = 1,
	HDMI_SCDC_INT_CLEAR_CFG_MASK = BIT(0),
	HDMI_SCDC_INT_CLEAR_CFG_OFFSET = 0,
/* --- id_hdcp_interrupt --- */
	/* HDCP_INT_STATUS field values */
	HDMI_HDCP_INT_STATUS_ENCDIS = BIT(8),
	HDMI_HDCP_INT_STATUS_ENCEN = BIT(7),
	/* HDCP_INT_MASK_N field values */
	HDMI_HDCP_INT_MASK_N_ENCDIS_MASK = BIT(8),
	HDMI_HDCP_INT_MASK_N_ENCDIS_OFFSET = 8,
	HDMI_HDCP_INT_MASK_N_ENCEN_MASK = BIT(7),
	HDMI_HDCP_INT_MASK_N_ENCEN_OFFSET = 7,
	/* HDCP_INT_CLEAR field values */
	HDMI_HDCP_INT_CLEAR_ENCDIS_MASK = BIT(8),
	HDMI_HDCP_INT_CLEAR_ENCDIS_OFFSET = 8,
	HDMI_HDCP_INT_CLEAR_ENCEN_MASK = BIT(7),
	HDMI_HDCP_INT_CLEAR_ENCEN_OFFSET = 7,
/* --- id_cec_interrupt --- */
	/* HDMI_CEC_INT_STATUS field values */
	HDMI_CEC_INT_STATUS_RX_NOTIFY_ERR = BIT(12),
	HDMI_CEC_INT_STATUS_RX_EOM = BIT(11),
	HDMI_CEC_INT_STATUS_TX_DRIVE_ERR = BIT(10),
	HDMI_CEC_INT_STATUS_RX_BUSY = BIT(9),
	HDMI_CEC_INT_STATUS_TX_BUSY = BIT(8),
	HDMI_CEC_INT_STATUS_TX_FRAME_DISCARDED = BIT(5),
	HDMI_CEC_INT_STATUS_TX_NRETRANSMIT_FAIL = BIT(4),
	HDMI_CEC_INT_STATUS_TX_LINE_ERR = BIT(3),
	HDMI_CEC_INT_STATUS_TX_ARBLOST = BIT(2),
	HDMI_CEC_INT_STATUS_TX_NACK = BIT(1),
	HDMI_CEC_INT_STATUS_TX_DONE = BIT(0),
	/* HDMI_CEC_INT_MASK_N field values */
	HDMI_CEC_INT_MASK_N_RX_NOTIFY_ERR_MASK = BIT(12),
	HDMI_CEC_INT_MASK_N_RX_NOTIFY_ERR_OFFSET = 12,
	HDMI_CEC_INT_MASK_N_RX_EOM_MASK = BIT(11),
	HDMI_CEC_INT_MASK_N_RX_EOM_OFFSET = 11,
	HDMI_CEC_INT_MASK_N_TX_DRIVE_ERR_MASK = BIT(10),
	HDMI_CEC_INT_MASK_N_TX_DRIVE_ERR_OFFSET = 10,
	HDMI_CEC_INT_MASK_N_RX_BUSY_MASK = BIT(9),
	HDMI_CEC_INT_MASK_N_RX_BUSY_OFFSET = 9,
	HDMI_CEC_INT_MASK_N_TX_BUSY_MASK = BIT(8),
	HDMI_CEC_INT_MASK_N_TX_BUSY_OFFSET = 8,
	HDMI_CEC_INT_MASK_N_TX_FRAME_DISCARDED_MASK = BIT(5),
	HDMI_CEC_INT_MASK_N_TX_FRAME_DISCARDED_OFFSET = 5,
	HDMI_CEC_INT_MASK_N_TX_NRETRANSMIT_FAIL_MASK = BIT(4),
	HDMI_CEC_INT_MASK_N_TX_NRETRANSMIT_FAIL_OFFSET = 4,
	HDMI_CEC_INT_MASK_N_TX_LINE_ERR_MASK = BIT(3),
	HDMI_CEC_INT_MASK_N_TX_LINE_ERR_OFFSET = 3,
	HDMI_CEC_INT_MASK_N_TX_ARBLOST_MASK = BIT(2),
	HDMI_CEC_INT_MASK_N_TX_ARBLOST_OFFSET = 2,
	HDMI_CEC_INT_MASK_N_TX_NACK_MASK = BIT(1),
	HDMI_CEC_INT_MASK_N_TX_NACK_OFFSET = 1,
	HDMI_CEC_INT_MASK_N_TX_DONE_MASK = BIT(0),
	HDMI_CEC_INT_MASK_N_TX_DONE_OFFSET = 0,
	/* HDMI_CEC_INT_CLEAR field values */
	HDMI_CEC_INT_CLEAR_RX_NOTIFY_ERR_MASK = BIT(12),
	HDMI_CEC_INT_CLEAR_RX_NOTIFY_ERR_OFFSET = 12,
	HDMI_CEC_INT_CLEAR_RX_EOM_MASK = BIT(11),
	HDMI_CEC_INT_CLEAR_RX_EOM_OFFSET = 11,
	HDMI_CEC_INT_CLEAR_TX_DRIVE_ERR_MASK = BIT(10),
	HDMI_CEC_INT_CLEAR_TX_DRIVE_ERR_OFFSET = 10,
	HDMI_CEC_INT_CLEAR_RX_BUSY_MASK = BIT(9),
	HDMI_CEC_INT_CLEAR_RX_BUSY_OFFSET = 9,
	HDMI_CEC_INT_CLEAR_TX_BUSY_MASK = BIT(8),
	HDMI_CEC_INT_CLEAR_TX_BUSY_OFFSET = 8,
	HDMI_CEC_INT_CLEAR_TX_FRAME_DISCARDED_MASK = BIT(5),
	HDMI_CEC_INT_CLEAR_TX_FRAME_DISCARDED_OFFSET = 5,
	HDMI_CEC_INT_CLEAR_TX_NRETRANSMIT_FAIL_MASK = BIT(4),
	HDMI_CEC_INT_CLEAR_TX_NRETRANSMIT_FAIL_OFFSET = 4,
	HDMI_CEC_INT_CLEAR_TX_LINE_ERR_MASK = BIT(3),
	HDMI_CEC_INT_CLEAR_TX_LINE_ERR_OFFSET = 3,
	HDMI_CEC_INT_CLEAR_TX_ARBLOST_MASK = BIT(2),
	HDMI_CEC_INT_CLEAR_TX_ARBLOST_OFFSET = 2,
	HDMI_CEC_INT_CLEAR_TX_NACK_MASK = BIT(1),
	HDMI_CEC_INT_CLEAR_TX_NACK_OFFSET = 1,
	HDMI_CEC_INT_CLEAR_TX_DONE_MASK = BIT(0),
	HDMI_CEC_INT_CLEAR_TX_DONE_OFFSET = 0,
/* --- id_cbus_unit --- */
/* --- id_ecbus_slot_manager_interrupt --- */
/* --- id_ecbus_vc_emsc_interrupt --- */
/* --- id_ecbus_vc_low_latency_interrupt --- */
/* --- id_cbus_hdcp_if_interrupt --- */
/* --- id_cbus_device_discovery_interrupt --- */
/* --- id_ocbus_link_layer_interrupt --- */
};

/*----------------------------------------------------------------------------------------
	Extern Function Prototype Declaration
----------------------------------------------------------------------------------------*/
extern	void	 HDMICEC_PreInit(void);
extern	int      HDMICEC_Init(void);
extern	void     HDMICEC_Cleanup(void);

extern int hdmicec_init(void);
/*----------------------------------------------------------------------------------------
	Extern Variables
----------------------------------------------------------------------------------------*/
#ifdef	__cplusplus
}
#endif /* __cplusplus */

#endif /* _AFE_DRV_H_ */

/** @} */
