obj-$(CONFIG_EKP_KERNEL_DEBUG_IN_ISE)	+= inise-kdebug.o
obj-$(CONFIG_EKP_DEBUGFS)		+= debugfs.o state.o core/
obj-$(CONFIG_EKP_DEBUGFS_SYSINFO)	+= sysinfo.o
obj-$(CONFIG_EKP_DEBUGFS_TEST_HELPERS)	+= test-helper.o
