obj-$(CONFIG_EKP_DEBUGFS_PTDUMP_CORE)		+= ptdump.o
obj-$(CONFIG_EKP_DEBUGFS_CHECK_PROT)		+= ptprot.o ptprot-pgtable.o
obj-$(CONFIG_EKP_DEBUGFS_TEST_AGAINST_ATTACK)	+= ptmanip.o ptmanip-parse.o \
						   sc.o
