/*
	SIC LABORATORY, LG ELECTRONICS INC., SEOUL, KOREA
	Copyright(c) 2013 by LG Electronics Inc.

	This program is free software; you can redistribute it and/or 
	modify it under the terms of the GNU General Public License
	version 2 as published by the Free Software Foundation.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
	GNU General Public License for more details.
*/ 


/** @file
 *
 *  Brief description.
 *  Detailed description starts here.
 *
 *  @author     won.hur (won.hur@lge.com) 
 *  @version    1.0
 *  @date       2019-03-20
 *  @note       Additional information.
 */

#ifndef	_HDMI21_HAL_DRIVER_H_
#define	_HDMI21_HAL_DRIVER_H_

/*----------------------------------------------------------------------------------------
	Control Constants
----------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------
    File Inclusions
----------------------------------------------------------------------------------------*/
#include <linux/interrupt.h>

#include "hdmi20_kapi.h"
#include "hdmi_kapi.h"
#include "hdmi21_rx_audio.h"
#ifdef	__cplusplus
extern "C"
{
#endif /* __cplusplus */

/*----------------------------------------------------------------------------------------
	Macro Definitions
----------------------------------------------------------------------------------------*/
/**
 * Bit field mask
 * @param m	width
 * @param n shift
 */
#ifndef MSK
#define MSK(m, n)		(((1 << (m)) - 1) << (n))
#endif

/**
 * Bit mask
 * @param n shift
 */
#ifndef BIT
#define BIT(n)			MSK(1, (n))
#endif

#define HDMI21_LINE_DBG(line, format, args...) \
	if(gHDMI21RxDevVideoControler[HDMI21__VIDEO_LINE_DEBUGGER].value == line){ \
		HDMI20_DBG(format, ##args);\
	}\
/*----------------------------------------------------------------------------------------
	Constant Definitions
----------------------------------------------------------------------------------------*/
#define HDMI21_PQE_O20_SRC_INPUT_SEL (0xC9000200)
#define HDMI21_PQE_O20_SRC_INPUT_SEL_BIT	MSK(4, 14)
#define HDMI21_PQE_O22_SRC_INPUT_SEL (0xCC840200)
#define HDMI21_PQE_O22_SRC_INPUT_SEL_BIT	MSK(4, 14)
#define HDMI21_PQE_O24_SRC_INPUT_SEL (0xCCCC0200)
#define HDMI21_PQE_O24_SRC_INPUT_SEL_BIT	MSK(4, 14)
#define HDMI21_PQE_O26_SRC_INPUT_SEL (0xCC4E0200)
#define HDMI21_PQE_O26_SRC_INPUT_SEL_BIT	MSK(4, 14)

#define HDMI21_PQE_O20_HDR_INFO_ADDR (0xC902608C)
#define HDMI21_PQE_O20_HDR_INFO_SIZE (0x14)
#define HDMI21_PQE_O22_HDR_INFO_ADDR (0xCC8C0D28)
#define HDMI21_PQE_O22_HDR_INFO_SIZE (0x14)
#define HDMI21_PQE_M23_HDR_INFO_ADDR (0xCC6D0D28)
#define HDMI21_PQE_M23_HDR_INFO_SIZE (0x14)
#define HDMI21_PQE_O24_HDR_INFO_ADDR (0xCC820D28)
#define HDMI21_PQE_O24_HDR_INFO_SIZE (0x14)
#define HDMI21_PQE_O26_HDR_INFO_ADDR (0xCCC10E28)
#define HDMI21_PQE_O26_HDR_INFO_SIZE (0x14)


#define HDMI21_CHIP_O20_CRG_SETTING_REG				(0xC9305070)	/* Must refer to reg manual for usage */
#define HDMI21_CHIP_O20_CRG2_SETTING_REG			(0xC930500C)	/* Must refer to reg manual for usage */
#define HDMI21_CHIP_E60_CRG_SETTING_REG				(0xC93B8014)	/* Must refer to reg manual for usage */
#define HDMI21_CHIP_E60_CRG2_SETTING_REG			(0xC93B8018)	/* Must refer to reg manual for usage */
#define HDMI21_CHIP_O22_CRG_SETTING_REG				(0xC88B0010)	/* Must refer to reg manual for usage */
#define HDMI21_CHIP_O22_CRG2_SETTING_REG			(0xCC850010)	/* Must refer to reg manual for usage */
#define HDMI21_CHIP_O24_CRG_SETTING_REG				(0xC8CF0010)	/* Must refer to reg manual for usage */
#define HDMI21_CHIP_O24_CRG2_SETTING_REG			(0xCCCD0010)	/* Must refer to reg manual for usage */
#define HDMI21_CHIP_O26_CRG_SETTING_REG				(0xCC510010)	/* Must refer to reg manual for usage */
#define HDMI21_CHIP_O26_CRG2_SETTING_REG			(0xCC4F0010)	/* Must refer to reg manual for usage */


#define HDMI21_TOP_REG_AD_REG_MON_SEL				(0xA4)
#define HDMI21_TOP_FIELD_REG_PSLVERR_OFF			BIT(8)
#define HDMI21_TOP_FIELD_REG_PSLVERR_OFF_O24		BIT(28)

#define HDMI21_TOP_REG_SCDC_ISR_MASK				(0x128)
#define HDMI21_TOP_FIELD_SCDC_ISR_MASK				MSK(7, 16)

#define HDMI21_TOP_REG_SCDC_ISR_STATUS				(0x620)
#define HDMI21_TOP_FIELD_SCDC_ISR_STATUS			MSK(7, 8)

#define HDMI21_TOP_REG_SCDC_ISR_ENABLE_CLR			(0x624)
#define HDMI21_TOP_FIELD_SCDC_ISR_ENABLE			MSK(7, 0)
#define HDMI21_TOP_FIELD_SCDC_ISR_CLEAR				MSK(7, 8)

#define HDMI21_TOP_BIT_SCDC_ISR_FRL_RATE_RCV		BIT(0)
#define HDMI21_TOP_BIT_SCDC_ISR_FRL_RATE_SAME		BIT(1)
#define HDMI21_TOP_BIT_SCDC_ISR_SCRAMBLE_RCV		BIT(2)
#define HDMI21_TOP_BIT_SCDC_ISR_FRL_START_UP		BIT(3)
#define HDMI21_TOP_BIT_SCDC_ISR_FRL_START_DN		BIT(4)
#define HDMI21_TOP_BIT_SCDC_ISR_FRL_UPDATE_UP		BIT(5)
#define HDMI21_TOP_BIT_SCDC_ISR_FRL_UPDATE_DN		BIT(6)


#define HDMI21_TOP_VFREQ_COUNTER_SYS_CLOCK		(0x1C9C3800) /* 480MHz */
#define HDMI21_TOP_REG_AD_VFREQ_VALUE			(0x600)
#define HDMI21_TOP_REG_AD_VFREQ_OPT				(0x604)
#define HDMI21_TOP_FIELD_AD_VFREQ_OPT_ONE_FIELD		BIT(1)	
#define HDMI21_TOP_FIELD_AD_VFERQ_OPT_VFREQ_CHK_EN	BIT(0)


/* 2023/06/01 : O24 */
#define HDMI21_TOP_REG_NEW_REG_O24_SNPSRST		(0x630)
#define HDMI21_TOP_BIT_NEW_REG_O24_DATAPATHONLY		BIT(4)

#define HDMI21_TOP_REG_VFREQ_COUNTER_REF_CLK	(0x604)

#define HDMI21_TOP_REG_AD_FS_MONITOR_1				(0x300)
#define HDMI21_TOP_FIELD_AD_FS_MON_1_DE_CNT_VALID	BIT(3)
#define HDMI21_TOP_FIELD_AD_FS_MON_1_DE_LEN_VALID	BIT(2)
#define HDMI21_TOP_FIELD_AD_FS_MON_1_VSYNC_VALID	BIT(1)
#define HDMI21_TOP_FIELD_AD_FS_MON_1_HSYNC_VALID	BIT(0)

#define HDMI21_TOP_REG_AD_FS_MONITOR_3				(0x308)
#define HDMI21_TOP_FIELD_AD_FS_MON_3_ENCEN_LOSTCNT	MSK(8 ,8)
#define HDMI21_TOP_FIELD_AD_FS_MON_3_ENC_EN_EXIST	BIT(3)
#define HDMI21_TOP_FIELD_AD_FS_MON_3_IS_INTERLACED	BIT(1)

#define HDMI21_TOP_REG_AD_FS_MONITOR_4				(0x30C)

#define HDMI21_TOP_REG_AD_FS_MONITOR_5				(0x310)

#define HDMI21_TOP_REG_AD_FS_1						(0x314)
#define HDMI21_TOP_FIELD_AD_FS_1_E60B0_NEW			BIT(12)
#define HDMI21_TOP_FIELD_AD_FS_1_MODULE_RESET		BIT(11)
#define HDMI21_TOP_FIELD_AD_FS_1_BLOCK_SYNC_DE		BIT(10)
#define HDMI21_TOP_FIELD_AD_FS_1_BLOCK_SYNC_VSYNC	BIT(9)
#define HDMI21_TOP_FIELD_AD_FS_1_BLOCK_SYNC_HSYNC	BIT(8)
#define HDMI21_TOP_FIELD_AD_FS_1_BLOCK_ESM_ECC_ERR	BIT(6)
#define HDMI21_TOP_FIELD_AD_FS_1_SEND_FAKE_ECC_ESM	BIT(5)
#define HDMI21_TOP_FIELD_AD_FS_1_FAKE_VSYNC_ON		BIT(1)

#define HDMI21_TOP_REG_AD_FS_3						(0x31C)

#define HDMI21_TOP_REG_AD_FS_4						(0x320)

#define HDMI21_TOP_REG_AD_MAIN_PHY_CTRL				(0x90)
#define HDMI21_TOP_FIELD_O_REG_PHY_PDB				BIT(0)
#define HDMI21_TOP_FIELD_O_REG_PHY_ODT_PDB			BIT(4)
#define HDMI21_TOP_FIELD_O_REG_PHY_ODT_PDB_MODE_SEL BIT(8)

#define HDMI21_TOP_REG_AD_MAIN_PHY_I2C				(0x94)
#define HDMI21_TOP_FIELD_O_REG_PHY_I2C_RST_N		BIT(0)
#define HDMI21_TOP_FIELD_O_REG_PHY_I2C_DEV_ID		MSK(3, 8)

#define HDMI21_ALED_TOP_REG_AD_APB_5V_SEL			(0x50)

#define HDMI21_ALED_RC_REG_AD_HPD					(0x254)
#define HDMI21_ALED_RC_FIELD_O_REG_HPD				BIT(0)

#define HDMI21_ALED_RC_AD_EDDC_0					(0x22C)
#define HDMI21_ALED_RC_FIELD_EDDC_DISABLE			BIT(0)

#define HDMI21_TOP_REG_AD_MAIN_HPD_DDC_SET			(0x8)
#define HDMI21_TOP_FIELD_O_REG_HPD_PORT_SELECT_VAL	0x00000001		
#define HDMI21_TOP_FIELD_O_REG_HPD					BIT(4)

#define HDMI21_TOP_REG_AD_MAIN_5V_DETECT			(0x10)
#define HDMI21_TOP_FIELD_I_REG_HDMI5V_STATUS		BIT(20)

#define HDMI21_TOP_REG_AD_MAIN_COLOR_COMPONENT_ALIGN (0x14)
#define HDMI21_TOP_REG_AD_MAIN_422TO444				 (0x18)
#define HDMI21_TOP_FIELD_REG_PIX_REP_MODE			BIT(16)
/* -------------------------------------------------------------------------------------*/
/* Do not change below definition, unless if the LINK architecture has changed          */
/* -------------------------------------------------------------------------------------*/
#define HDMI21_HAL_LINK_DEVICE_ID_PORT0	0		/* For hdmi21_rx_misc.c port mapping */
#define HDMI21_HAL_LINK_DEVICE_ID_PORT1	1		/* For hdmi21_rx_misc.c port mapping */
#define HDMI21_HAL_LINK_DEVICE_ID_PORT2	2		/* For hdmi21_rx_misc.c port mapping */
#define HDMI21_HAL_LINK_DEVICE_ID_PORT3	3		/* For hdmi21_rx_misc.c port mapping */
#define HDMI21_HAL_LINK_DEVICE_ID_PORT4	4		/* For hdmi21_rx_misc.c port mapping */


#define HDMI21_HAL_INITIAL_THREAD_SLEEP_MS			20 		/* Must be greater than 10, or seg fault due to div */
#define HDMI21_HAL_VIDEO_CHECK_CNT					23		/* O20 : 20 msec * 23 tick => 460msec */
#define HDMI21_HAL_NUMBER_OF_PHY_FOR_LINK			1		/* O20 :  Each Link has one PHY */
#define HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY		4	
#define HDMI21_HAL_SIZE_OF_EDID						512		/* 512 Byte EDID support */
#define HDMI21_MAX_DATA_PACKET_LENGTH				32 		/* One packet has 32 bytes */
#define HDMI21_HAL_DRIVER_SUSPEND_TRY_COUNT			50 		/* Limit count of tries to suspend */
#define HDMI21_AMOUNT_OF_TMDS_CHANNEL_IN_ONE_PHY	4		/* Used value in Host-Error feature */
#define HDMI21_MAX_CVTEM_LENGHT						146		/* 7 Byte (PB0~6) + 136 Byte (MD 0 ~ 135) + 3 Byte (HB 0 ~ 2) */

/* ESM PUK, DUK */
#define HDMI21_PUK_ADDR_1					(0xF00)
#define HDMI21_PUK_ADDR_2					(0xF04)
#define HDMI21_PUK_ADDR_3					(0xF08)
#define HDMI21_PUK_ADDR_4					(0xF0C)

#define HDMI21_DUK_ADDR_1					(0xF10)
#define HDMI21_DUK_ADDR_2					(0xF14)
#define HDMI21_DUK_ADDR_3					(0xF18)
#define HDMI21_DUK_ADDR_4					(0xF1C)

#define HDMI21_PUK_1						(0x00112233)
#define HDMI21_PUK_2						(0x44556677)
#define HDMI21_PUK_3						(0x8899aabb)
#define HDMI21_PUK_4						(0xccddeeff)

#define HDMI21_RX_DUK_1						(0x00EEDDCC)
#define HDMI21_RX_DUK_2						(0xBBAA9988)
#define HDMI21_RX_DUK_3						(0x77665544)
#define HDMI21_RX_DUK_4						(0x33221100)


#define HDMI21_RX_VSI_TYPE_H14B_OUI_0		(0x03)
#define HDMI21_RX_VSI_TYPE_H14B_OUI_1		(0x0C)
#define HDMI21_RX_VSI_TYPE_H14B_OUI_2		(0x00)

#define HDMI21_RX_VSI_TYPE_HF_OUI_0			(0xD8)
#define HDMI21_RX_VSI_TYPE_HF_OUI_1			(0x5D)
#define HDMI21_RX_VSI_TYPE_HF_OUI_2			(0xC4)

#define HDMI21_RX_VSI_TYPE_DOLBY_OUI_0		(0x46)
#define HDMI21_RX_VSI_TYPE_DOLBY_OUI_1		(0xD0)
#define HDMI21_RX_VSI_TYPE_DOLBY_OUI_2		(0x00)

#define HDMI21_RX_DOLBY_UNIQUE_DRM_COUNT	(26)
#define HDMI21_RX_DOLBY_UNIQUE_DRM_0		(0x02)
#define HDMI21_RX_DOLBY_UNIQUE_DRM_1		(0x00)
#define HDMI21_RX_DOLBY_UNIQUE_DRM_2		(0x26) /* R_x_LSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_3		(0x8a) /* R_x_MSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_4		(0x76) /* R_y_LSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_5		(0x39) /* R_y_MSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_6		(0x08) /* G_x_LSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_7		(0x21) /* G_x_MSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_8		(0x7e) /* G_y_LSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_9		(0x9b) /* G_y_MSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_10		(0xfa) /* B_x_LSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_11		(0x19) /* B_x_MSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_12		(0x46) /* B_y_LSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_13		(0x08) /* B_y_MSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_14		(0xee) /* W_x_LSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_15		(0x3d) /* W_x_MSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_16		(0x30) /* W_y_LSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_17		(0x40) /* W_y_MSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_18		(0xe8) /* Luma_Max_LSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_19		(0x03) /* Luma_Max_MSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_20		(0x32) /* Luma_Min_LSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_21		(0x00) /* Luma_Min_MSB */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_22		(0xfe) /* Max CLL [0] */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_23		(0x03) /* Max CLL [1] */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_24		(0xaa) /* MaxFALL [0] */
#define HDMI21_RX_DOLBY_UNIQUE_DRM_25		(0x03) /* MaxFALL [1] */

/*----------------------------------------------------------------------------------------
    Type Definitions
----------------------------------------------------------------------------------------*/
typedef struct
{
	UINT32 se_os;
	UINT32 so_os;
	UINT32 te_os;
	UINT32 to_os;
	UINT32 dep_os;
	UINT32 den_os;
	UINT32 dop_os;
	UINT32 don_os;
	UINT32 eq_os;
} HDMI21_PHY_E60B0_SAFF_OFFSET_DATA_T;
	
typedef enum 
{
	HDMI21__DBG_SYNC_MONITOR_RUN_MODE,
	HDMI21__STABLE_CHECK_CNT,
	HDMI21__CLEAR_AVMUTE_BY_TIMER, 
	HDMI21__AVMUTE_HOLD_TIME,
	HDMI21__LOCAL_MUTE_HOLD_TIME,
	HDMI21__LOCAL_MUTE_HOLD_INIT_TIME,
	HDMI21__LOCAL_MUTE_HOLD_ORIGIN_TIME,
	HDMI21__DISABLE_DCM_UPDATE_FOR_LINK,
	HDMI21__ADJUST_DETECTED_4K_SYNC_WITH_HTOTAL,
	HDMI21__LINK_RESET_DELAY_TIME,
	HDMI21__VERBOSE_FOR_ABNORMAL_SYNC,
	HDMI21__TIMEOUT_FOR_PHY_LOCK_WAIT,
	HDMI21__TIMEOUT_FOR_HPD_REQUEST,
	HDMI21__VIDEO_LINE_DEBUGGER,				
	HDMI21__NUMBER_OF_ACTIVATED_LINK,
	HDMI21__HOLD_TIME_5V_DETECTION,
	HDMI21__THRESHOLD_FOR_DETECTING_HDCP14_STABILITY,
	HDMI21__COUNT_OF_RESUME,
	HDMI21__FORCE_5V_UP,
	HDMI21__FORCE_ORIGIN_TIME_FOR_3D,
	HDMI21__FORCE_SCDC_MODE,
	HDMI21__FORCE_DOLBY_DETECT_ON,
	HDMI21__PDB_LOW_ON_DISCONNECT,
	HDMI21__TIME_OF_HPD_DOWN_ON_RESTART_HPD,
	HDMI21__FORCE_HDR10_SAMPLE_PACKET,
	HDMI21__DBG_PACKET_TYPE,
	HDMI21__DBG_PACKET_LOCATION,
	HDMI21__DATAPACKET_USE_CHSUM_FILTER,
	HDMI21__FORCE_DCM_8_BIT_ON_594,
	HDMI21__HPD_TG_ON_6G_297,
	HDMI21__HPD_TG_ON_6G_297_TMDS_CLK,
	HDMI21__LINK_AMD_FREESYNC_MODE,
	HDMI21__LINK_HPD_DELAY_TIME,
	HDMI21__FORCE_COLOR_SAMPLE_PACKET,
	HDMI21__USE_MW_HOSTERROR_CTRL,
	HDMI21__ENABLE_ISR_PROFILER,
	HDMI21__ISR_PROFILER_TYPE,
	HDMI21__LINK_ALLM_TIMEOUT,
	HDMI21__LINK_DISABLE_APB_ACCESS,
	HDMI21__LINK_H_TOTAL_DIFF_THRES,
	HDMI21__LINK_H_ACTIVE_DIFF_THRES,
	HDMI21__LINK_V_TOTAL_DIFF_THRES,
	HDMI21__LINK_V_ACTIVE_DIFF_THRES,
	HDMI21__LINK_LOWEST_H_TOTAL,
	HDMI21__LINK_LOWEST_H_ACTIVE,
	HDMI21__LINK_LOWEST_V_TOTAL,
	HDMI21__LINK_LOWEST_V_ACTIVE,
	HDMI21__LINK_HIGHEST_H_TOTAL,
	HDMI21__LINK_HIGHEST_H_ACTIVE,
	HDMI21__LINK_HIGHEST_V_TOTAL,
	HDMI21__LINK_HIGHEST_V_ACTIVE,
	HDMI21__LINK_ENABLE_SCDC_POLL_TRIG,
	HDMI21__VIDEO_CHG_PRINT_INTERVAL,
	HDMI21__LINK_ENABLE_VIC_CORRECTION,
	HDMI21__FLT_RESTART_ON_CHG,
	HDMI21__VIDEO_VIC_HTOTAL_COMP_THRES,
	HDMI21__VIDEO_VIC_HACTIVE_COMP_THRES,
	HDMI21__VIDEO_VIC_VACTIVE_COMP_THRES,
	HDMI21__VIDEO_CHANGE_DETECTOR_WATCHDOG,
	HDMI21__VIDEO_UPDATE_PHY_DFE_RESULT,
	HDMI21__CHECK_VIDEO_CHG_ON_AVI_ISR,
	HDMI21__VIDEO_ENABLE_VPGEN_TOGGLE,
	HDMI21__FORCE_5V_DOWN,
	HDMI21__VIDEO_PCB_FORCE_8K_MODEL,
	HDMI21__VIDEO_PCB_IS_ONBOARD_PORT0,
	HDMI21__VIDEO_PCB_IS_ONBOARD_PORT1,
	HDMI21__VIDEO_PCB_IS_ONBOARD_PORT2,
	HDMI21__VIDEO_PCB_IS_ONBOARD_PORT3,
	HDMI21__VIDEO_PCB_IS_ONBOARD_PORT4,
	HDMI21__VIDEO_VRR_EM_TIMEOUT,
	HDMI21__VIDEO_H5D_LN_LOCK_RET,
	HDMI21__VIDEO_FRL_NO_READY_SWWA,
	HDMI21__VIDEO_FORCE_FRL_CTS_MODE,
	HDMI21__VIDEO_FORCE_PROGRES_HIGH_V,
	HDMI21__VIDEO_HPD_LOW_DURATION_ON_BOOT,
	HDMI21__VIDEO_PKTERR_DETECT_THRES,
	HDMI21__VIDEO_PKTERR_DETECT_CNT,
	HDMI21__VIDEO_H5D_8K_CHECK_HPD_SWWA,
	HDMI21__VIDEO_TICK_THRESHOLD_LOWPOWER,
	HDMI21__VIDEO_ENABLE_LOWPOWER_FOR_HDCP23,
	HDMI21__VIDEO_ENABLE_PIXEL_PACKING_WATCHDOG,
	HDMI21__VIDEO_DSC_8K5060_NUM_OF_ACITVE_C,
	HDMI21__VIDEO_DSC_8K30_NUM_OF_ACTIVE_C,
	HDMI21__VIDEO_DSC_NUM_OF_SS_OVERRIDE,
	HDMI21__VIDEO_AUTO_SCRAMBLE_FOR_HDMI20,
	HDMI21__VIDEO_LOWPOWER_LIMIT_CNT,
	HDMI21__VIDEO_LOWPOWER_LIMIT_ALLPORT,
	HDMI21__VIDEO_LOWPOWER_LOWEST_TMDSCLK,
	HDMI21__VIDEO_DOVI_PACKET_MS_TIMEOUT,
	HDMI21__VIDEO_DDCMON_ADDR_SEL,
	HDMI21__VIDEO_LOWPOWER_O22_32C_VAL,
	HDMI21__VIDEO_LOWPOWER_O22_PHY_DBG,
	HDMI21__VIDEO_DSC_CVI_HSYNC_PULSE_WIDTH,
	HDMI21__VIDEO_DSC_CORE_HSYNC_DELAY_0,
	HDMI21__VIDEO_DSC_USE_GREAT_LIM_FORMULA,
	HDMI21__VIDEO_DISCARD_SPECIFIC_CHANGES,
	HDMI21__VIDEO_TRIGGER_SCDC_CHG_WATCHDOG,
	HDMI21__VIDEO_FS_CONSIDER_HDCP2X_CASE,
	HDMI21__LINK_FORCE_QMS_MODE,
	HDMI21__VIDEO_QMS_EM_TIMEOUT,
	HDMI21__VIDEO_DBG_VFREQ_OVERRIDE,
	HDMI21__VIDEO_DSC_712M_MODE,
	HDMI21__VIDEO_FILTER_STUCK_SWWA_THRES,
	HDMI21__VIDEO_FILTER_CONSECUTIVE_STUCK,
	HDMI21__VIDEO_HPD_TOGGLE_ON_FRL_TCS_LOW,
	HDMI21__VIDEO_FILTER_STUCK_CLOCK_CONDITION,
	HDMI21__VIDEO_DSC_RESET_CORE_CLOCK,
	HDMI21__VIDEO_DSC_165_REWRITE,
	HDMI21__VIDEO_DSC_USE_CAL_VALUE,
	HDMI21__VIDEO_DSC_USE_CAL_NUM_OF_SS,
	HDMI21__VIDEO_VERBOSE_DOLBY_UNIQUE_DRM,
	HDMI21__DEV_VIDEO_CONTROL_LIST_MAXNUM
}HDMI21_DEV_VIDEO_CONTROL_LIST_T;
	
typedef enum 
{
	HDMI21__PHY_RS_GAIN_TYPE0 = 0,
	HDMI21__PHY_RS_GAIN_TYPE1,
	HDMI21__PHY_RS_GAIN_TYPE2,
	HDMI21__PHY_RS_GAIN_TYPE3,
	HDMI21__PHY_TMDS_EXCEPTIONRANGE_LOW,
	HDMI21__PHY_TMDS_EXCEPTIONRANGE_HIGH,
	HDMI21__PHY_TCS_ENABLE_RANGE_EQ,
	HDMI21__PHY_TCS_ERROR_SEL_3G,
	HDMI21__PHY_TCS_ERROR_SEL_6G,
	HDMI21__PHY_TCS_ERROR_SEL_FRL_3G,
	HDMI21__PHY_TCS_ERROR_SEL_FRL_TYPE1,
	HDMI21__PHY_TCS_ERROR_SEL_FRL_TYPE2,
	HDMI21__PHY_TCS_ERROR_SEL_FRL_TYPE3,
	HDMI21__PHY_TCS_ERROR_SEL_MODE_1_0,
	HDMI21__PHY_TCS_ERROR_SEL_MODE_2,
	HDMI21__PHY_TCS_ERROR_SEL_MODE_3,
	HDMI21__PHY_DELTA_ADD_VAL,
	HDMI21__PHY_DELTA_ADD_VAL_FRL12G,
	HDMI21__PHY_DELTA_ADD_VAL_FRL10G,
	HDMI21__PHY_DELTA_ADD_VAL_FRL3G,
	HDMI21__PHY_DELTA_ADD_VAL_TMDS6G,
	HDMI21__PHY_DELTA_ADD_VAL_TMDS3G,
	HDMI21__PHY_DELTA_ADD_VAL_FRL12G_CTS,
	HDMI21__PHY_DELTA_ADD_VAL_FRL10G_CTS,
	HDMI21__PHY_DELTA_ADD_VAL_FRL12G_ONB,
	HDMI21__PHY_DELTA_ADD_VAL_FRL10G_ONB,
	HDMI21__PHY_ENABLE_PHY_EXCEPTION_CASE,
	HDMI21__PHY_TCS_PERIOD_S_FRL12G_CTS,
	HDMI21__PHY_TCS_PERIOD_S_FRL_CTS,
	HDMI21__PHY_TCS_PERIOD_S_FRL3G_CTS,
	HDMI21__PHY_TCS_PERIOD_S_FRL12G,
	HDMI21__PHY_TCS_PERIOD_S_FRL,
	HDMI21__PHY_TCS_PERIOD_S_TMDS,
	HDMI21__PHY_TCS_SCOPE_SEL_FRL,
	HDMI21__PHY_TCS_SCOPE_SEL_TMDS,
	HDMI21__PHY_I2C_ODT_VAL,
	HDMI21__PHY_DISABLE_PHYINITIATE_API,
	HDMI21__PHY_ERROR_PERIOD_SEL,
	HDMI21__PHY_CTRL_VREF_3G,
	HDMI21__PHY_CTRL_VREF_6G,
	HDMI21__PHY_CTRL_VREF_FRL_TYPE1,
	HDMI21__PHY_CTRL_VREF_FRL_TYPE2,
	HDMI21__PHY_CTRL_VREF_FRL_TYPE3,
	HDMI21__PHY_CTRL_REG_VOUT_3G,
	HDMI21__PHY_CTRL_REG_VOUT_6G,
	HDMI21__PHY_CTRL_REG_VOUT_FRL_TYPE1,
	HDMI21__PHY_CTRL_REG_VOUT_FRL_TYPE2,
	HDMI21__PHY_CTRL_REG_VOUT_FRL_TYPE3,
	HDMI21__PHY_CTRL_REG_VOUT_CTS_TYPE2,
	HDMI21__PHY_CTRL_REG_VOUT_CTS_TYPE3,
	HDMI21__PHY_CTRL_EQICTRL_3G,		
	HDMI21__PHY_CTRL_EQICTRL_6G,
	HDMI21__PHY_CTRL_EQICTRL_FRL_TYPE1,
	HDMI21__PHY_CTRL_EQICTRL_FRL_TYPE2,
	HDMI21__PHY_CTRL_EQICTRL_FRL_TYPE3,
	HDMI21__PHY_CTRL_EQICTRL_CTS_TYPE2,
	HDMI21__PHY_CTRL_EQICTRL_CTS_TYPE3,
	HDMI21__PHY_CTRL_EQ_FREQ_DIV,
	HDMI21__PHY_DELTA_FULL_CHECK,
	HDMI21__PHY_DELTA_CHK_NSIDE,
	HDMI21__PHY_DELTA_CHK_PSIDE,
	HDMI21__PHY_ANA_CDR_SEL_MODE_2_0,
	HDMI21__PHY_ANA_CDR_SEL_MODE_3,
	HDMI21__PHY_ANA_CDR_SEL_6G,
	HDMI21__PHY_ANA_CDR_SEL_FRL_TYPE1,
	HDMI21__PHY_ANA_CDR_SEL_FRL_TYPE2,
	HDMI21__PHY_ANA_CDR_SEL_FRL_TYPE3,
	HDMI21__PHY_CDR_FLTR_CTRL_MODE_2_0,
	HDMI21__PHY_CDR_FLTR_CTRL_MODE_3,
	HDMI21__PHY_CDR_FLTR_CTRL_6G,
	HDMI21__PHY_CDR_FLTR_CTRL_FRL_TYPE1,
	HDMI21__PHY_CDR_FLTR_CTRL_FRL_TYPE2,
	HDMI21__PHY_CDR_FLTR_CTRL_FRL_TYPE3,
	HDMI21__PHY_DFE_NOT_OFF,
	HDMI21__PHY_TCS_BOUND_0,
	HDMI21__PHY_TCS_BOUND_1,
	HDMI21__PHY_TCS_BOUND_2,
	HDMI21__PHY_TCS_BOUND_3,
	HDMI21__PHY_TCS_ADD_VAL_BOUND0,
	HDMI21__PHY_TCS_ADD_VAL_BOUND1,
	HDMI21__PHY_TCS_ADD_VAL_BOUND2,
	HDMI21__PHY_TCS_ADD_VAL_BOUND3,
	HDMI21__PHY_TCS_ADD_VAL_BOUND4,
	HDMI21__PHY_EQ_AUTO_PLL_0,
	HDMI21__PHY_EQ_AUTO_PLL_1,
	HDMI21__PHY_EQ_AUTO_PLL_2,
	HDMI21__PHY_EQ_AUTO_PLL_3,
	HDMI21__PHY_DFE_DIG_ON,
	HDMI21__PHY_DFE_EVERY_CS,
	HDMI21__PHY_I2C_DFE_ON_MODE,
	HDMI21__PHY_EQ_DOHG_3G,
	HDMI21__PHY_EQ_DOHG_6G,
	HDMI21__PHY_EQ_DOHG_FRL_TYPE1,
	HDMI21__PHY_EQ_DOHG_FRL_TYPE2,
	HDMI21__PHY_EQ_DOHG_FRL_TYPE3,
	HDMI21__PHY_RETRAIN_ON_NO_LANELOCK,
	HDMI21__PHY_EQ_HDMI20_VAL_3G,
	HDMI21__PHY_EQ_HDMI20_VAL_6G,				
	HDMI21__PHY_EQ_HDMI20_VAL_FRL_TYPE1,		
	HDMI21__PHY_EQ_HDMI20_VAL_FRL_TYPE2,		
	HDMI21__PHY_EQ_HDMI20_VAL_FRL_TYPE3,	
	HDMI21__PHY_EQ_HDMI20_VAL_FRL_TYPE3_OB,
	HDMI21__PHY_EQ_HDMI20_MAN_3G,				  
	HDMI21__PHY_EQ_HDMI20_MAN_6G,				
	HDMI21__PHY_EQ_HDMI20_MAN_FRL_TYPE1,		
	HDMI21__PHY_EQ_HDMI20_MAN_FRL_TYPE2,	
	HDMI21__PHY_EQ_HDMI20_MAN_FRL_TYPE3,	
	HDMI21__PHY_EQ_PLL_MANUAL_MODE,
	HDMI21__PHY_MAN_CTRL_FB_10L_20H,
	HDMI21__PHY_MAN_CTRL_DIV2H_BPL,
	HDMI21__PHY_MAN_CTRL_RDIV,
	HDMI21__PHY_MAN_CTRL_REFCLK,
	HDMI21__PHY_MAN_CTRL_ICP,
	HDMI21__PHY_MAN_CTRL_FDIV,
	HDMI21__PHY_MAN_CTRL_PDR_5L_9H,
	HDMI21__PHY_MAN_CTRL_LFR2,
	HDMI21__PHY_MAN_CTRL_LFC2,
	HDMI21__PHY_MAN_CTRL_LFC1,
	HDMI21__PHY_EQ_DHFG_FRL_TYPE1,
	HDMI21__PHY_EQ_DHFG_FRL_TYPE2,
	HDMI21__PHY_EQ_DHFG_FRL_TYPE3,
	HDMI21__PHY_EQ_DHFG_FRL_TYPE3_ONB,
	HDMI21__PHY_EQ_FILTER_SEL_3G,
	HDMI21__PHY_EQ_FILTER_SEL_6G,
	HDMI21__PHY_EQ_FILTER_SEL_FRL_TYPE1,
	HDMI21__PHY_EQ_FILTER_SEL_FRL_TYPE2,
	HDMI21__PHY_EQ_FILTER_SEL_FRL_TYPE3,
	HDMI21__PHY_EQ_G1_SEL_3G,
	HDMI21__PHY_EQ_G1_SEL_6G,
	HDMI21__PHY_EQ_G1_SEL_FRL_TYPE1,
	HDMI21__PHY_EQ_G1_SEL_FRL_TYPE2,
	HDMI21__PHY_EQ_G1_SEL_FRL_TYPE3,
	HDMI21__PHY_EQ_G2_SEL_3G,
	HDMI21__PHY_EQ_G2_SEL_6G,
	HDMI21__PHY_EQ_G2_SEL_FRL_TYPE1,
	HDMI21__PHY_EQ_G2_SEL_FRL_TYPE2,
	HDMI21__PHY_EQ_G2_SEL_FRL_TYPE3,
	HDMI21__PHY_CED_OPEN_LENGTH_TMDS,
	HDMI21__PHY_CED_OPEN_LENGTH_FRL,
	HDMI21__PHY_TMDS_OPEN_LENGTH,
	HDMI21__PHY_SUM_BIAS_3G,
	HDMI21__PHY_SUM_BIAS_6G,
	HDMI21__PHY_SUM_BIAS_FRL_TYPE1,
	HDMI21__PHY_SUM_BIAS_FRL_TYPE2,
	HDMI21__PHY_SUM_BIAS_FRL_TYPE3,
	HDMI21__PHY_DAC_BIAS_3G,
	HDMI21__PHY_DAC_BIAS_6G,
	HDMI21__PHY_DAC_BIAS_FRL_TYPE1,
	HDMI21__PHY_DAC_BIAS_FRL_TYPE2,
	HDMI21__PHY_DAC_BIAS_FRL_TYPE3,
	HDMI21__PHY_DFE_UPDN_PERIOD_3G,
	HDMI21__PHY_DFE_UPDN_PERIOD_6G,
	HDMI21__PHY_DFE_UPDN_PERIOD_FRL_TYPE1,
	HDMI21__PHY_DFE_UPDN_PERIOD_FRL_TYPE2,
	HDMI21__PHY_DFE_UPDN_PERIOD_FRL_TYPE3,
	HDMI21__PHY_DFE_A_ON_FRL_TYPE2,
	HDMI21__PHY_DFE_B1_ON_FRL_TYPE2,
	HDMI21__PHY_DFE_B2_ON_FRL_TYPE2,
	HDMI21__PHY_DFE_B3_ON_FRL_TYPE2,
	HDMI21__PHY_DFE_B4_ON_FRL_TYPE2,
	HDMI21__PHY_DFE_B5_ON_FRL_TYPE2,
	HDMI21__PHY_DFE_A_ON_FRL_TYPE1,
	HDMI21__PHY_DFE_B1_ON_FRL_TYPE1,
	HDMI21__PHY_DFE_B2_ON_FRL_TYPE1,
	HDMI21__PHY_DFE_B3_ON_FRL_TYPE1,
	HDMI21__PHY_DFE_B4_ON_FRL_TYPE1,
	HDMI21__PHY_DFE_B5_ON_FRL_TYPE1,
	HDMI21__PHY_I2C_DFE_LEV_B1_MODE_FRL10,
	HDMI21__PHY_I2C_DFE_LEVEL_B1_MODE,
	HDMI21__PHY_I2C_DFE_LEVEL_B2_MODE,
	HDMI21__PHY_I2C_DFE_LEVEL_B3_MODE,
	HDMI21__PHY_I2C_DFE_LEVEL_B4_MODE,
	HDMI21__PHY_I2C_DFE_LEVEL_B5_MODE,
	HDMI21__PHY_I2C_DFE_B1_LEVEL_LN0,
	HDMI21__PHY_I2C_DFE_B2_LEVEL_LN0,
	HDMI21__PHY_I2C_DFE_B3_LEVEL_LN0,
	HDMI21__PHY_I2C_DFE_B4_LEVEL_LN0,
	HDMI21__PHY_I2C_DFE_B5_LEVEL_LN0,
	HDMI21__PHY_I2C_DFE_B1_LEVEL_LN1,
	HDMI21__PHY_I2C_DFE_B2_LEVEL_LN1,
	HDMI21__PHY_I2C_DFE_B3_LEVEL_LN1,
	HDMI21__PHY_I2C_DFE_B4_LEVEL_LN1,
	HDMI21__PHY_I2C_DFE_B5_LEVEL_LN1,
	HDMI21__PHY_I2C_DFE_B1_LEVEL_LN2,
	HDMI21__PHY_I2C_DFE_B2_LEVEL_LN2,
	HDMI21__PHY_I2C_DFE_B3_LEVEL_LN2,
	HDMI21__PHY_I2C_DFE_B4_LEVEL_LN2,
	HDMI21__PHY_I2C_DFE_B5_LEVEL_LN2,
	HDMI21__PHY_I2C_DFE_B1_LEVEL_LN3,
	HDMI21__PHY_I2C_DFE_B2_LEVEL_LN3,
	HDMI21__PHY_I2C_DFE_B3_LEVEL_LN3,
	HDMI21__PHY_I2C_DFE_B4_LEVEL_LN3,
	HDMI21__PHY_I2C_DFE_B5_LEVEL_LN3,
	HDMI21__PHY_FLT_TIMER_2000_11_8,
	HDMI21__PHY_FLT_TIMER_2000_7_0,
	HDMI21__PHY_I2C_DELTA_EN_MODE,
	HDMI21__PHY_I2C_DELTA_EN_VAL,
	HDMI21__PHY_DELTA_SCAN2_MODE,
	HDMI21__PHY_ADAPTIVE_PERIOD_3GTMDS,
	HDMI21__PHY_ADAPTIVE_PERIOD_SEL_3GTMDS,
	HDMI21__PHY_ADAPTIVE_PERIOD_6G_FRL,
	HDMI21__PHY_ADAPTIVE_PERIOD_SEL_6G_FRL,
	HDMI21__PHY_DFE_N1_3G,
	HDMI21__PHY_DFE_N1_6G,
	HDMI21__PHY_DFE_N1_FRL_TYPE1,
	HDMI21__PHY_DFE_N1_FRL_TYPE2,
	HDMI21__PHY_DFE_N1_FRL_TYPE3,
	HDMI21__PHY_DFE_N2_3G,
	HDMI21__PHY_DFE_N2_6G,
	HDMI21__PHY_DFE_N2_FRL_TYPE1,
	HDMI21__PHY_DFE_N2_FRL_TYPE2,
	HDMI21__PHY_DFE_N2_FRL_TYPE3,
	HDMI21__PHY_DFE_N2_ON_3G,
	HDMI21__PHY_DFE_N2_ON_6G,
	HDMI21__PHY_DFE_N2_ON_FRL_TYPE1,
	HDMI21__PHY_DFE_N2_ON_FRL_TYPE2,
	HDMI21__PHY_DFE_N2_ON_FRL_TYPE3,
	HDMI21__PHY_DFE_UPDN_PRE_3G,
	HDMI21__PHY_DFE_UPDN_PRE_6G,
	HDMI21__PHY_DFE_UPDN_PRE_FRL_TYPE1,
	HDMI21__PHY_DFE_UPDN_PRE_FRL_TYPE2,
	HDMI21__PHY_DFE_UPDN_PRE_FRL_TYPE3,
	HDMI21__PHY_DFE_IDR_ADJ_3G,
	HDMI21__PHY_DFE_IDR_ADJ_6G,
	HDMI21__PHY_DFE_IDR_ADJ_FRL_TYPE1,
	HDMI21__PHY_DFE_IDR_ADJ_FRL_TYPE2,
	HDMI21__PHY_DFE_IDR_ADJ_FRL_TYPE3,
	HDMI21__PHY_DELTA_M_AD_3G,
	HDMI21__PHY_DELTA_M_AD_6G,
	HDMI21__PHY_DELTA_M_AD_FRL_TYPE1,
	HDMI21__PHY_DELTA_M_AD_FRL_TYPE2,
	HDMI21__PHY_DELTA_M_AD_FRL_TYPE3,
	HDMI21__PHY_DELTA_M_AD_CTS_TYPE1,
	HDMI21__PHY_DELTA_M_AD_CTS_TYPE2,
	HDMI21__PHY_DELTA_M_AD_CTS_TYPE3,
	HDMI21__PHY_TCS_STATE_HIST_DEPTH,
	HDMI21__PHY_TCS_STATE_HIST_MATCH,
	HDMI21__PHY_FLT_STATE_MATCH,
	HDMI21__PHY_CH0_SSB_CHECK_ON,
	HDMI21__PHY_FRL_EQ_SWWA_OPTION_1,
	HDMI21__PHY_FRL_EQ_SWWA_OPTION_2,
	HDMI21__PHY_FRL_EQ_SWWA_OPTION_3,
	HDMI21__PHY_DFE_CENTER_SWWA,	
	HDMI21__PHY_DFE_CENTER_SWWA_ROUND_UP,
	HDMI21__PHY_RS_GAIN_TYPE0_ONBOARD,
	HDMI21__PHY_RS_GAIN_TYPE1_ONBOARD,
	HDMI21__PHY_RS_GAIN_TYPE2_ONBOARD,
	HDMI21__PHY_RS_GAIN_TYPE3_ONBOARD,
	HDMI21__PHY_EQICTRL_3G_ONBOARD,		
	HDMI21__PHY_EQICTRL_6G_ONBOARD,
	HDMI21__PHY_EQICTRL_FRL_TYPE1_ONBOARD,
	HDMI21__PHY_EQICTRL_FRL_TYPE2_ONBOARD,
	HDMI21__PHY_EQICTRL_FRL_TYPE3_ONBOARD,
	HDMI21__PHY_CTRL_VREF_3G_ONBOARD,
	HDMI21__PHY_CTRL_VREF_6G_ONBOARD,
	HDMI21__PHY_CTRL_VREF_FRL_TYPE1_ONBOARD,
	HDMI21__PHY_CTRL_VREF_FRL_TYPE2_ONBOARD,
	HDMI21__PHY_CTRL_VREF_FRL_TYPE3_ONBOARD,
	HDMI21__PHY_SUM_BIAS_3G_ONBOARD,
	HDMI21__PHY_SUM_BIAS_6G_ONBOARD,
	HDMI21__PHY_SUM_BIAS_FRL_TYPE1_ONBOARD,
	HDMI21__PHY_SUM_BIAS_FRL_TYPE2_ONBOARD,
	HDMI21__PHY_SUM_BIAS_FRL_TYPE3_ONBOARD,
	HDMI21__PHY_CTRL_RBIAS_FRL_TYPE3,
	HDMI21__PHY_CTRL_RBIAS_FRL_TYPE2,
	HDMI21__PHY_CTRL_RBIAS,
	HDMI21__PHY_CTRL_RBIAS_CTS_MODE,
	HDMI21__PHY_PHANTOM_MAN_VAL,
	HDMI21__PHY_PHANTOM_FIXED_MODE,
	HDMI21__PHY_RS_GAIN_CTS_TYPE1_CH0,
	HDMI21__PHY_RS_GAIN_CTS_TYPE1_CH1,
	HDMI21__PHY_RS_GAIN_CTS_TYPE1_CH2,
	HDMI21__PHY_RS_GAIN_CTS_TYPE1_CH3,
	HDMI21__PHY_RS_GAIN_CTS_TYPE2_CH0,
	HDMI21__PHY_RS_GAIN_CTS_TYPE2_CH1,
	HDMI21__PHY_RS_GAIN_CTS_TYPE2_CH2,
	HDMI21__PHY_RS_GAIN_CTS_TYPE2_CH3,
	HDMI21__PHY_RS_GAIN_CTS_TYPE3_CH0,
	HDMI21__PHY_RS_GAIN_CTS_TYPE3_CH1,
	HDMI21__PHY_RS_GAIN_CTS_TYPE3_CH2,
	HDMI21__PHY_RS_GAIN_CTS_TYPE3_CH3,
	HDMI21__PHY_DFE_ADD_VAL_ON_CTS,
	HDMI21__PHY_P0_ENABLE_MANUAL_EQ,
	HDMI21__PHY_P0_MANUAL_CS_VAL_CH0,
	HDMI21__PHY_P0_MANUAL_CS_VAL_CH1,
	HDMI21__PHY_P0_MANUAL_CS_VAL_CH2,
	HDMI21__PHY_P0_MANUAL_CS_VAL_CH3,
	HDMI21__PHY_P1_ENABLE_MANUAL_EQ,
	HDMI21__PHY_P1_MANUAL_CS_VAL_CH0,
	HDMI21__PHY_P1_MANUAL_CS_VAL_CH1,
	HDMI21__PHY_P1_MANUAL_CS_VAL_CH2,
	HDMI21__PHY_P1_MANUAL_CS_VAL_CH3,
	HDMI21__PHY_P2_ENABLE_MANUAL_EQ,
	HDMI21__PHY_P2_MANUAL_CS_VAL_CH0,
	HDMI21__PHY_P2_MANUAL_CS_VAL_CH1,
	HDMI21__PHY_P2_MANUAL_CS_VAL_CH2,
	HDMI21__PHY_P2_MANUAL_CS_VAL_CH3,
	HDMI21__PHY_P3_ENABLE_MANUAL_EQ,
	HDMI21__PHY_P3_MANUAL_CS_VAL_CH0,
	HDMI21__PHY_P3_MANUAL_CS_VAL_CH1,
	HDMI21__PHY_P3_MANUAL_CS_VAL_CH2,
	HDMI21__PHY_P3_MANUAL_CS_VAL_CH3,
	HDMI21__PHY_P4_ENABLE_MANUAL_EQ,
	HDMI21__PHY_P4_MANUAL_CS_VAL_CH0,
	HDMI21__PHY_P4_MANUAL_CS_VAL_CH1,
	HDMI21__PHY_P4_MANUAL_CS_VAL_CH2,
	HDMI21__PHY_P4_MANUAL_CS_VAL_CH3,
	HDMI21__PHY_E60_I2C_DDELTA_MODE_CH0,
	HDMI21__PHY_E60_I2C_DDELTA_MODE_CH1,
	HDMI21__PHY_E60_I2C_DDELTA_MODE_CH2,
	HDMI21__PHY_E60_I2C_DDELTA_MODE_CH3,
	HDMI21__PHY_E60_I2C_DDELTA_CH0,
	HDMI21__PHY_E60_I2C_DDELTA_CH1,
	HDMI21__PHY_E60_I2C_DDELTA_CH2,
	HDMI21__PHY_E60_I2C_DDELTA_CH3,
	HDMI21__PHY_E60_I2C_DATA_SIGN,
	HDMI21__PHY_E60_PAT_FILTER_SEL,
	HDMI21__PHY_E60_CED_CHK_BYPASS,
	HDMI21__PHY_E60_DFE_DELTA_ON,
	HDMI21__PHY_E60_DFE_NEW_M,
	HDMI21__PHY_E60_DFE_NEW_CHAR,
	//E60B0
	HDMI21__PHY_E60_EQ_RS_MAN_CH0_CTS_TYPE3,
    HDMI21__PHY_E60_EQ_RS_MAN_CH1_CTS_TYPE3,
    HDMI21__PHY_E60_EQ_RS_MAN_CH2_CTS_TYPE3,
    HDMI21__PHY_E60_EQ_RS_MAN_CH3_CTS_TYPE3,
    HDMI21__PHY_E60_EQ_RS_MAN_CH0_CTS_TYPE2,
    HDMI21__PHY_E60_EQ_RS_MAN_CH1_CTS_TYPE2,
    HDMI21__PHY_E60_EQ_RS_MAN_CH2_CTS_TYPE2,
    HDMI21__PHY_E60_EQ_RS_MAN_CH3_CTS_TYPE2,
	HDMI21__PHY_E60_EQ_RS_MAN_CH0_FRL_TYPE3,
	HDMI21__PHY_E60_EQ_RS_MAN_CH1_FRL_TYPE3,
	HDMI21__PHY_E60_EQ_RS_MAN_CH2_FRL_TYPE3,
	HDMI21__PHY_E60_EQ_RS_MAN_CH3_FRL_TYPE3,
	HDMI21__PHY_E60_EQ_RS_MAN_CH0_FRL_TYPE2,
	HDMI21__PHY_E60_EQ_RS_MAN_CH1_FRL_TYPE2,
	HDMI21__PHY_E60_EQ_RS_MAN_CH2_FRL_TYPE2,
	HDMI21__PHY_E60_EQ_RS_MAN_CH3_FRL_TYPE2,
	HDMI21__PHY_E60_EQ_RS_MAN_CH0_FRL_TYPE1,
	HDMI21__PHY_E60_EQ_RS_MAN_CH1_FRL_TYPE1,
	HDMI21__PHY_E60_EQ_RS_MAN_CH2_FRL_TYPE1,
	HDMI21__PHY_E60_EQ_RS_MAN_CH3_FRL_TYPE1,
	HDMI21__PHY_E60_EQ_RS_MAN_CH0_6G,
	HDMI21__PHY_E60_EQ_RS_MAN_CH1_6G,
	HDMI21__PHY_E60_EQ_RS_MAN_CH2_6G,
	HDMI21__PHY_E60_EQ_RS_MAN_CH3_6G,
	HDMI21__PHY_E60_EQ_RS_MAN_CH0_3G,
	HDMI21__PHY_E60_EQ_RS_MAN_CH1_3G,
	HDMI21__PHY_E60_EQ_RS_MAN_CH2_3G,
	HDMI21__PHY_E60_EQ_RS_MAN_CH3_3G,
	HDMI21__PHY_E60_CR_MAN_HDMI20,
	HDMI21__PHY_E60_CR_MAN_HDMI20_6G,
	HDMI21__PHY_E60_CR_I2C_HDMI21_MODE,
	HDMI21__PHY_E60_CR_MAN_HDMI21_FRL,
	HDMI21__PHY_E60_CR_MAN_HDMI21_TMDS,
	HDMI21__PHY_E60_SCR_MAN_MODE,
	HDMI21__PHY_E60_SCR_MAN_VAL,
	HDMI21__PHY_E60_SCR_MAN_VAL_3G,
	HDMI21__PHY_E60_DR_CLKGEN_CAPENB_HDMI14,
	HDMI21__PHY_E60_DR_CLKGEN_CAPENB_HDMI20,
	HDMI21__PHY_E60_DR_CLKGEN_CAPENB_FRL_RATE1,
	HDMI21__PHY_E60_DR_CLKGEN_CAPENB_FRL_RATE2_4,
	HDMI21__PHY_E60_DR_CLKGEN_CAPENB_FRL_RATE5,
	HDMI21__PHY_E60_DR_CLKGEN_CAPENB_FRL_RATE6,
	HDMI21__PHY_E60_EQ_RS_MODE_SEL,
	HDMI21__PHY_E60_RS_SCAN_MODE,
	HDMI21__PHY_E60_RS_SCAN_CAL_NUM,
	HDMI21__PHY_E60_RS_DATA_NUM, 
	HDMI21__PHY_E60_EQ_CAL_RS_TARGET, 
	HDMI21__PHY_E60_EQ_CAL_RS_MODE,
	HDMI21__PHY_E60_RS_SCAN_PRE, 
	HDMI21__PHY_E60_RS_SCAN_MEAS_11_8, 
	HDMI21__PHY_E60_RS_SCAN_MEAS_7_0,
	HDMI21__PHY_E60_RS_SCAN_LEVEL_A_11,
	HDMI21__PHY_E60_DFE_B1_FILTER_SEL,
	HDMI21__PHY_E60_DFE_MINUS_ON,
	HDMI21__PHY_E60_DFE_B1_MINUS,
	HDMI21__PHY_E60_DFE_ALPHA_MIN_CAL,
	HDMI21__PHY_E60_SIGN_PATH_B1_ON,
	HDMI21__PHY_E60_CR_I2C_PLL_MODE_M,
	HDMI21__PHY_E60_CR_MAN_PLL_MODE_M,
	HDMI21__PHY_E60_CR_MAN_CTRL_REFCLK,
	HDMI21__PHY_E60_CR_MAN_CTRL_RDIV,
	HDMI21__PHY_E60_CR_MAN_CTRL_DIV2H_BPL,
	HDMI21__PHY_E60_CR_MAN_CTRL_FB_10L_20H,
	HDMI21__PHY_E60_CR_MAN_CTRL_FDIV,
	HDMI21__PHY_E60_CR_MAN_CTRL_ICP,
	HDMI21__PHY_E60_CR_MAN_CTRL_LFC1,
	HDMI21__PHY_E60_CR_MAN_CTRL_LFC2,
	HDMI21__PHY_E60_CR_MAN_CTRL_LFR2,
	HDMI21__PHY_E60_CR_MAN_CTRL_PDR_5L_9H,
	HDMI21__PHY_E60_CTRL_SEL_CRREF,
	HDMI21__PHY_E60_ERR_OPTION,
	HDMI21__PHY_E60_DELTA_REPEAT_MODE,
	HDMI21__PHY_E60_DELTA_REPEAT_NONE,
	HDMI21__PHY_E60_DELTA_DOWN_GAP, 
	HDMI21__PHY_E60_DELTA_PEREAT_MAX,
	HDMI21__PHY_E60_VIDEO_DATA_CNT,
	HDMI21__PHY_E60_SWWA_2SCOMPLIMENT_BUG,
	HDMI21__PHY_E60_SWWA_2SCOMPLIMENT_M1_THR,
	HDMI21__PHY_E60_DELTA_CUTLINE_TYPE3,
	HDMI21__PHY_E60_DELTA_CUTLINE_TYPE2,
	HDMI21__PHY_E60_DELTA_CUTLINE_TYPE1,
	HDMI21__PHY_E60_DELTA_CUTLINE_6G,
	HDMI21__PHY_E60_DELTA_CUTLINE_3G,
	HDMI21__PHY_E60_FLT_PRE_CHK_MODE,
	HDMI21__PHY_E60_G2_RESET_OPTION,
	HDMI21__PHY_E60_DFE_DELTA_OPTION,
	HDMI21__PHY_E60_DFE_DELTA_ON_M_M,
	HDMI21__PHY_E60_DFE_DELTA_ON_MAN,
	HDMI21__PHY_E60_DFE_DELTA_SCOPE2,
	HDMI21__PHY_E60_DFE_DONE_BYPASS,
	HDMI21__PHY_E60_PI_SET_MAN_MODE_FRL_TYPE3,
	HDMI21__PHY_E60_PI_SET_MAN_VAL_FRL_TYPE3,
	HDMI21__PHY_E60_PI_SET_MAN_MODE_FRL_TYPE2,
	HDMI21__PHY_E60_PI_SET_MAN_VAL_FRL_TYPE2,
	HDMI21__PHY_E60_PI_SET_MAN_MODE_FRL_TYPE1,
	HDMI21__PHY_E60_PI_SET_MAN_VAL_FRL_TYPE1,
	HDMI21__PHY_E60_PI_SET_MAN_MODE_6G,
	HDMI21__PHY_E60_PI_SET_MAN_VAL_6G,
	HDMI21__PHY_E60_PI_SET_MAN_MODE_3G,
	HDMI21__PHY_E60_PI_SET_MAN_VAL_3G,
	HDMI21__PHY_TCS_ERR_LIMIT_BASIC_FRL_TYPE3_CTS,
	HDMI21__PHY_TCS_ERR_LIMIT_BASIC_FRL_TYPE2_CTS,
	HDMI21__PHY_TCS_ERR_LIMIT_BASIC_FRL_TYPE3,
	HDMI21__PHY_TCS_ERR_LIMIT_BASIC_FRL_TYPE2,
	HDMI21__PHY_TCS_ERR_LIMIT_BASIC,
	HDMI21__PHY_TCS_ERR_LIMIT_LOOSE,
	HDMI21__PHY_E60_CTRL_EQ_DT_RANGE,
	HDMI21__PHY_O22_STUDY,
	HDMI21__PHY_ONBOARD_MAN_TCS_VAL_MINUS,
	HDMI21__PHY_RETRAIN_NO_LANELOCK_TCSLOW,
	HDMI21__PHY_FRL_CAL_CLOCK_SPEED_UP,
	HDMI21__PHY_RS_SCAN_RETRY_DISABLE,
	HDMI21__PHY_RS_SCAN_RETRY_COUNT,
	HDMI21__PHY_RS_SCAN_RETRY_DIFF,
	HDMI21__PHY_EQ_SUCCESS_SEL_VAL,
	HDMI21__DEV_PHY_CONTROL_LIST_MAXNUM
}HDMI21_DEV_PHY_CONTROL_LIST_T;

typedef enum 
{
	HDMI21__LINK_VMON_SOURCE_TYPE_TMDS,
	HDMI21__LINK_VMON_SOURCE_TYPE_FRL,
	HDMI21__LINK_VMON_IRQ_THR_MODE,
	HDMI21__LINK_ISRUNIT_ISRVAL_HDCP_1_INTVEC,
	HDMI21__LINK_ISRUNIT_ISRVAL_HDCP_INTVEC,
	HDMI21__LINK_ISRUNIT_ISRVAL_SCDC_INTVEC,
	HDMI21__LINK_ISRUNIT_ISRVAL_PKT_2_INTVEC,
	HDMI21__LINK_ISRUNIT_ISRVAL_PKT_1_INTVEC,
	HDMI21__LINK_ISRUNIT_ISRVAL_PKT_0_INTVEC,
	HDMI21__LINK_ISRUNIT_ISRVAL_AVPUNIT_2_INTVEC,
	HDMI21__LINK_ISRUNIT_ISRVAL_AVPUNIT_1_INTVEC_T,
	HDMI21__LINK_ISRUNIT_ISRVAL_AVPUNIT_1_INTVEC_F,
	HDMI21__LINK_ISRUNIT_ISRVAL_AVPUNIT_1_INTVEC_T_A,
	HDMI21__LINK_ISRUNIT_ISRVAL_AVPUNIT_1_INTVEC_F_A,
	HDMI21__LINK_ISRUNIT_ISRVAL_AVPUNIT_0_INTVEC,
	HDMI21__LINK_ISRUNIT_ISRVAL_MAINUNIT_2_INTVEC,
	HDMI21__LINK_ISRUNIT_ISRVAL_MAINUNIT_1_INTVEC,
	HDMI21__LINK_ISRUNIT_ISRVAL_MAINUNIT_0_INTVEC,
	HDMI21__LINK_ISRUNIT_ISRVAL_EARC_INTVEC,
	HDMI21__LINK_VIDCHANGE_ISRMASK_HDCP_1,
	HDMI21__LINK_VIDCHANGE_ISRMASK_HDCP,
	HDMI21__LINK_VIDCHANGE_ISRMASK_SCDC,
	HDMI21__LINK_VIDCHANGE_ISRMASK_PKT_2,
	HDMI21__LINK_VIDCHANGE_ISRMASK_PKT_1,
	HDMI21__LINK_VIDCHANGE_ISRMASK_PKT_0,
	HDMI21__LINK_VIDCHANGE_ISRMASK_AVPUNIT_2,
	HDMI21__LINK_VIDCHANGE_ISRMASK_AVPUNIT_1,
	HDMI21__LINK_VIDCHANGE_ISRMASK_AVPUNIT_0,
	HDMI21__LINK_VIDCHANGE_ISRMASK_MAINUNIT_2,
	HDMI21__LINK_VIDCHANGE_ISRMASK_MAINUNIT_1,
	HDMI21__LINK_VIDCHANGE_ISRMASK_MAINUNIT_0,
	HDMI21__LINK_VIDMUTE_ISRMASK_HDCP_1,
	HDMI21__LINK_VIDMUTE_ISRMASK_HDCP,
	HDMI21__LINK_VIDMUTE_ISRMASK_SCDC,
	HDMI21__LINK_VIDMUTE_ISRMASK_PKT_2,
	HDMI21__LINK_VIDMUTE_ISRMASK_PKT_1,
	HDMI21__LINK_VIDMUTE_ISRMASK_PKT_0,
	HDMI21__LINK_VIDMUTE_ISRMASK_AVPUNIT_2,
	HDMI21__LINK_VIDMUTE_ISRMASK_AVPUNIT_1,
	HDMI21__LINK_VIDMUTE_ISRMASK_AVPUNIT_0,
	HDMI21__LINK_VIDMUTE_ISRMASK_MAINUNIT_2,
	HDMI21__LINK_VIDMUTE_ISRMASK_MAINUNIT_1,
	HDMI21__LINK_VIDMUTE_ISRMASK_MAINUNIT_0,
	HDMI21__LINK_AUDCHANGE_ISRMASK_HDCP_1,
	HDMI21__LINK_AUDCHANGE_ISRMASK_HDCP,
	HDMI21__LINK_AUDCHANGE_ISRMASK_SCDC,
	HDMI21__LINK_AUDCHANGE_ISRMASK_PKT_2,
	HDMI21__LINK_AUDCHANGE_ISRMASK_PKT_1,
	HDMI21__LINK_AUDCHANGE_ISRMASK_PKT_0,
	HDMI21__LINK_AUDCHANGE_ISRMASK_AVPUNIT_2,
	HDMI21__LINK_AUDCHANGE_ISRMASK_AVPUNIT_1,
	HDMI21__LINK_AUDCHANGE_ISRMASK_AVPUNIT_0,
	HDMI21__LINK_AUDCHANGE_ISRMASK_MAINUNIT_2,
	HDMI21__LINK_AUDCHANGE_ISRMASK_MAINUNIT_1,
	HDMI21__LINK_AUDCHANGE_ISRMASK_MAINUNIT_0,
	HDMI21__LINK_AUDMUTE_ISRMASK_HDCP_1,
	HDMI21__LINK_AUDMUTE_ISRMASK_HDCP,
	HDMI21__LINK_AUDMUTE_ISRMASK_SCDC,
	HDMI21__LINK_AUDMUTE_ISRMASK_PKT_2,
	HDMI21__LINK_AUDMUTE_ISRMASK_PKT_1,
	HDMI21__LINK_AUDMUTE_ISRMASK_PKT_0,
	HDMI21__LINK_AUDMUTE_ISRMASK_AVPUNIT_2,
	HDMI21__LINK_AUDMUTE_ISRMASK_AVPUNIT_1,
	HDMI21__LINK_AUDMUTE_ISRMASK_AVPUNIT_0,
	HDMI21__LINK_AUDMUTE_ISRMASK_MAINUNIT_2,
	HDMI21__LINK_AUDMUTE_ISRMASK_MAINUNIT_1,
	HDMI21__LINK_AUDMUTE_ISRMASK_MAINUNIT_0,
	HDMI21__LINK_PFIFO_ENABLE_MASK,
	HDMI21__LINK_PFIFO_PASS_THRESHOLD,
	HDMI21__LINK_PFIFO_LOW_THRESHOLD,
	HDMI21__LINK_PFIFO_HIGH_THRESHOLD,
	HDMI21__LINK_HDCP_HDCP14DELAY_VAL,
	HDMI21__LINK_MISC_MAIN_HARD_RESET_VAL,
	HDMI21__LINK_MISC_MAIN_SOFT_RESET_VAL,
	HDMI21__LINK_MISC_RESET_ON_TCS_TOGGLE,
	HDMI21__LINK_MISC_RESET_ON_TCS_DONE_VAL,
	HDMI21__LINK_PDEC_USE_PKT_SNAPSHOT,
	HDMI21__LINK_VPROC_FRLSYNC_HSYNC_4L,
	HDMI21__LINK_VPROC_FRLSYNC_HFRONT_4L,
	HDMI21__LINK_VPROC_FRLSYNC_HSYNC_3L,
	HDMI21__LINK_VPROC_FRLSYNC_HFRONT_3L,
	HDMI21__LINK_VPROC_FRLSYNC_VSYNC,
	HDMI21__LINK_VPROC_FRLSYNC_VFRONT,
	HDMI21__LINK_FRL_START_CHK_SB_QST,
	HDMI21__LINK_HDMI_TO_DVI_THRESHOLD,
	HDMI21__LINK_DVI_TO_HDMI_THRESHOLD,
	HDMI21__LINK_FRL_DEFRAMER_PREAMBLE_LOCK,
	HDMI21__LINK_CRG_FIFO_RESET_HIGH_VAL,
	HDMI21__LINK_CRG_FIFO_RESET_LOW_VAL,
	HDMI21__LINK_TOP_SCDC_ISR_MASK,
	HDMI21__LINK_FRLSYNCGEN_OVRRIDE_EN, 
	HDMI21__LINK_FRLSYNCGEN_OVR_VIDCONFIG1,
	HDMI21__LINK_FRLSYNCGEN_OVR_CONFIG1,
	HDMI21__LINK_FRLSYNCGEN_OVR_CONFIG2,
	HDMI21__LINK_FRLSYNCGEN_OVR_CONFIG3,
	HDMI21__LINK_FRLSYNCGEN_OVR_CONFIG4,
	HDMI21__LINK_FRLSYNCGEN_OVR_CONFIG5,
	HDMI21__LINK_FRLSYNCGEN_FOR_DSC,
	HDMI21__LINK_FRLSYNCGEN_VS_ZERO_FOR_DSC,
	HDMI21__LINK_FRLSYNCGEN_VS_ZERO_FOR_GEN1,
	HDMI21__LINK_FRLSYNCGEN_DEFAULT_MODE,
	HDMI21__LINK_FRLSYNCGEN_HS_ZERO_FOR_GEN1,
	HDMI21__LINK_FRLSYNCGEN_OFF_FOR_UNDER,
	HDMI21__LINK_FRLSYNCGEN_GENVAL_OVR,
	HDMI21__LINK_FRLSYNCGEN_VBCONST_HACT,
	HDMI21__LINK_O22_FRLSYNCGEN_VFRONTSYNC,
	HDMI21__LINK_FRLSYNCGEN_DSC_REDUCE_HBACK,
	HDMI21__LINK_FRLSYNCGEN_VBCONST_ZERO_FORCE,
	HDMI21__LINK_DSC_LIMS_HSYNCDELAY0_FACTOR,
	HDMI21__LINK_DSC_LIMS_ALLOW_EXCEPTION,
	HDMI21__LINK_PDEC_AVMUTE_AUTO_CLEAR_TIME,
	HDMI21__LINK_PDEC_AVMUTE_AUTO_CLEAR_ENABLE,
	HDMI21__LINK_MISC_DATAPATH_RST_ON_UNSTABLE,
	HDMI21__LINK_DATAPATH_ONLY_RST_ON_REAUTH,
	HDMI21__LINK_USE_LINK_VFREQ_COUNTER,
	HDMI21__LINK_DELAY_TO_EQ_SUCCESS_SEL,
	HDMI21__LINK_RST_HDMI_SYN_FOR_CLK_LOSS,
	HDMI21__LINK_FAULT_INJECTION_VFREQ_COUNT,
	HDMI21__LINK_FRL12G4L_480P_12B_FORCE_WA,
	HDMI21__LINK_TEST_SCDC_ERROR_FLAT_ENJECT,
	HDMI21__LINK_DSC_RESTORE_SYNC_GEN_MODE,
	HDMI21__LINK_WATCHDOG_VRR_VFREQ_WITH_MEASURE,
	HDMI21__DEV_LINK_CONTROL_LIST_MAXNUM
}HDMI21_DEV_LINK_CONTROL_LIST_T;

/* IRQ Type */
typedef enum {
	/* Main Unit 0 */
	HDMI21_IRQ_LINK_REGBANK_READY_IRQ,
	HDMI21_IRQ_LINK_APB_IF_READY_IRQ,
	HDMI21_IRQ_CDSENSE_CHG_MASK_N,
	HDMI21_IRQ_LINK_TIMER_BASE_LOCKED_IRQ,
	HDMI21_IRQ_LINK_EARC_BPCLK_OFF_CHG_IRQ,
	HDMI21_IRQ_LINK_EARC_BPCLK_LOCKED_CHG_IRQ,
	HDMI21_IRQ_LINK_EARC_AUDCLK_OFF_CHG_IRQ,
	HDMI21_IRQ_LINK_EARC_AUDCLK_LOCKED_CHG_IRQ,
	HDMI21_IRQ_LINK_FRLCLK_OFF_CHG_IRQ,
	HDMI21_IRQ_LINK_FRLCLK_LOCKED_CHG_IRQ,
	HDMI21_IRQ_LINK_TMDSQPCLK_OFF_CHG_IRQ,
	HDMI21_IRQ_LINK_TMDSQPCLK_LOCKED_CHG_IRQ,
	HDMI21_IRQ_LINK_AUDCLK_OFF_CHG_IRQ,
	HDMI21_IRQ_LINK_AUDCLK_LOCKED_CHG_IRQ,
	/* Main Unit 1 */
	HDMI21_IRQ_LINK_DDC_SCDC_ACTIVITY_IRQ,
	HDMI21_IRQ_LINK_DDC_HDCP_ACTIVITY_IRQ,
	HDMI21_IRQ_LINK_EARCTX_POWERED_DOWN_IRQ,
	HDMI21_IRQ_LINK_EARCTX_POWERED_UP_IRQ,
	HDMI21_IRQ_LINK_CEC_POWERED_DOWN_IRQ,
	HDMI21_IRQ_LINK_CEC_POWERED_UP_IRQ,
	HDMI21_IRQ_LINK_AVPUNIT_POWERED_DOWN_IRQ,
	HDMI21_IRQ_LINK_AVPUNIT_POWERED_UP_IRQ,
	/* Main Unit 2 */
	HDMI21_IRQ_LINK_PHYCREG_CR_TIMEOUT_IRQ,
	HDMI21_IRQ_LINK_PHYCREG_CR_READ_DONE_IRQ,
	HDMI21_IRQ_LINK_PHYCREG_CR_WRITE_DONE_IRQ,
	HDMI21_IRQ_LINK_PHYCREG_CR_SELECTOR_DONE_IRQ,
	HDMI21_IRQ_LINK_PHYCREG_CR_SELECTIONMODE_DONE_IRQ,
	HDMI21_IRQ_LINK_EARC_BPCLK_VALID_STABLE_CHG_IRQ,
	HDMI21_IRQ_LINK_TMDSVALID_STABLE_CHG_IRQ,
	HDMI21_IRQ_LINK_AUDPLL_LOCK_STABLE_CHG_IRQ,
	/* AVP Unit 0 */
	HDMI21_IRQ_LINK_CED_DYN_CNT_CH2_IRQ,
	HDMI21_IRQ_LINK_CED_DYN_CNT_CH1_IRQ,
	HDMI21_IRQ_LINK_CED_DYN_CNT_CH0_IRQ,
	HDMI21_IRQ_LINK_DESCRAND_SYNC_SEQ_ERR_IRQ,
	HDMI21_IRQ_LINK_DESCRAND_SYNC_IRQ,
	/* AVP Unit 1 */
	HDMI21_IRQ_LINK_VMON_VMEAS_IRQ,
	HDMI21_IRQ_LINK_VMON_HMEAS_IRQ,
	HDMI21_IRQ_LINK_AUD_CHSTATUS_SP3_IRQ,
	HDMI21_IRQ_LINK_AUD_CHSTATUS_SP2_IRQ,
	HDMI21_IRQ_LINK_AUD_CHSTATUS_SP1_IRQ,
	HDMI21_IRQ_LINK_AUD_CHSTATUS_SP0_IRQ,
	HDMI21_IRQ_LINK_AUD_MUTE_IRQ	,
	HDMI21_IRQ_LINK_AFIFO_UNDERFLOW_IRQ,
	HDMI21_IRQ_LINK_AFIFO_OVERFLOW_IRQ,
	HDMI21_IRQ_LINK_AFIFO_THR_MUTE_LOW_IRQ,
	HDMI21_IRQ_LINK_AFIFO_THR_MUTE_HIGH_IRQ,
	HDMI21_IRQ_LINK_AFIFO_THR_LOW_IRQ,
	HDMI21_IRQ_LINK_AFIFO_THR_HIGH_IRQ,
	HDMI21_IRQ_LINK_AFIFO_THR_PASS_IRQ,
	HDMI21_IRQ_LINK_AUD_FMT_CHG_IRQ,
	HDMI21_IRQ_LINK_VPROC_SYNCGEN_IRQ,
	HDMI21_IRQ_LINK_VPROC_PP_DIFF_IRQ,
	HDMI21_IRQ_LINK_VPROC_CD_TIMEOUT_IRQ,
	HDMI21_IRQ_LINK_VPROC_CD_CHG_IRQ,
	HDMI21_IRQ_LINK_VSTREAM_FIFO_OVERFLOW_IRQ,
	HDMI21_IRQ_LINK_VSTREAM_FIFO_UNDERFLOW_IRQ, 
	HDMI21_IRQ_LINK_VSTREAM_FIFO_ALMOST_FULL_IRQ, 
	HDMI21_IRQ_LINK_VSTREAM_FIFO_ALMOST_EMPTY_IRQ,
	HDMI21_IRQ_LINK_DEFRAMER_DVIHDMI_CHG_IRQ,
	HDMI21_IRQ_LINK_DEFRAMER_GBDET_ERR_IRQ,
	HDMI21_IRQ_LINK_DEFRAMER_VSYNC_THR_REACHED_IRQ,
	HDMI21_IRQ_LINK_DEFRAMER_VSYNC_IRQ,
	/* AVP Unit 2 */
	HDMI21_IRQ_LINK_FRL_CED_DYN_ERRCNT_THR_LANE3_IRQ,
	HDMI21_IRQ_LINK_FRL_CED_DYN_ERRCNT_THR_LANE2_IRQ,
	HDMI21_IRQ_LINK_FRL_CED_DYN_ERRCNT_THR_LANE1_IRQ,
	HDMI21_IRQ_LINK_FRL_CED_DYN_ERRCNT_THR_LANE0_IRQ,
	HDMI21_IRQ_LINK_UNPACKER_TYPE_ERR_CNT_IRQ,
	HDMI21_IRQ_LINK_UNPACKER_LENGTH_ERR_CNT_IRQ,
	HDMI21_IRQ_LINK_UNPACKER_FIFO_UNDERFLOW_IRQ,
	HDMI21_IRQ_LINK_UNPACKER_FIFO_OVERFLOW_IRQ,
	HDMI21_IRQ_LINK_FRL_DESCRAMB_SYNC_IRQ,
	HDMI21_IRQ_LINK_MARKER_SB_SIZE_IRQ,
	HDMI21_IRQ_LINK_MARKER_SB_COUNT_IRQ,
	/* PKT Unit 0 */
	HDMI21_IRQ_LINK_PKTDEC_VTEM_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_CVTEM_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_EMD_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_GENPKT1_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_GENPKT0_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_DRMIF_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_NTSCVBIIF_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_AUDIF_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_SRCPDIF_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_AVIIF_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_VSIF_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_AMD_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_GMD_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_ISRC2_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_ISRC1_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_ACP_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_GCP_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_ACR_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_ACP_TIMEOUT_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_ACR_N_CHG_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_ACR_CTS_CHG_IRQ,
	/* PKT Unit 1 */
	HDMI21_IRQ_LINK_PKTFIFO_NEW_ENTRY_IRQ,
	HDMI21_IRQ_LINK_PKTFIFO_OVERFLOW_IRQ,
	HDMI21_IRQ_LINK_PKTFIFO_UNDERFLOW_IRQ,
	HDMI21_IRQ_LINK_PKTFIFO_THR_HIGH_IRQ,
	HDMI21_IRQ_LINK_PKTFIFO_THR_PASS_IRQ,
	HDMI21_IRQ_LINK_PKTFIFO_THR_LOW_IRQ,
	/* PKT Unit 2*/
	HDMI21_IRQ_LINK_PKTDEC_VTEM_RCV_IRQ,
	HDMI21_IRQ_LINK_PKTDEC_CVTEM_RCV_IRQ,		
	HDMI21_IRQ_LINK_PKTDEC_EMD_RCV_IRQ,		
	HDMI21_IRQ_LINK_PKTDEC_GENPKT1_RCV_IRQ,	
	HDMI21_IRQ_LINK_PKTDEC_GENPKT0_RCV_IRQ,	
	HDMI21_IRQ_LINK_PKTDEC_DRMIF_RCV_IRQ,		
	HDMI21_IRQ_LINK_PKTDEC_NTSCVBIIF_RCV_IRQ,	
	HDMI21_IRQ_LINK_PKTDEC_AUDIF_RCV_IRQ,		
	HDMI21_IRQ_LINK_PKTDEC_SRCPDIF_RCV_IRQ,	
	HDMI21_IRQ_LINK_PKTDEC_AVIIF_RCV_IRQ,		
	HDMI21_IRQ_LINK_PKTDEC_VSIF_RCV_IRQ,		
	HDMI21_IRQ_LINK_PKTDEC_AMD_RCV_IRQ,		
	HDMI21_IRQ_LINK_PKTDEC_GMD_RCV_IRQ,		
	HDMI21_IRQ_LINK_PKTDEC_ISRC2_RCV_IRQ,		
	HDMI21_IRQ_LINK_PKTDEC_ISRC1_RCV_IRQ,		
	HDMI21_IRQ_LINK_PKTDEC_ACP_RCV_IRQ,		
	HDMI21_IRQ_LINK_PKTDEC_GCP_RCV_IRQ,		
	HDMI21_IRQ_LINK_PKTDEC_ACR_RCV_IRQ,		
	/* SCDC Unit */
	HDMI21_IRQ_LINK_FRL_START_TIMEOUT_IRQ,
	HDMI21_IRQ_LINK_SCDCTMDSCCFG_CHG_IRQ,
	HDMI21_IRQ_LINK_SCDCSCSTATUS_CHG_IRQ,
	HDMI21_IRQ_LINK_SCDCCFG_CHG_IRQ,
	/* HDCP Unit */
	HDMI21_IRQ_LINK_HDCP2_DECRYPTED_CHG_IRQ,
	HDMI21_IRQ_LINK_HDCP2_AUTHENTICATION_FAIL_IRQ,
	HDMI21_IRQ_LINK_HDCP2_AUTHENTICATED_IRQ,
	HDMI21_IRQ_LINK_HDCP2_AUTHENTICATION_LOST_IRQ,
	HDMI21_IRQ_LINK_HDCP2_NOT_CAPABLE_IRQ,
	HDMI21_IRQ_LINK_HDCP2_CAPABLE_IRQ,
	HDMI21_IRQ_LINK_HDCP_DKSET_DONE_IRQ,
	HDMI21_IRQ_LINK_HDCP14_OESS_EESS_CHG_IRQ,
	HDMI21_IRQ_LINK_HDCP14_ENCDIS_IRQ,
	HDMI21_IRQ_LINK_HDCP14_ENCEN_IRQ,
	HDMI21_IRQ_LINK_HDCP14_AUTH_IRQ,
	HDMI21_IRQ_LINK_HDCP14_BSTATUS_READ_IRQ,
	HDMI21_IRQ_LINK_HDCP14_BCAPS_READ_IRQ,
	HDMI21_IRQ_LINK_HDCP14_RI_READ_IRQ,
	HDMI21_IRQ_LINK_HDCP14_BKSV_READ_IRQ,
	HDMI21_IRQ_LINK_HDCP14_AKSV_RCV_IRQ,
	/* HDCP 1 Unit */
	HDMI21_IRQ_LINK_HDCP2_ESM_P0_GPIO_OUT_15_CHG_IRQ,
	HDMI21_IRQ_LINK_HDCP2_ESM_P0_GPIO_OUT_14_CHG_IRQ,
	HDMI21_IRQ_LINK_HDCP2_ESM_P0_GPIO_OUT_13_CHG_IRQ,
	HDMI21_IRQ_LINK_HDCP2_ESM_P0_GPIO_OUT_12_CHG_IRQ, 
	HDMI21_IRQ_LINK_HDCP2_ESM_P0_GPIO_OUT_11_CHG_IRQ, 
	HDMI21_IRQ_LINK_HDCP2_ESM_P0_GPIO_OUT_10_CHG_IRQ,
	HDMI21_IRQ_LINK_HDCP2_ESM_P0_GPIO_OUT_9_CHG_IRQ,
	HDMI21_IRQ_LINK_HDCP2_ESM_P0_GPIO_OUT_8_CHG_IRQ, 
	HDMI21_IRQ_LINK_HDCP2_ESM_P0_GPIO_OUT_7_CHG_IRQ, 
	HDMI21_IRQ_LINK_HDCP2_ESM_P0_GPIO_OUT_6_CHG_IRQ, 
	HDMI21_IRQ_LINK_HDCP2_ESM_P0_GPIO_OUT_5_CHG_IRQ, 
	HDMI21_ISR_LINK_UNKNOWN,
	HDMI21_ISR_TOPLINK_SCDC_FRL_RATE_RCV,
	HDMI21_ISR_TOPLINK_SCDC_FRL_RATE_SAME,
	HDMI21_ISR_TOPLINK_SCDC_SCRAMBLE_RCV, 
	HDMI21_ISR_TOPLINK_SCDC_FRL_START_UP,
	HDMI21_ISR_TOPLINK_SCDC_FRL_START_DN,
	HDMI21_ISR_TOPLINK_SCDC_FRL_UPDATE_UP,
	HDMI21_ISR_TOPLINK_SCDC_FRL_UPDATE_DN,
	/* LG HDMI Top */
	HDMI21_ISR_TOP_5V_UP,
	HDMI21_ISR_TOP_5V_DOWN,
	HDMI21_ISR_TOP_PC,
	HDMI21_ISR_TOP_PD,
	HDMI21_ISR_TOP_CHSTS_EN,
	HDMI21_ISR_TOP_EARCTX_CMDC_XACT_DONE_IRQ,
	HDMI21_ISR_TOP_EARCTX_CMDC_RXPKT_BADPAR_IRQ,
	HDMI21_ISR_TOP_EARCTX_CMDC_RXPKT_BADECC_IRQ,
	HDMI21_ISR_TOP_EARCTX_CMDC_RXPKT_INCOMPLETE_IRQ,
	HDMI21_ISR_TOP_EARCTX_CMDC_RXPKT_BADSYNC_IRQ,
	HDMI21_ISR_TOP_EARCTX_CMDC_RXPKT_BADPREAMBLE_IRQ,
	HDMI21_ISR_TOP_EARCTX_CMDC_HEARTBEAT_CAP_CHNG_IRQ,
	HDMI21_ISR_TOP_EARCTX_CMDC_HEARTBEAT_STAT_CHNG_IRQ,
	HDMI21_ISR_TOP_EARCTX_CMDC_HEARTBEAT_LOST_IRQ,
	HDMI21_ISR_TOP_EARCTX_CMDC_DISCOVERY_TIMEOUT_IRQ,
	HDMI21_ISR_TOP_EARCTX_CMDC_DISCOVERY_DONE_IRQ,
	HDMI21_ISR_TOP_EARCTX_DMAC_MUTE_REQUEST_IRQ,
	HDMI21_ISR_TOP_EARCTX_DMAC_AUDIO_FIFO_OVERFLOW_IRQ,
	HDMI21_ISR_TOP_EARCTX_DMAC_AUDIO_FIFO_UNDERFLOW_IRQ,
	HDMI21_ISR_TOP_DDCMON_DDC1_IRQ,
	HDMI21_ISR_TOP_DDCMON_DDC2_IRQ,
	HDMI21_ISR_TOP_DDCMON_DDC3_IRQ,
	HDMI21_ISR_TOP_DDCMON_DDC4_IRQ,
	HDMI21_ISR_TOP_UNKNOWN,	
	HDMI21_ISR_MAXNUM
} HDMI21_ISR_TYPE_T;

/* Data Packet Type */
typedef enum
{
	/** Audio clock regeneration packet */
	HDMI21_DISLAND_DATA__ACR = 0,
	/** General control packet */
	HDMI21_DISLAND_DATA__GCP,
	/** Audio content protection packet */
	HDMI21_DISLAND_DATA__ACP,
	/** International standard recording code 1 packet */
	HDMI21_DISLAND_DATA__ISRC1,
	/** International standard recording code 2 packet */
	HDMI21_DISLAND_DATA__ISRC2,
	/** Gamut metadata packet */
	HDMI21_DISLAND_DATA__GAMUT,
	/** Audio metadata Packet */
	HDMI21_DISLAND_DATA__AMD,
	/** Vendor specific info frame packet */
	HDMI21_DISLAND_DATA__VSI,
	/** Auxiliary video info frame packet */
	HDMI21_DISLAND_DATA__AVI,
	/** Source product descriptor info frame packet */
	HDMI21_DISLAND_DATA__SPD,
	/** Audio info frame packet */
	HDMI21_DISLAND_DATA__AIF,
	/** NTSCVBI source info frame packet */
	HDMI21_DISLAND_DATA__NTSCVBI,
	/** HDR source info frame packet */
	HDMI21_DISLAND_DATA__DRM,
	/** GEN 0 **/
	HDMI21_DISLAND_DATA__GEN0,
	/** GEN 1 **/
	HDMI21_DISLAND_DATA__GEN1,
	/** EMD **/
	HDMI21_DISLAND_DATA__EMD,
	/** 2020/05/25 : H14 VSIF */
	HDMI21_DISLAND_DATA__H14VSI,	
	/** 2020/05/25 : HF VSIF */
	HDMI21_DISLAND_DATA__HFVSI,
	/** 2020/05/25 : Dolby VSIF */
	HDMI21_DISLAND_DATA__DOLBYVSI,
	/** 2020/08/21 : Dolby VSIF + H14 VSIF **/
	HDMI21_DISLAND_DATA__DOVI,
	/** Sentinel value */
	HDMI21_DISLAND_DATA_MAXNUM
} HDMI21_DISLAND_DATA_T;


typedef struct
{
	UINT32 /* 0 */
		bits_per_component:4,		// 3:0
		convert_rgb:1,		// 4:4
		simple_422:1,		// 5:5
		linebuf_depth:4,		// 9:6
		bits_per_pixel:10,		// 19:10
		_block_pred_enable:1,		// 20:20
		native_420:1,		// 21:21
		native_422:1,		// 22:22
		padd_rsvd0:5,		// 27:23
		dsc_version_minor:4;	// 31:28
	UINT32 /* 1 */
		pic_width:16,		// 15:0
		pic_height:16;		// 31:16
	UINT32 /* 2 */
		slice_width:16,		// 15:0
		slice_height:16;		// 31:16
	UINT32 /* 3 */
		chunk_size:16,		// 15:0
		padd_rsvd1:15;		// 31:16
	UINT32 /* 4 */
		initial_xmit_delay:10,		// 9:0
		padd_rsvd2:6,		// 15:10
		initial_dec_delay:16;		// 31:16
	UINT32 /* 5 */
		initial_scale_value:6,		// 5:0
		padd_rsvd3:25;		// 31:6
	UINT32 /* 6 */
		scale_increment_interval:16,		// 15:0
		scale_decrement_interval:12,		// 27:16
		padd_rsvd4:3;		// 31:28
	UINT32 /* 7 */
		first_line_bpg_offset:5,		// 4:0
		second_line_bpg_offset:5,		// 9:5
		padd_rsvd5:21;		// 31:10
	UINT32 /* 8 */
		nfl_bpg_offset:16,		// 15:0
		slice_bpg_offset:16;		// 31:16
	UINT32 /* 9 */
		initial_offset:16,		// 15:0
		final_offset:16;		// 31:16
	UINT32 /* 10 */
		nsl_bpg_offset:16,		// 15:0
		second_line_offset_adj:16;		// 31:16
	UINT32 /* 11 */
		flatness_min_qp:5,		// 4:0
		flatness_max_qp:5,		// 9:5
		flatness_det_thresh:8,		// 17:10
		padd_rsvd6:13;		// 31:18
	UINT32 /* 12 */
		rc_model_size:16,		// 15:0
		padd_rsvd7:15;		// 31:16
	UINT32 /* 13 */
		rc_edge_factor:4,		// 3:0
		padd_rsvd8:4,		// 7:4
		rc_quant_incr_limit0:5,		// 12:8
		rc_quant_incr_limit1:5,		// 17:13
		padd_rsvd20:2,		// 19:18
		rc_tgt_offset_hi:4,		// 23:20
		rc_tgt_offset_lo:4,		// 27:24
		padd_rsvd9:3;		// 31:28
	UINT32 /* 14 */
		rc_buf_thresh_0:8,		// 7:0
		rc_buf_thresh_1:8,		// 15:8
		rc_buf_thresh_2:8,		// 23:16
		rc_buf_thresh_3:8;		// 31:24
	UINT32 /* 15 */
		rc_buf_thresh_4:8,		// 7:0
		rc_buf_thresh_5:8,		// 15:8
		rc_buf_thresh_6:8,		// 23:16
		rc_buf_thresh_7:8;		// 31:24
	UINT32 /* 16 */
		rc_buf_thresh_8:8,		// 7:0
		rc_buf_thresh_9:8,		// 15:8
		rc_buf_thresh_10:8,		// 23:16
		rc_buf_thresh_11:8;		// 31:24
	UINT32 /* 17 */
		rc_buf_thresh_12:8,		// 7:0
		rc_buf_thresh_13:8,		// 15:8
		padd_rsvd10:15;		// 31:16
	UINT32 /* 18 */
		rc_range_parameters_0_range_min_qp:5,		// 4:0
		rc_range_parameters_1_range_min_qp:5,		// 9:5
		rc_range_parameters_2_range_min_qp:5,		// 14:10
		rc_range_parameters_3_range_min_qp:5,		// 19:15
		rc_range_parameters_4_range_min_qp:5,		// 24:20
		padd_rsvd11:6;		// 31:25
	UINT32 /* 19 */
		rc_range_parameters_5_range_min_qp:5,		// 4:0
		rc_range_parameters_6_range_min_qp:5,		// 9:5
		rc_range_parameters_7_range_min_qp:5,		// 14:10
		rc_range_parameters_8_range_min_qp:5,		// 19:15
		rc_range_parameters_9_range_min_qp:5,		// 24:20
		padd_rsvd12:6;		// 31:25
	UINT32 /* 20 */
		rc_range_parameters_10_range_min_qp:5,		// 4:0
		rc_range_parameters_11_range_min_qp:5,		// 9:5
		rc_range_parameters_12_range_min_qp:5,		// 14:10
		rc_range_parameters_13_range_min_qp:5,		// 19:15
		rc_range_parameters_14_range_min_qp:5,		// 24:20
		padd_rsvd13:6;		// 31:25
	UINT32 /* 21 */
		rc_range_parameters_0_range_max_qp:5,		// 4:0
		rc_range_parameters_1_range_max_qp:5,		// 9:5
		rc_range_parameters_2_range_max_qp:5,		// 14:10
		rc_range_parameters_3_range_max_qp:5,		// 19:15
		rc_range_parameters_4_range_max_qp:5,		// 24:20
		padd_rsvd14:6;		// 31:25
	UINT32 /* 22 */
		rc_range_parameters_5_range_max_qp:5,		// 4:0
		rc_range_parameters_6_range_max_qp:5,		// 9:5
		rc_range_parameters_7_range_max_qp:5,		// 14:10
		rc_range_parameters_8_range_max_qp:5,		// 19:15
		rc_range_parameters_9_range_max_qp:5,		// 24:20
		padd_rsvd15:6;		// 31:25
	UINT32 /* 23 */
		rc_range_parameters_10_range_max_qp:5,		// 4:0
		rc_range_parameters_11_range_max_qp:5,		// 9:5
		rc_range_parameters_12_range_max_qp:5,		// 14:10
		rc_range_parameters_13_range_max_qp:5,		// 19:15
		rc_range_parameters_14_range_max_qp:5,		// 24:20
		padd_rsvd16:6;		// 31:25
	UINT32 /* 24 */
		rc_range_parameters_0_range_bpg_offset:6,		// 5:0
		rc_range_parameters_1_range_bpg_offset:6,		// 11:6
		rc_range_parameters_2_range_bpg_offset:6,		// 17:12
		rc_range_parameters_3_range_bpg_offset:6,		// 23:18
		rc_range_parameters_4_range_bpg_offset:6,		// 29:24
		padd_rsvd17:1;		// 31:30
	UINT32 /* 25 */
		rc_range_parameters_5_range_bpg_offset:6,		// 5:0
		rc_range_parameters_6_range_bpg_offset:6,		// 11:6
		rc_range_parameters_7_range_bpg_offset:6,		// 17:12
		rc_range_parameters_8_range_bpg_offset:6,		// 23:18
		rc_range_parameters_9_range_bpg_offset:6,		// 29:24
		padd_rsvd18:1;		// 31:30
	UINT32 /* 26 */
		rc_range_parameters_10_range_bpg_offset:6,		// 5:0
		rc_range_parameters_11_range_bpg_offset:6,		// 11:6
		rc_range_parameters_12_range_bpg_offset:6,		// 17:12
		rc_range_parameters_13_range_bpg_offset:6,		// 23:18
		rc_range_parameters_14_range_bpg_offset:6,		// 29:24
		padd_rsvd19:1;		// 31:30
} HDMI21_HAL_DSC_PPS_O20A0_T;


typedef enum
{
	HDMI21_HAL_VIDEO_DEEPCOLOR_NONE = 0,
	HDMI21_HAL_VIDEO_DEEPCOLOR_8_BIT = 4,
	HDMI21_HAL_VIDEO_DEEPCOLOR_10_BIT = 5,
	HDMI21_HAL_VIDEO_DEEPCOLOR_12_BIT = 6,
	HDMI21_HAL_VIDEO_DEEPCOLOR_16_BIT = 7,
	HDMI21_HAL_VIDEO_DEEPCOLOR_MAXNUM
} HDMI21_HAL_VIDEO_DEEPCOLOR_MODE_T;

typedef struct
{
	bool dvi;/** DVI detection status: DVI (true) or HDMI (false) */
	bool interlaced;/** Interlaced */
	int pixel_repetition;
	UINT32 video_format;	/* RGB:0/YCbCr422:1/444:2/420:3 */
	UINT32 tmds_clk;
	UINT32 vicCode;		/* From AVI VIC Code */
	HDMI21_HAL_VIDEO_DEEPCOLOR_MODE_T deep_color_mode;	/** Deep color mode: 24, 30, 36 or 48 [bits per pixel] */
	UINT32 pixel_clk;/** Pixel clock frequency [kHz] */
	UINT32 vfreq;
	UINT32 refresh_rate;/** Refresh rate [0.01Hz] */
	UINT32 voffset;	/** Vertical offset */
	UINT32 vactive;/** Vertical active */
	UINT32 vtotal;/** Vertical total */
	UINT32 hoffset;/** Horizontal offset */
	UINT32 hactive;/** Horizontal active */
	UINT32 htotal;	/** Horizontal total */
} HDMI21_HAL_VIDEO_TIMING_T;

/* Device Handler : MEMORY MAPPING data structure */
typedef struct
{
	UINT32 hwAddr;
	volatile UINT32 * pSwAddr;
	int size;
} HDMI21_HAL_MEMORY_MAPPING_T;


typedef struct {
	UINT32 errorStatus;
	UINT32 startTick[LX_HDMI20_ERROR_MAXNUM];
	UINT32 counter[LX_HDMI20_ERROR_MAXNUM];	
	bool isActive[LX_HDMI20_ERROR_MAXNUM];

	/* For CED Error Accumlate */
	UINT32 cedError[HDMI21_AMOUNT_OF_TMDS_CHANNEL_IN_ONE_PHY];
} HDMI21_HOST_DIAGNOSIS_ERROR_T;

/* PHY Exception types */
typedef enum
{
	HDMI21_HAL_PHY_EXCEPTION_CASE_NONE = 0,
	HDMI21_HAL_PHY_EXCEPTION_CASE_MAXNUM
} HDMI21_HAL_PHY_EXCEPTION_CASE_T;

typedef enum
{
	HDMI21_HAL_POWER_UNINITIATED = 0,
	HDMI21_HAL_POWER_NORMAL,	
	HDMI21_HAL_POWER_LOWPOWER,
	HDMI21_HAL_POWER_ERRORSTATE,
	HDMI21_HAL_POWER_MAXNUM
} HDMI21_HAL_POWER_MODE_T;

/* Main Thread Handler */
typedef struct {
	struct task_struct* pThread;
	int isAlive;
	int stamp;
	int mSleep;
} HDMI21_THREAD_CONTROLLER_T;

/* For abnormal 3D video detection */
typedef struct{
	UINT16 hAct_info;		///< Horizontal active pixel
	UINT16 vAct_info; 		///< Vertical active lines
	UINT16 scan_info;		///< Scan type (0 : interlace, 1 : progressive)

	UINT16 hAct_buf;			///< Horizontal active pixel
	UINT16 vAct_buf; 		///< Vertical active lines
	UINT16 scan_buf; 		///< Scan type (0 : interlace, 1 : progressive)
	LX_HDMI_EXT_FORMAT_INFO_T  extInfo_buf;		///< Ext format Information (3D, 4Kx2K)
} HDMI21_NON_VSI_3D_TIMING_T;


/* DDC Monitor Feature */
typedef struct
{
	UINT8 bank;
	UINT8 sub_addr;
	UINT8 dev_addr;
	UINT8
		op_mode:1,			/* 0:0 */
		intr_err:1,			/* 1:1 */
		cap_length:3,		/* 4:2 */
		finish:1,			/* 5:5 */
		nack:1,				/* 6:6 */
		b_rsvd_0:1;			/* 7:7 */	
	UINT8
		scdc_short_rd:1,	/* 0:0 */
		hdcp_short_rd:1,	/* 1:1 */
		b_rsvd_1:6;			/* 7:2 */
	UINT32 data;
	UINT32 msec;			/* Jiffies msec */
} HDMI21_HAL_DDC_HW_UNITDATA_T;


/* Device Handler for Each Link */
typedef struct
{
	bool initiated;				/* Flag indicating that the Device Handler was initiated */

	/*---------------------------------------------------------------------------------
	 * Need to be provided for Driver to operation : HW address, IRQ, Port       
	 * Below Parts must be provided for normal operation */

	/* #1. Port Number for index */
	unsigned int port;					/* HDMI2.1 My Handler Index. Insert array index */

	/* #2. IRQ Information. Should be provided from share.lge.com/pws chip information */
	int irq;					/* HDMI2.0 Rx LINK IRQ */
	int top_irq;				/* HDMI2.0 Rx TOP IRQ */

	/* #3. Link HW Physical Address must be provided before initate sequence :
	 * 		Need to be provided at before initiate sequence.
	 * 		Memory will be allocated with */
	HDMI21_HAL_MEMORY_MAPPING_T topMem;			/* HDMI2.1 RX Top ctrl memory mapping */
	HDMI21_HAL_MEMORY_MAPPING_T linkMem;		/* HDMI2.1 RX Link ctrl memory mapping */
	HDMI21_HAL_MEMORY_MAPPING_T aledMem;		/* HDMI2.1 RX Always EDID memory mapping */
	HDMI21_HAL_MEMORY_MAPPING_T	phyPdcMem;		/* HDMI2.1 Rx PHY PDC memory mapping */
	HDMI21_HAL_MEMORY_MAPPING_T	phyPostDrMem;	/* HDMI2.1 Rx PHY Post DR memory mapping */


	/* #4. Function Pointers :
	 * 		Memory will be accessed with these function pointers.
	 * 		Funtions should use topMem/LinkMem/aledMem/phyPdcMem/phyPostDRMem info */
	void (*aled_write)(UINT32 addr, UINT32 data);	/* Function for Always-EDID register write access */
	UINT32 (*aled_read)(UINT32 addr);				/* Function for Always-EDID register write access */
	void (*top_write)(UINT32 addr, UINT32 data);	/* Function for TOP register write access */
	UINT32 (*top_read)(UINT32 addr);				/* Function for TOP register write access */
	void (*link_write)(UINT32 addr, UINT32 data);	/* Function for LINK register write access */
	UINT32 (*link_read)(UINT32 addr);				/* Function for LINK register write access */
	void (*phyPDC_write)(UINT32 addr, UINT32 data);	/* Function for PHY PDC register write access */
	UINT32 (*phyPDC_read)(UINT32 addr);				/* Function for PHY PDC register write access */
	void (*phyDR_write)(UINT32 addr, UINT32 data);	/* Function for PHY Post DR register write access */
	UINT32 (*phyDR_read)(UINT32 addr);				/* Function for PHY Post DR register write access */
	void (*control_link_irq)(int bOnOff);			/* Control Interrupt disable/enable for Link IRQ */	
	void (*control_top_irq)(int bOnOff);			/* Control Interrupt disable/enable for TOP IRQ */
	irqreturn_t (*irq_link_handler)(int irq, void *dev_id, struct pt_regs *regs); /* Link Interrupt IRQ */ 
	irqreturn_t (*irq_top_handler)(int irq, void *dev_id, struct pt_regs *regs); /* Top Interrupt IRQ */ 

	/* End of insertion.
	 * ------------------------------------------------------------------------------*/

	/* Below data structure is for driver operation reference/History/Mode control/etc.. */
	/* #1. Clock Information */
	UINT64 phy_tmds_clk;		/* PHY  : TMDS clock read from PHY module */
	UINT64 real_tmds_clk;		/* LINK : TMDS Clock. This is read from PHY Module */
	UINT64 real_pixel_clk;		/* LINK : Pixel Clock derived from LINK real_tmds_clk */
	UINT32 real_vfreq;			/* LINK : Vertical Frequency derived from LINK real_tmds_clk */

	/* #2. Data : DataPacket, EDID Data */
	UINT8 dataPacket[HDMI21_DISLAND_DATA_MAXNUM][HDMI21_MAX_DATA_PACKET_LENGTH];	/* HDMI Data Island Packet storage */
	UINT8 emp_vtemPacket[HDMI21_MAX_DATA_PACKET_LENGTH];		/* HDMI Extended Meta : VTEM */
	UINT8 emp_cvtemPacket[HDMI21_MAX_CVTEM_LENGHT];				/* HDMI Extended Meta : CVTEM */
	UINT32 edidData[HDMI21_HAL_SIZE_OF_EDID>>2];		/* EDID Data storage for reference */
	HDMI21_HAL_DSC_PPS_O20A0_T pps;

	/* #3. Status variables */	
	HDMI21_HAL_VIDEO_TIMING_T video;	/* Video Status : updated only if HW value are stable enough */
	HDMI21_HAL_VIDEO_TIMING_T hwVideo;	/* Video Status of HW : Direct HW Value */
	int gWasHDCP14Written;				/* indicating that the HDCP1.4 key was written by MW*/
	int gWasHDCP22Written;				/* indicating that the HDCP2.2 should be operating*/
	int gWasHDCP22FuncCalled;			/* idicating that the HDCP2.2 key was written from MW */
	int isDolbyHDR;						/* Dolby HDR Status */
	int isDSC;							/* DSC status */
	HDMI21_HAL_PHY_INITIATED_MODE_T scdcTmdsMode;		/* Current PHY Mode */
	int stable_cnt;

	/* #4. PHY status variable */
	HDMI21_HAL_PHY_INITIATED_MODE_T phyInitiatedMode;	/* The mode PHY was reseted... 0:3G, 1:6G, 2:FRL*/
	UINT32 phyTCSFailed;
	int phyTCSDiff[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyTCSMin[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyTCSMax[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyTCSResult[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyTMDSError[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phySyncRecovery[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyCEDError[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyDeltaError[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyDeltaPlus[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyDeltaMinus[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyDfeA01Result[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyDfeA11Result[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyDfeB1Result[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyDfeB2Result[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyDfeB3Result[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyDfeB4Result[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyDfeB5Result[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];
	int phyCurrentTMDSExceptionRange;
	int phyPrevTMDSExceptionRange;
	UINT32 phyDcBalanceCounter;
	UINT32 phyTCSState;
	HDMI21_HAL_PHY_EXCEPTION_CASE_T phyExceptionState;

	UINT8 phyRsResult[HDMI21_HAL_CNT_OF_CHANNEL_IN_ONE_PHY];


	/* #5. Time stamps : History of signal transaction time */
	UINT32 allm_recieve_time;	/* Time stamp on when ALLM packet was recieved */
	UINT32 em_vrr_recieve_time;	/* Time stamp on when EM VRR packet was recieved */
	UINT32 avmute_on_time;		/* The time when the AVMUTE(GCP) was indicated */
	UINT32 cable_connect_time;	/* The Jiffies time when the cable was connected */		
	UINT32 localmutetimer;		/* Record of when the local mute was called */
	UINT32 updateTimingTime;	/* The time stamp of when the timinginfo was updated */
	UINT32 restartHPDTimeStamp; /* The Time stamp for Restart HPD feature */
	UINT32 connected5Vtime;/*The timestamp when the cable was connected */
	UINT32 doviTimeStamp; /*Time stamp of DOLBY releated VSI receieve time */
	UINT32 dolbyVsiTimeStamp; /* Time stampe of Dolby-VSI receieve time */
	UINT32 em_qms_recieve_time;	/* Time stamp on when EM QMS packet was recieved */
	UINT32 em_qms_mconst_zero_cnt;

	/* #6. Counters for History : Non-Audio */
	int locking_time;			/* The actual lock time from phy reset to phy lock */
	unsigned int stablehdcp14time;/*The accumulated time for HDCp1.4 stable condition */
	UINT32 isr_count0[HDMI21_ISR_MAXNUM];	/* DBG : ISR profiler counter */
	UINT32 isr_count1[HDMI21_ISR_MAXNUM];	/* DBG : ISR profiler counter */

	/* #7. Counters for History : Audio(taejun.lee@lge.com) */
	LX_HDMI_AUDIO_INFO_T audioInfo;		/* Audio Type Info */
	UINT32 audioStandByCnt;
	UINT32 audioStableCnt;					/* No Audio Count */
	UINT32 audioChMapStandByCnt;			/* Audio Channel Mapping Count */
	UINT32 audioChMapCnt;					/* Fifo Error count */
	UINT32 audioFifoErrMuteCnt;			/* I2S Mute Cnt */
	UINT32 audioAcrErrorCnt;	
	UINT32 audioAcrResetCnt;
	UINT32 audioIrqFifoErrCnt;
	UINT32 audioForceMuteCnt;
	UINT32 audioUnknowTypeMuteCnt;
	UINT32 audioHBRAdnormalCnt;
	UINT32 audioTypeAdnormalCnt;
	UINT32 audioDbgPrintCnt;

	/* #8. Flag : PHY */
	bool phyTCSDone;			/* PHY TCS Done */
	bool phyCrDone;				/* PHY CR(CLock Recovery) Done Signal */
	bool phyRsDone;
	
	/* #9. Flag : For non-Audio */
	bool restartHpdFlagUp;		/* The flag for indiciating that driver is in Restart HPD mode */
	bool isHPDInverseMode;		/* HPD Inverse mode */
	bool isLinkInitiated;		/* A Flag inidicating that the link was initiated after cable connection */
	bool isPhyLocked;			/* A Flag inidicating that the PHY is LOCKED */
	bool scdc_change;			/* Flag indicating that the SCDC status have been changed */
	bool video_change;			/* Flag indicating that the Link status have been changed */
	bool audio_change;			/* Flag indicating that the Audio status have been changed */
	int audio_state;			/* Flag indicating that the Audio status have been changed */
	bool tmds_change;			/* Flag indicating that the TMDS status have been changed */
	bool hdcp_change;			/* Flag indicating that the AKSV status have been changed */
	bool dcm_change;			/* Flag indicating that the GCP DCM status have been changed */
	bool is5Vconnected;			/* Flag indicating that the 5V is inserted from the source device */
	bool isHPD;					/* Flag indicating that the HPD is Up */
	
	bool isHDCP22;				/* Flag indicating that current source is HDCP2.2 encrypted */
	bool isHDCP14;				/* Flag indicating that current source is HDCP1.4 encrypted */	
	bool isTimingInvalid;		/* Flag indicating that the currently detected signal is invalid timing*/
	bool hpd_request;			/* Flag indicating that the driver is waiting a HPD UP request from upper layer */
	bool fsm_phy_lock;		/* Flag indicating that the driver is on a phy reset sequence */
	bool main_thread_init_request;		/* Flag indicating that the driver is on a connection request */
	bool wasEdidWritten;		/* Flag indicating the the EDID was written from MW */
	bool hdmiDisabled;			/* For HDCP Repeater. This Flag means that the driver is disabled */
	bool isAllmMode;			/* Flag indicating that current mode is ALLM mode */
	bool isMute;				/* Flag inidicating that AVMute is beinging inserted */
	bool repeaterHpd;			/* Flag for HDCP Repeater mode HPD */
	bool frlRateRcv;			/* Flag for FRL Rate Receieved */
	bool isSleepMode;			/* Flag for HDMI Sleep mode : Not raising HPD even 5V is detected */
	bool disableAledEdid;

	/* #10. Flag : For Audio(taejun.lee@lge.com) */
	bool isAudioARCMode;		/* A Flag inidication that the ARC mode has been enabled from MW(CEC) */
	bool isAudioMute;
	bool isAudioMuteControl;
	bool isAudioTypeChangeIrq;
	bool isAudioRegReady;
	bool isHBRaudio;
	bool isPC;			/* Added by TaeJun.Lee for PC audio issue */
	bool isAstroFRLSwWa;
	bool isV4l2Activated;
	UINT32 isFLT;
	
	/* #11. AUX */
	int isLowPowerTransState;
	bool isForceRestore;
	UINT32 stableHist;			/* Number Of times video was stable */
	UINT32 vfreq_min;			/* For VRR/FVA/FreeSync/Gsync case */
	UINT32 vfreq_max;			/* For VRR/FVA/FreeSync/Gsync case */
	UINT32 videoChgCount;
	UINT32 vidChgTime;
	int isMConst;
	int isFvaMode;
	int isQmsMode;
	int isFreeSyncMode;			/* VRR/FreeSync Mode. 0:Off, 1:AMD FreeSync, 2:VRR */
	unsigned int countOf6GHpdTgSwWa;	/* For XBox no SCDC/6G issue */
	int	phyErrCounter;
	LX_HDMI20_HDCP14_DATA_T hdcp;
	int phyFrlSwWaState;
	int is8KModel;
	int isPhyFrlCtsMode;
	int lnLockLossCnt;
	UINT32 hdrOverRide;
	int pktErrStateCnt;
	UINT32 idleTick;
	HDMI21_HAL_POWER_MODE_T lowPowerMode;
	UINT32 lowPowerAccumCnt;
	UINT32 lowPowerTimeStamp;
	UINT32 accumulatedLowPowerTime;
	UINT32 em_vrr_baseRate;
	UINT32 em_qms_baseRate;
	UINT32 em_qms_tfr;
	int hdcp23_csm;
	UINT32 filterSelStuck;
	UINT32 filterSelSwWaCnt;
	UINT32 consecutiveFilStuckCnt; 
	UINT32 phyStuckVal;

	/* 2021/05/02 : DDC Mon Buffer */
	HDMI21_HAL_DDC_HW_UNITDATA_T *pDdcBuf;
	UINT32 ddcBufCnt;
	UINT32 ddcBufPnt;
	UINT32 ddcBufPrevBank;
	UINT32 isDdcMonEnabled;		/* Flag to indicate DDC Monitor is Enabled */

	UINT32 zombieMode;			/* Power Saving Mode from webOS22 */
	UINT32 top300Count;
	int cvi_vfreq;			/* vfreq calculated in PQE CVI */
	bool isPqeSuspend;
	bool isPhyLockLoss;		/* Only for O26!!! */
	bool isFrl480pDcmForceSwWa;
} HDMI21_HAL_RX_DEVICE_DATA;

/*----------------------------------------------------------------------------------------
	Extern Function Prototype Declaration
----------------------------------------------------------------------------------------*/
int HDMI21_Version(void);	/* Returns HDMI21 HAL Engine code version */
int HDMI21_Open(void);		/* Should be called on linux instance open method */
int HDMI21_Process_Cmd(LX_HDMI20_CMD_T* cmd);	/* IOCTL Handler */
int HDMI21_Suspend(void);	/* Linux Hibernation : Suspend*/
int HDMI21_Resume(void);	/* Linux Hibernation : Resume*/
void HDMI21_Set_PreInit(int isReset);

void HDMI21_Set_Line_Debugger(UINT32 value);		/* Used in Proc */
void HDMI21_Set_Audio_Line_Debugger(UINT32 value);	/* Used in Proc */
UINT32 HDMI21_Get_Line_Debugger(void);				/* Used in Proc */
UINT32 HDMI21_Get_Audio_Line_Debugger(void);		/* Used in Proc */
int	HDMI21_HAL_Rx_DBG_AccessDevVideoController(HDMI21_DEV_VIDEO_CONTROL_LIST_T index, UINT8 isSet, UINT32 *data, int isInternalCall);
int	HDMI21_HAL_Rx_DBG_AccessDevPhyController(HDMI21_DEV_PHY_CONTROL_LIST_T index, UINT8 isSet, UINT32 *data, int isInternalCall);
int	HDMI21_HAL_Rx_DBG_AccessDevLinkController(HDMI21_DEV_LINK_CONTROL_LIST_T index, UINT8 isSet, UINT32 *data, int isInternalCall);
int HDMI21_HAL_Rx_DBG_AccessDevAudioController(HDMI21_DEV_AUDIO_CONTROL_LIST_T index, UINT8 isSet, UINT32 *data, int isInternalCall);
void HDMI21_HAL_Rx_Get_VideoInfo(HDMI21_HAL_RX_DEVICE_DATA *pDevHandler, HDMI21_HAL_VIDEO_TIMING_T *pDest);
int HDMI21_HAL_Rx_Set_HDCP22Info(UINT8 port, int isInitiated);
void HDMI21_HAL_Rx_Set_PqeHdrInfo(HDMI21_HAL_RX_DEVICE_DATA *pDevHandler, UINT32 data, bool isClear);
void HDMI21_HAL_Rx_Get_UpdateDscCvtemPpsData(HDMI21_HAL_RX_DEVICE_DATA *pDevHandler);


/* Used in both hdmi21_hal_engine.c / V4L2 method layer */
int HDMI21_HAL_Rx_Set_Initialize(LX_HDMI20_INIT_T *pData, int size, int isInternalCall);
int HDMI21_HAL_Rx_Get_Check5VLevelInfo(int port, int *pValue, int isReal);	/* Could be called after HDMI21_Open*/
int HDMI21_HAL_Rx_Get_StableTimingInfo(UINT8 port, LX_HDMI_TIMING_INFO_T *pData, int size, int isInternalCall);
int HDMI21_HAL_Rx_Set_EDID(UINT8 port, UINT8 *pData, int size, int isInternalCall);
int HDMI21_HAL_Rx_Set_EDID_Enable(UINT8 port, BOOLEAN enable);
int HDMI21_HAL_Rx_Get_EDID(UINT8 port, UINT8 *pData, int size, int isInternalCall);
int HDMI21_HAL_Rx_Set_HDCP14(UINT8 port, UINT32 *pData, int size, int isInternalCall);
int HDMI21_HAL_Rx_Set_RestartHPD(UINT8 port);
LX_HDMI_DOLBY_STATE_T HDMI21_HAL_Rx_Get_IsDolbyHDR(UINT8 port);
LX_HDMI_HDR_MODE_T HDMI21_HAL_Rx_Get_HDR_Mode(UINT8 port);
int	HDMI21_HAL_Rx_Get_IsHpdUp(UINT8 port);
int	HDMI21_HAL_Rx_Get_OperationStatus(UINT8 port, LX_HDMI20_OP_STATUS_T *pData);
int HDMI21_HAL_Rx_Get_VrrCurrentVfreq(UINT8 port, UINT16 *pData, int size, int isInternalCall);
int HDMI21_HAL_Rx_Set_HDMIFactor(LX_HDMI20_SETTING_FACTOR_T *pData, int size, int isInternalCall);
int HDMI21_HAL_Rx_Set_EnableDscModule(UINT8 port);
int HDMI21_HAL_Rx_Get_VICtoVfreq(UINT32 vicCode);
UINT32 HDMI21_HAL_Rx_Get_CompensateDignosticsVfreq(UINT32 tmds_clk, UINT32 vtotal, UINT32 htotal, bool interaced, UINT32 video_format);

/* Used in both hdmi21_hal_engine.c / hdmi21_rx_irq.c */
int HDMI21_HAL_ConnectCable(int port, int bOnOff);	/* Should be called on 5V ISR */
int HDMI21_HAL_Rx_Get_IsLocalMuteOn(UINT8 port);
int HDMI21_HAL_Rx_Set_LocalVideoMute(UINT8 port, int onOff, int useTimer);
int HDMI21_HAL_Rx_Set_LinkBypassForDSC(UINT8 port, int isSet, int mode);
void HDMI21_HAL_Rx_Set_ScdcMode(UINT8 port, int force);	/* For 3G/6G/FRL setting */
int HDMI21_HAL_Rx_Get_IsVideoSyncChanged(HDMI21_HAL_RX_DEVICE_DATA *pDevHandler, HDMI21_HAL_VIDEO_TIMING_T *pComp);
void HDMI21_HAL_Rx_Get_UpdateAllmMode(HDMI21_HAL_RX_DEVICE_DATA *pDevHandler, UINT8 *pData);
void HDMI21_HAL_Rx_Get_UpdateVrrMode(HDMI21_HAL_RX_DEVICE_DATA *pDevHandler, UINT8 *pData);
void HDMI21_HAL_Rx_Set_CoreResetWithMask(HDMI21_HAL_RX_DEVICE_DATA *pDevHandler, UINT32 mask);
int HDMI21_HAL_Rx_Get_VfreqFromHdmiRegForFRL(UINT8 port);

/* Used in hdmi20_proc.c */
void HDMI21_HAL_Rx_DBG_ActivateEyeMonitor(UINT8 port, int mode, int printMode, int scaleMode);
void HDMI21_HAL_Rx_PROC_PrintEyeMonitor(int port, struct seq_file* m);
void HDMI21_HAL_Rx_PROC_PrintPhySetting(int port, struct seq_file* m);
void HDMI21_HAL_Rx_PROC_PrintVideo(int port, struct seq_file* m);
void HDMI21_HAL_Rx_PROC_PrintSavedEDID(int port, struct seq_file* m);
void HDMI21_HAL_Rx_PROC_PrintIRQ(int port, struct seq_file* m);
void HDMI21_HAL_Rx_PROC_ExternalInputStatus(int port, struct seq_file* m);
int HDMI21_HAL_Rx_DBG_GetDevControllerCnt(HDMI20_DEV_CONTROL_TYPE_T type, int *pCnt, int isInternalCall);
int HDMI21_HAL_Rx_DBG_GetDevController(HDMI20_DEV_CONTROL_TYPE_T type, HDMI20_DEV_CONTROL_T *pDevCon, int size, int isInternalCall);
int HDMI21_HAL_Rx_DBG_Tool(int type, UINT8 port, int data);
int HDMI21_HAL_Rx_Get_HDCPStatus(UINT8 port);
void HDMI21_HAL_Rx_Get_TopReg(UINT8 port, UINT32 addr, UINT32 count);
void HDMI21_HAL_Rx_Set_TopReg(UINT8 port, UINT32 addr, UINT32 value);
void HDMI21_HAL_Rx_Get_LinkReg(UINT8 port, UINT32 addr, UINT32 count);
void HDMI21_HAL_Rx_Set_LinkReg(UINT8 port, UINT32 addr, UINT32 value);
void HDMI21_HAL_Rx_Get_AledReg(UINT8 port, UINT32 addr, UINT32 count);
void HDMI21_HAL_Rx_Set_AledReg(UINT8 port, UINT32 addr, UINT32 value);
void HDMI21_HAL_Rx_Get_PhyReg(UINT8 port, UINT8 regBank, UINT32 addr, UINT32 count);
void HDMI21_HAL_Rx_Set_PhyReg(UINT8 port, UINT8 regBank, UINT32 addr, UINT32 value);

void HDMI21_HAL_Rx_DBG_GetCsEyeWidth(UINT8 port);
void HDMI21_HAL_Rx_DBG_PrintCsEyeWidth(UINT8 port);
void HDMI21_HAL_Rx_PROC_PrintCsEyeWidth(UINT8 port, struct seq_file* m);

int HDMI21_HAL_Rx_Get_IsMyPortMainWindow(UINT8 port);
int HDMI21_HAL_Rx_Get_FrameRateFromCVI(UINT8 port);

/* Power Saving */
int HDMI21_HAL_Rx_Set_V4l2PortActivate(UINT8 port, int isActive);
int HDMI21_HAL_Rx_Get_IsV4l2PortActivated(UINT8 port);
int HDMI21_HAL_Rx_Set_LowPowerMode(UINT8 port, bool isLowPower, bool isReset, int step);

/* Zombie Mode */
int HDMI21_HAL_Rx_Set_ZombieMode(UINT8 port, bool isZombie);
int HDMI21_HAL_Rx_Get_ZombieMode(UINT8 port);

int HDMI21_HAL_Rx_Get_FrameRateFromCVI_2nd(UINT8 port);
int HDMI21_HAL_Rx_Get_CheckVfreqBaseWithStableVfreq(HDMI21_HAL_RX_DEVICE_DATA *pDevHandler);
/*----------------------------------------------------------------------------------------
	Extern Variables
----------------------------------------------------------------------------------------*/

#ifdef	__cplusplus
}
#endif /* __cplusplus */

#endif /* _PROTOS_H_ */

