/*
	SIC LABORATORY, LG ELECTRONICS INC., SEOUL, KOREA
	Copyright(c) 2013 by LG Electronics Inc.

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	version 2 as published by the Free Software Foundation.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.
*/


/** @file
 *
 *  Brief description.
 *  Detailed description starts here.
 *
 *  @author     won.hur
 *  @version    1.0
 *  @date       2019-04-01
 *  @note       Additional information.
 */

#ifndef	_HDMI21_RX_SNPS_ISRUNIT_H_
#define	_HDMI21_RX_SNPS_ISRUNIT_H_

/*----------------------------------------------------------------------------------------
	Control Constants
----------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------
    File Inclusions
----------------------------------------------------------------------------------------*/


#ifdef	__cplusplus
extern "C"
{
#endif /* __cplusplus */

/*----------------------------------------------------------------------------------------
	Constant Definitions
----------------------------------------------------------------------------------------*/
/**
 * Bit field mask
 * @param m	width
 * @param n shift
 */
#ifndef MSK
#define MSK(m, n)		(((1 << (m)) - 1) << (n))
#endif

/**
 * Bit mask
 * @param n shift
 */
#ifndef BIT
#define BIT(n)			MSK(1, (n))
#endif



/* ISR Vector Table */
#define HDMI21_SNPS_REG_MAINUNIT_INTVEC_INDEX		(0x5000)
#define HDMI21_SNPS_FIELD_HDCP_1_INTVEC				BIT(14)
#define HDMI21_SNPS_FIELD_HDCP_INTVEC				BIT(13)
#define HDMI21_SNPS_FIELD_SCDC_INTVEC				BIT(12)
#define HDMI21_SNPS_FIELD_PKT_2_INTVEC				BIT(10)
#define HDMI21_SNPS_FIELD_PKT_1_INTVEC				BIT(9)
#define HDMI21_SNPS_FIELD_PKT_0_INTVEC				BIT(8)
#define HDMI21_SNPS_FIELD_AVPUNIT_2_INTVEC			BIT(6)
#define HDMI21_SNPS_FIELD_AVPUNIT_1_INTVEC			BIT(5)
#define HDMI21_SNPS_FIELD_AVPUNIT_0_INTVEC			BIT(4)
#define HDMI21_SNPS_FIELD_MAINUNIT_2_INTVEC			BIT(2)
#define HDMI21_SNPS_FIELD_MAINUNIT_1_INTVEC			BIT(1)
#define HDMI21_SNPS_FIELD_MAINUNIT_0_INTVEC			BIT(0)

/* ISR Main Unit 0 */
#define HDMI21_SNPS_REG_MAINUNIT_0_INT_MASK_N		(0x5014)
#define HDMI21_SNPS_REG_MAINUNIT_0_INT_CLR			(0x5018)
#define HDMI21_SNPS_REG_MAINUNIT_0_INT_FORCE		(0x501C)
#define HDMI21_SNPS_REG_MAINUNIT_0_INT_STATUS		(0x5010)
#define HDMI21_SNPS_FIELD_REGBANK_READY_IRQ			BIT(31)
#define HDMI21_SNPS_FIELD_APB_IF_READY_IRQ			BIT(30)
#define HDMI21_SNPS_FIELD_CDSENSE_CHG_MASK_N		BIT(27)
#define HDMI21_SNPS_FIELD_TIMER_BASE_LOCKED_IRQ		BIT(26)
#define HDMI21_SNPS_FIELD_EARC_BPCLK_OFF_CHG_IRQ	BIT(25)
#define HDMI21_SNPS_FIELD_EARC_BPCLK_LOCKED_CHG_IRQ	BIT(24)
#define HDMI21_SNPS_FIELD_EARC_AUDCLK_OFF_CHG_IRQ	BIT(23)
#define HDMI21_SNPS_FIELD_EARC_AUDCLK_LOCKED_CHG_IRQ	BIT(22)
#define HDMI21_SNPS_FIELD_FRLCLK_OFF_CHG_IRQ		BIT(21)
#define HDMI21_SNPS_FIELD_FRLCLK_LOCKED_CHG_IRQ		BIT(20)
#define HDMI21_SNPS_FIELD_TMDSQPCLK_OFF_CHG_IRQ		BIT(5)
#define HDMI21_SNPS_FIELD_TMDSQPCLK_LOCKED_CHG_IRQ	BIT(4)
#define HDMI21_SNPS_FIELD_AUDCLK_OFF_CHG_IRQ		BIT(1)
#define HDMI21_SNPS_FIELD_AUDCLK_LOCKED_CHG_IRQ		BIT(0)

/* ISR Main Unit 1 */
#define HDMI21_SNPS_REG_MAINUNIT_1_INT_MASK_N		(0x5024)
#define HDMI21_SNPS_REG_MAINUNIT_1_INT_CLEAR		(0x5028)
#define HDMI21_SNPS_REG_MAINUNIT_1_INT_FORCE		(0x502C)
#define HDMI21_SNPS_REG_MAINUNIT_1_INT_STATUS		(0x5020)
#define HDMI21_SNPS_FIELD_DDC_SCDC_ACTIVITY_IRQ		BIT(21)
#define HDMI21_SNPS_FIELD_DDC_HDCP_ACTIVITY_IRQ		BIT(20)
#define HDMI21_SNPS_FIELD_EARCTX_POWERED_DOWN_IRQ	BIT(17)
#define HDMI21_SNPS_FIELD_EARCTX_POWERED_UP_IRQ		BIT(16)
#define HDMI21_SNPS_FIELD_CEC_POWERED_DOWN_IRQ		BIT(13)
#define HDMI21_SNPS_FIELD_CEC_POWERED_UP_IRQ		BIT(12)
#define HDMI21_SNPS_FIELD_AVPUNIT_POWERED_DOWN_IRQ	BIT(1)
#define HDMI21_SNPS_FIELD_AVPUNIT_POWERED_UP_IRQ	BIT(0)

/* ISR Main Unit 2 */
#define HDMI21_SNPS_REG_MAINUNIT_2_INT_MASK_N		(0x5034)
#define HDMI21_SNPS_REG_MAINUNIT_2_INT_CLEAR		(0x5038)
#define HDMI21_SNPS_REG_MAINUNIT_2_INT_FORCE		(0x503C)
#define HDMI21_SNPS_REG_MAINUNIT_2_INT_STATUS		(0x5030)
#define HDMI21_SNPS_FIELD_PHYCREG_CR_TIMEOUT_IRQ	BIT(12)
#define HDMI21_SNPS_FIELD_PHYCREG_CR_READ_DONE_IRQ	BIT(11)
#define HDMI21_SNPS_FIELD_PHYCREG_CR_WRITE_DONE_IRQ	BIT(10)
#define HDMI21_SNPS_FIELD_PHYCREG_CR_SELECTOR_DONE_IRQ BIT(9)
#define HDMI21_SNPS_FIELD_PHYCREG_CR_SELECTIONMODE_DONE_IRQ BIT(8)
#define HDMI21_SNPS_FIELD_EARC_BPCLK_VALID_STABLE_CHG_IRQ	BIT(3)
#define HDMI21_SNPS_FIELD_TMDSVALID_STABLE_CHG_IRQ		BIT(1)
#define HDMI21_SNPS_FIELD_AUDPLL_LOCK_STABLE_CHG_IRQ	BIT(0)


/* ISR AVP Unit 0 */
#define HDMI21_SNPS_REG_AVPUNIT_0_INT_MASK_N		(0x5044)
#define HDMI21_SNPS_REG_AVPUNIT_0_INT_CLEAR			(0x5048)
#define HDMI21_SNPS_REG_AVPUNIT_0_INT_FORCE			(0x504C)
#define HDMI21_SNPS_REG_AVPUNIT_0_INT_STATUS		(0x5040)
#define HDMI21_SNPS_FIELD_CED_DYN_CNT_CH2_IRQ		BIT(22)
#define HDMI21_SNPS_FIELD_CED_DYN_CNT_CH1_IRQ		BIT(21)
#define HDMI21_SNPS_FIELD_CED_DYN_CNT_CH0_IRQ		BIT(20)
#define HDMI21_SNPS_FIELD_DESCRAND_SYNC_SEQ_ERR_IRQ	BIT(7)
#define HDMI21_SNPS_FIELD_DESCRAND_SYNC_IRQ			BIT(4)


/* ISR AVP Unit 1 */
#define HDMI21_SNPS_REG_AVPUNIT_1_INT_MASK_N		(0x5054)
#define HDMI21_SNPS_REG_AVPUNIT_1_INT_CLEAR			(0x5058)
#define HDMI21_SNPS_REG_AVPUNIT_1_INT_FORCE			(0x505C)
#define HDMI21_SNPS_REG_AVPUNIT_1_INT_STATUS		(0x5050)
#define HDMI21_SNPS_FIELD_VMON_VMEAS_IRQ			BIT(31)
#define HDMI21_SNPS_FIELD_VMON_HMEAS_IRQ			BIT(30)
#define HDMI21_SNPS_FIELD_AUD_CHSTATUS_SP3_IRQ		BIT(24)
#define HDMI21_SNPS_FIELD_AUD_CHSTATUS_SP2_IRQ		BIT(23)
#define HDMI21_SNPS_FIELD_AUD_CHSTATUS_SP1_IRQ		BIT(22)
#define HDMI21_SNPS_FIELD_AUD_CHSTATUS_SP0_IRQ		BIT(21)
#define HDMI21_SNPS_FIELD_AUD_MUTE_IRQ				BIT(20)
#define HDMI21_SNPS_FIELD_AFIFO_UNDERFLOW_IRQ		BIT(19)
#define HDMI21_SNPS_FIELD_AFIFO_OVERFLOW_IRQ		BIT(18)
#define HDMI21_SNPS_FIELD_AFIFO_THR_MUTE_LOW_IRQ	BIT(17)
#define HDMI21_SNPS_FIELD_AFIFO_THR_MUTE_HIGH_IRQ	BIT(16)
#define HDMI21_SNPS_FIELD_AFIFO_THR_LOW_IRQ			BIT(15)
#define HDMI21_SNPS_FIELD_AFIFO_THR_HIGH_IRQ		BIT(14)
#define HDMI21_SNPS_FIELD_AFIFO_THR_PASS_IRQ		BIT(13)
#define HDMI21_SNPS_FIELD_AUD_FMT_CHG_IRQ			BIT(12)
#define HDMI21_SNPS_FIELD_VPROC_SYNCGEN_IRQ			BIT(11)
#define HDMI21_SNPS_FIELD_VPROC_PP_DIFF_IRQ			BIT(10)
#define HDMI21_SNPS_FIELD_VPROC_CD_TIMEOUT_IRQ		BIT(9)
#define HDMI21_SNPS_FIELD_VPROC_CD_CHG_IRQ			BIT(8)
#define HDMI21_SNPS_FIELD_VSTREAM_FIFO_OVERFLOW_IRQ		BIT(7)
#define HDMI21_SNPS_FIELD_VSTREAM_FIFO_UNDERFLOW_IRQ 	BIT(6)
#define HDMI21_SNPS_FIELD_VSTREAM_FIFO_ALMOST_FULL_IRQ 	BIT(5)
#define HDMI21_SNPS_FIELD_VSTREAM_FIFO_ALMOST_EMPTY_IRQ BIT(4)
#define HDMI21_SNPS_FIELD_DEFRAMER_DVIHDMI_CHG_IRQ	BIT(3)
#define HDMI21_SNPS_FIELD_DEFRAMER_GBDET_ERR_IRQ	BIT(2)
#define HDMI21_SNPS_FIELD_DEFRAMER_VSYNC_THR_REACHED_IRQ	BIT(1)
#define HDMI21_SNPS_FIELD_DEFRAMER_VSYNC_IRQ		BIT(0)


/* ISR AVP Unit 2 */
#define HDMI21_SNPS_REG_AVPUNIT_2_INT_MASK_N		(0x5064)
#define HDMI21_SNPS_REG_AVPUNIT_2_INT_CLEAR			(0x5068)
#define HDMI21_SNPS_REG_AVPUNIT_2_INT_FORCE			(0x506C)
#define HDMI21_SNPS_REG_AVPUNIT_2_INT_STATUS		(0x5060)
#define HDMI21_SNPS_FIELD_FRL_CED_DYN_ERRCNT_THR_LANE3_IRQ	BIT(19)
#define HDMI21_SNPS_FIELD_FRL_CED_DYN_ERRCNT_THR_LANE2_IRQ	BIT(18)
#define HDMI21_SNPS_FIELD_FRL_CED_DYN_ERRCNT_THR_LANE1_IRQ	BIT(17)
#define HDMI21_SNPS_FIELD_FRL_CED_DYN_ERRCNT_THR_LANE0_IRQ	BIT(16)
#define HDMI21_SNPS_FIELD_UNPACKER_TYPE_ERR_CNT_IRQ		BIT(11)
#define HDMI21_SNPS_FIELD_UNPACKER_LENGTH_ERR_CNT_IRQ	BIT(10)
#define HDMI21_SNPS_FIELD_UNPACKER_FIFO_UNDERFLOW_IRQ	BIT(9)
#define HDMI21_SNPS_FIELD_UNPACKER_FIFO_OVERFLOW_IRQ	BIT(8)
#define HDMI21_SNPS_FIELD_FRL_DESCRAMB_SYNC_IRQ			BIT(4)
#define HDMI21_SNPS_FIELD_MARKER_SB_SIZE_IRQ			BIT(1)
#define HDMI21_SNPS_FIELD_MARKER_SB_COUNT_IRQ			BIT(0)

/* ISR PKT 0 */
#define HDMI21_SNPS_REG_PKT_0_INT_MASK_N			(0x5084)
#define HDMI21_SNPS_REG_PKT_0_INT_CLEAR				(0x5088)
#define HDMI21_SNPS_REG_PKT_0_INT_FORCE				(0x508C)
#define HDMI21_SNPS_REG_PKT_0_INT_STATUS			(0x5080)
#define HDMI21_SNPS_FIELD_PKTDEC_VTEM_CHG_IRQ		BIT(23)
#define HDMI21_SNPS_FIELD_PKTDEC_CVTEM_CHG_IRQ		BIT(22)
#define HDMI21_SNPS_FIELD_PKTDEC_EMD_CHG_IRQ		BIT(21)
#define HDMI21_SNPS_FIELD_PKTDEC_GENPKT1_CHG_IRQ	BIT(18)
#define HDMI21_SNPS_FIELD_PKTDEC_GENPKT0_CHG_IRQ	BIT(17)
#define HDMI21_SNPS_FIELD_PKTDEC_DRMIF_CHG_IRQ		BIT(16)
#define HDMI21_SNPS_FIELD_PKTDEC_NTSCVBIIF_CHG_IRQ	BIT(15)
#define HDMI21_SNPS_FIELD_PKTDEC_AUDIF_CHG_IRQ		BIT(13)
#define HDMI21_SNPS_FIELD_PKTDEC_SRCPDIF_CHG_IRQ	BIT(12)
#define HDMI21_SNPS_FIELD_PKTDEC_AVIIF_CHG_IRQ		BIT(11)
#define HDMI21_SNPS_FIELD_PKTDEC_VSIF_CHG_IRQ		BIT(10)
#define HDMI21_SNPS_FIELD_PKTDEC_AMD_CHG_IRQ		BIT(9)
#define HDMI21_SNPS_FIELD_PKTDEC_GMD_CHG_IRQ		BIT(8)
#define HDMI21_SNPS_FIELD_PKTDEC_ISRC2_CHG_IRQ		BIT(7)
#define HDMI21_SNPS_FIELD_PKTDEC_ISRC1_CHG_IRQ		BIT(6)
#define HDMI21_SNPS_FIELD_PKTDEC_ACP_CHG_IRQ		BIT(5)
#define HDMI21_SNPS_FIELD_PKTDEC_GCP_CHG_IRQ		BIT(4)
#define HDMI21_SNPS_FIELD_PKTDEC_ACR_CHG_IRQ		BIT(3)
#define HDMI21_SNPS_FIELD_PKTDEC_ACP_TIMEOUT_IRQ	BIT(2)
#define HDMI21_SNPS_FIELD_PKTDEC_ACR_N_CHG_IRQ		BIT(1)
#define HDMI21_SNPS_FIELD_PKTDEC_ACR_CTS_CHG_IRQ	BIT(0)

/* ISR PKT 1 */
#define HDMI21_SNPS_REG_PKT_1_INT_MASK_N			(0x5094)
#define HDMI21_SNPS_REG_PKT_1_INT_CLEAR				(0x5098)
#define HDMI21_SNPS_REG_PKT_1_INT_FORCE				(0x509C)
#define HDMI21_SNPS_REG_PKT_1_INT_STATUS			(0x5090)
#define HDMI21_SNPS_FIELD_PKTFIFO_NEW_ENTRY_IRQ		BIT(6)
#define HDMI21_SNPS_FIELD_PKTFIFO_OVERFLOW_IRQ		BIT(5)
#define HDMI21_SNPS_FIELD_PKTFIFO_UNDERFLOW_IRQ		BIT(4)
#define HDMI21_SNPS_FIELD_PKTFIFO_THR_HIGH_IRQ		BIT(2)
#define HDMI21_SNPS_FIELD_PKTFIFO_THR_PASS_IRQ		BIT(1)
#define HDMI21_SNPS_FIELD_PKTFIFO_THR_LOW_IRQ		BIT(0)

/* ISR PKT 2 */
#define HDMI21_SNPS_REG_PKT_2_INT_MASK_N			(0x50A4)
#define HDMI21_SNPS_REG_PKT_2_INT_CLEAR				(0x50A8)
#define HDMI21_SNPS_REG_PKT_2_INT_FORCE				(0x50AC)
#define HDMI21_SNPS_REG_PKT_2_INT_STATUS			(0x50A0)
#define HDMI21_SNPS_FIELD_PKTDEC_VTEM_RCV_IRQ		BIT(23)
#define HDMI21_SNPS_FIELD_PKTDEC_CVTEM_RCV_IRQ		BIT(22)
#define HDMI21_SNPS_FIELD_PKTDEC_EMD_RCV_IRQ		BIT(21)
#define HDMI21_SNPS_FIELD_PKTDEC_GENPKT1_RCV_IRQ	BIT(18)
#define HDMI21_SNPS_FIELD_PKTDEC_GENPKT0_RCV_IRQ	BIT(17)
#define HDMI21_SNPS_FIELD_PKTDEC_DRMIF_RCV_IRQ		BIT(16)
#define HDMI21_SNPS_FIELD_PKTDEC_NTSCVBIIF_RCV_IRQ	BIT(15)
#define HDMI21_SNPS_FIELD_PKTDEC_AUDIF_RCV_IRQ		BIT(13)
#define HDMI21_SNPS_FIELD_PKTDEC_SRCPDIF_RCV_IRQ	BIT(12)
#define HDMI21_SNPS_FIELD_PKTDEC_AVIIF_RCV_IRQ		BIT(11)
#define HDMI21_SNPS_FIELD_PKTDEC_VSIF_RCV_IRQ		BIT(10)
#define HDMI21_SNPS_FIELD_PKTDEC_AMD_RCV_IRQ		BIT(9)
#define HDMI21_SNPS_FIELD_PKTDEC_GMD_RCV_IRQ		BIT(8)
#define HDMI21_SNPS_FIELD_PKTDEC_ISRC2_RCV_IRQ		BIT(7)
#define HDMI21_SNPS_FIELD_PKTDEC_ISRC1_RCV_IRQ		BIT(6)
#define HDMI21_SNPS_FIELD_PKTDEC_ACP_RCV_IRQ		BIT(5)
#define HDMI21_SNPS_FIELD_PKTDEC_GCP_RCV_IRQ		BIT(4)
#define HDMI21_SNPS_FIELD_PKTDEC_ACR_RCV_IRQ		BIT(3)


/* ISR SCDC */
#define HDMI21_SNPS_REG_SCDC_INT_MASK_N			(0x50C4)
#define HDMI21_SNPS_REG_SCDC_INT_CLEAR			(0x50C8)
#define HDMI21_SNPS_REG_SCDC_INT_FORCE			(0x50CC)
#define HDMI21_SNPS_REG_SCDC_INT_STATUS			(0x50C0)
#define HDMI21_SNPS_FIELD_FRL_START_TIMEOUT_IRQ	BIT(3)
#define HDMI21_SNPS_FIELD_SCDCTMDSCCFG_CHG_IRQ	BIT(2)
#define HDMI21_SNPS_FIELD_SCDCSCSTATUS_CHG_IRQ	BIT(1)
#define HDMI21_SNPS_FIELD_SCDCCFG_CHG_IRQ		BIT(0)

/* ISR HDCP */
#define HDMI21_SNPS_REG_HDCP_INT_MASK_N			(0x50D4)
#define HDMI21_SNPS_REG_HDCP_INT_CLEAR			(0x50D8)
#define HDMI21_SNPS_REG_HDCP_INT_FORCE			(0x50DC)
#define HDMI21_SNPS_REG_HDCP_INT_STATUS			(0x50D0)
#define HDMI21_SNPS_FIELD_HDCP2_DECRYPTED_CHG_IRQ		BIT(21)
#define HDMI21_SNPS_FIELD_HDCP2_AUTHENTICATION_FAIL_IRQ	BIT(20)
#define HDMI21_SNPS_FIELD_HDCP2_AUTHENTICATED_IRQ		BIT(19)
#define HDMI21_SNPS_FIELD_HDCP2_AUTHENTICATION_LOST_IRQ	BIT(18)
#define HDMI21_SNPS_FIELD_HDCP2_NOT_CAPABLE_IRQ			BIT(17)
#define HDMI21_SNPS_FIELD_HDCP2_CAPABLE_IRQ				BIT(16)
#define HDMI21_SNPS_FIELD_HDCP_DKSET_DONE_IRQ			BIT(10)
#define HDMI21_SNPS_FIELD_HDCP14_OESS_EESS_CHG_IRQ		BIT(9)
#define HDMI21_SNPS_FIELD_HDCP14_ENCDIS_IRQ				BIT(8)
#define HDMI21_SNPS_FIELD_HDCP14_ENCEN_IRQ				BIT(7)
#define HDMI21_SNPS_FIELD_HDCP14_AUTH_IRQ				BIT(6)
#define HDMI21_SNPS_FIELD_HDCP14_BSTATUS_READ_IRQ		BIT(5)
#define HDMI21_SNPS_FIELD_HDCP14_BCAPS_READ_IRQ			BIT(4)
#define HDMI21_SNPS_FIELD_HDCP14_RI_READ_IRQ			BIT(2)
#define HDMI21_SNPS_FIELD_HDCP14_BKSV_READ_IRQ			BIT(1)
#define HDMI21_SNPS_FIELD_HDCP14_AKSV_RCV_IRQ			BIT(0)

/* ISR HDCP 1 */
#define HDMI21_SNPS_REG_HDCP_1_INT_MASK_N			(0x50E4)
#define HDMI21_SNPS_REG_HDCP_1_INT_CLEAR			(0x50E8)
#define HDMI21_SNPS_REG_HDCP_1_INT_FORCE			(0x50EC)
#define HDMI21_SNPS_REG_HDCP_1_INT_STATUS			(0x50E0)
#define HDMI21_SNPS_FIELD_HDCP2_ESM_P0_GPIO_OUT_15_CHG_IRQ	BIT(10)
#define HDMI21_SNPS_FIELD_HDCP2_ESM_P0_GPIO_OUT_14_CHG_IRQ	BIT(9)
#define HDMI21_SNPS_FIELD_HDCP2_ESM_P0_GPIO_OUT_13_CHG_IRQ	BIT(8)
#define HDMI21_SNPS_FIELD_HDCP2_ESM_P0_GPIO_OUT_12_CHG_IRQ	BIT(7)
#define HDMI21_SNPS_FIELD_HDCP2_ESM_P0_GPIO_OUT_11_CHG_IRQ	BIT(6)
#define HDMI21_SNPS_FIELD_HDCP2_ESM_P0_GPIO_OUT_10_CHG_IRQ	BIT(5)
#define HDMI21_SNPS_FIELD_HDCP2_ESM_P0_GPIO_OUT_9_CHG_IRQ	BIT(4)
#define HDMI21_SNPS_FIELD_HDCP2_ESM_P0_GPIO_OUT_8_CHG_IRQ	BIT(3)
#define HDMI21_SNPS_FIELD_HDCP2_ESM_P0_GPIO_OUT_7_CHG_IRQ	BIT(2)
#define HDMI21_SNPS_FIELD_HDCP2_ESM_P0_GPIO_OUT_6_CHG_IRQ	BIT(1)
#define HDMI21_SNPS_FIELD_HDCP2_ESM_P0_GPIO_OUT_5_CHG_IRQ	BIT(0)

/* ISR EARC */
#define HDMI21_SNPS_REG_EARC_INT_MASK_N			(0x5304)
#define HDMI21_SNPS_REG_EARC_INT_CLEAR			(0x5308)
#define HDMI21_SNPS_REG_EARC_INT_FORCE			(0x530C)
#define HDMI21_SNPS_REG_EARC_INT_STATUS			(0x5300)

#define HDMI21_SNPS_FIELD_EARCTX_CMDC_XACT_DONE_IRQ				BIT(18)
#define HDMI21_SNPS_FIELD_EARCTX_CMDC_RXPKT_BADPAR_IRQ			BIT(17)
#define HDMI21_SNPS_FIELD_EARCTX_CMDC_RXPKT_BADECC_IRQ			BIT(16)
#define HDMI21_SNPS_FIELD_EARCTX_CMDC_RXPKT_INCOMPLETE_IRQ		BIT(15)
#define HDMI21_SNPS_FIELD_EARCTX_CMDC_RXPKT_BADSYNC_IRQ			BIT(14)
#define HDMI21_SNPS_FIELD_EARCTX_CMDC_RXPKT_BADPREAMBLE_IRQ 	BIT(13)
#define HDMI21_SNPS_FIELD_EARCTX_CMDC_HEARTBEAT_CAP_CHNG_IRQ	BIT(12)
#define HDMI21_SNPS_FIELD_EARCTX_CMDC_HEARTBEAT_STAT_CHNG_IRQ	BIT(11)
#define HDMI21_SNPS_FIELD_EARCTX_CMDC_HEARTBEAT_LOST_IRQ		BIT(10)
#define HDMI21_SNPS_FIELD_EARCTX_CMDC_DISCOVERY_TIMEOUT_IRQ		BIT(9)
#define HDMI21_SNPS_FIELD_EARCTX_CMDC_DISCOVERY_DONE_IRQ		BIT(8)
#define HDMI21_SNPS_FIELD_EARCTX_DMAC_MUTE_REQUEST_IRQ			BIT(2)
#define HDMI21_SNPS_FIELD_EARCTX_DMAC_AUDIO_FIFO_OVERFLOW_IRQ	BIT(1)
#define HDMI21_SNPS_FIELD_EARCTX_DMAC_AUDIO_FIFO_UNDERFLOW_IRQ	BIT(0)



/*----------------------------------------------------------------------------------------
	Macro Definitions
----------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------
    Type Definitions
----------------------------------------------------------------------------------------*/
/* The Order in this Enum structure reflects to the ISR priority.
 * First order of enum value is the 1st priority, and last is the least important */
typedef enum
{
	HDMI21_IRQ_SNPS_HDCP_1_INTVEC,
	HDMI21_IRQ_SNPS_HDCP_INTVEC,
	HDMI21_IRQ_SNPS_SCDC_INTVEC,
	HDMI21_IRQ_SNPS_PKT_2_INTVEC,
	HDMI21_IRQ_SNPS_PKT_1_INTVEC,
	HDMI21_IRQ_SNPS_PKT_0_INTVEC,
	HDMI21_IRQ_SNPS_AVPUNIT_2_INTVEC,
	HDMI21_IRQ_SNPS_AVPUNIT_1_INTVEC,
	HDMI21_IRQ_SNPS_AVPUNIT_0_INTVEC,
	HDMI21_IRQ_SNPS_MAINUNIT_2_INTVEC,
	HDMI21_IRQ_SNPS_MAINUNIT_1_INTVEC,
	HDMI21_IRQ_SNPS_MAINUNIT_0_INTVEC,
	HDMI21_IRQ_SNPS_EARC_INTVEC,
	HDMI21_IRQ_SNPS_MAXNUM
} HDMI21_ISRUNIT_SNPS_TYPE_T;


/*----------------------------------------------------------------------------------------
	Extern Function Prototype Declaration
----------------------------------------------------------------------------------------*/
void	HDMI21_ISRUNIT_Rx_Initiate(HDMI21_HAL_RX_DEVICE_DATA *pDevHandler);
int		HDMI21_ISRUNIT_Rx_ProcessIRQ(HDMI21_HAL_RX_DEVICE_DATA *pDevHandler);
void	HDMI21_ISRUNIT_Rx_Set_IsrMaskValue(HDMI21_ISRUNIT_SNPS_TYPE_T type, UINT32 val);
void 	HDMI21_ISRUNIT_Rx_Set_ForceIsrSet(HDMI21_HAL_RX_DEVICE_DATA *pDevHandler, HDMI21_ISRUNIT_SNPS_TYPE_T type, UINT32 val);
UINT32	HDMI21_ISRUNIT_Rx_Get_IsrMaskValue(HDMI21_ISRUNIT_SNPS_TYPE_T type);
int 	HDMI21_ISRUNIT_Rx_ProcessEarcIRQ(HDMI21_HAL_RX_DEVICE_DATA *pDevHandler);
void 	HDMI21_ISRUNIT_Rx_Set_RegisterEarcDmacIsrCallBack(void (* function)(UINT32 intStatus));

char *__isrvec_type_to_str(HDMI21_ISRUNIT_SNPS_TYPE_T type);
/*----------------------------------------------------------------------------------------
	Extern Variables
----------------------------------------------------------------------------------------*/

#ifdef	__cplusplus
}
#endif /* __cplusplus */

#endif /* _PROTOS_H_ */

