ccflags-y		:= -I$(srctree)/drivers/block/zram/

obj-$(CONFIG_WEBOS)		+= webos.o
obj-$(CONFIG_LOW_MEM_NOTIFY)	+= low-mem-notify.o
obj-$(CONFIG_SYSRQ_LOG_PRINT)	+= sysrq.o
obj-$(CONFIG_KMSG_RAW)		+= kmsg_raw.o
obj-$(CONFIG_USER_INITCALL)	+= user_initcall.o
obj-$(CONFIG_FAULT_NOTIFIER)	+= fault_notifier.o
obj-$(CONFIG_GPU_INFO)		+= gpuinfo.o
obj-$(CONFIG_MRI_HELPER)	+= mri_helper.o
obj-$(CONFIG_KERNEL_MODE_ONLY)	+= kernel_mode_init.o
obj-$(CONFIG_KDUMP_LG1K)	+= lg1k_kmo_kdump.o

obj-y				+= logger/
